"use client";

import { useActionState } from "react";
import type { ManagementEmployeeDetail } from "@/modules/employees/employee-services";
import { grantAdminScopeAction, revokeAdminScopeAction, setEmployeeLifecycleAction, updateEmployeeAssignmentsAction, updateEmployeeBasicAction, updateEmployeeRoleAction, type EmployeeMutationAction, type EmployeeMutationState } from "@/modules/employees/employee-management-actions";

const initial: EmployeeMutationState = {};
function Feedback({ state }: { state: EmployeeMutationState }) { return state.error ? <p className="employee-form-error" role="alert">{state.error}</p> : state.success ? <p className="employee-form-success" role="status">{state.success}</p> : null; }
function ManagedForm({ action, children, submitLabel = "Save changes", danger = false }: { action: EmployeeMutationAction; children: React.ReactNode; submitLabel?: string; danger?: boolean }) { const [state, formAction, pending] = useActionState(action, initial); return <form action={formAction} className="employee-management-form">{children}<Feedback state={state} /><button className={`button ${danger ? "danger" : "primary"}`} type="submit" disabled={pending} onClick={danger ? (event) => { if (!window.confirm(submitLabel === "Deactivate employee" ? "Deactivate this employee and revoke their active sessions?" : "Reactivate this employee?") ) event.preventDefault(); } : undefined}>{pending ? "Saving…" : submitLabel}</button></form>; }

export function EmployeeManagementPanel({ employee, options }: { employee: ManagementEmployeeDetail; options: { designations: { id: string; name: string }[]; managers: { userId: string; displayName: string }[]; scopes: { id: string; scopeReference: string; active: boolean; version: number }[] } }) {
  const hidden = <><input type="hidden" name="userId" value={employee.userId} /><input type="hidden" name="expectedVersion" value={employee.version} /></>;
  return <section className="employee-management-panel" aria-labelledby="employee-management-title"><h3 id="employee-management-title">Super Admin controls</h3>
    <ManagedForm action={updateEmployeeBasicAction}>{hidden}<label>Display name<input name="displayName" defaultValue={employee.user.displayName} maxLength={120} required /></label><label>Employee code<input name="employeeCode" defaultValue={employee.employeeCode} maxLength={64} required /></label><label>Work email<input name="workEmail" type="email" defaultValue={employee.workEmail ?? ""} maxLength={254} /></label><label>Work phone<input name="workPhone" defaultValue={employee.workPhone ?? ""} maxLength={40} /></label><label>Professional summary<textarea name="professionalSummary" defaultValue={employee.professionalSummary ?? ""} maxLength={2000} rows={3} /></label></ManagedForm>
    <ManagedForm action={updateEmployeeAssignmentsAction}>{hidden}<label>Designation<select name="designationId" defaultValue={employee.designationId ?? ""}><option value="">Unassigned</option>{options.designations.map((designation) => <option key={designation.id} value={designation.id}>{designation.name}</option>)}</select></label><label>Manager<select name="managerUserId" defaultValue={employee.managerUserId ?? ""}><option value="">No manager</option>{options.managers.map((manager) => <option key={manager.userId} value={manager.userId}>{manager.displayName}</option>)}</select></label><label>Team<input name="team" defaultValue={employee.team ?? ""} placeholder="team:alpha" maxLength={120} /></label><label>Working pattern <span className="employee-optional">informational only</span><input name="workingPattern" defaultValue={employee.workingPattern ?? ""} maxLength={120} /></label></ManagedForm>
    <ManagedForm action={updateEmployeeRoleAction}>{hidden}<label>System role<select name="role" defaultValue={employee.user.role}><option value="SUPER_ADMIN">Super Admin</option><option value="ADMIN">Admin</option><option value="EMPLOYEE">Employee</option></select></label><p>Changing a role never grants TEAM scope. Existing sessions are revoked.</p></ManagedForm>
    <ManagedForm action={setEmployeeLifecycleAction} submitLabel={employee.user.active ? "Deactivate employee" : "Reactivate employee"} danger>{hidden}<input type="hidden" name="active" value={String(!employee.user.active)} /><p>{employee.user.active ? "Deactivation revokes active sessions. This cannot be undone by the employee." : "Reactivation restores only active status."}</p></ManagedForm>
    {employee.user.role === "ADMIN" ? <section className="employee-scope-controls" aria-labelledby="employee-scope-title"><h4 id="employee-scope-title">Admin TEAM scope</h4><p>Scope is explicit and independent from the employee’s team or role.</p><ManagedForm action={grantAdminScopeAction}>{hidden}<label>TEAM scope<input name="team" placeholder="team:alpha" maxLength={120} required /></label></ManagedForm><ul>{options.scopes.filter((scope) => scope.active).map((scope) => <li key={scope.id}>{scope.scopeReference}<form action={async (formData) => { await revokeAdminScopeAction(initial, formData); }}><input type="hidden" name="userId" value={employee.userId} /><input type="hidden" name="grantId" value={scope.id} /><input type="hidden" name="expectedVersion" value={scope.version} /><button className="button directory-clear" type="submit">Revoke</button></form></li>)}</ul></section> : null}
  </section>;
}
