import { WorkflowFeedback } from "@/shared/components/workflow-feedback";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getCurrentActor } from "@/modules/auth/session-service";
import { TaskDialog } from "@/shared/components/task-dialog";
import { organisationService } from "./organisation-service";
import { CatalogueNameForm, MembershipForm } from "./organisation-forms";

export async function OrganisationPage({ kind }: { kind: "team" | "designation" }) {
  const actor = await getCurrentActor(); if (!actor) redirect("/login"); if (actor.role !== "SUPER_ADMIN") notFound();
  const data = await organisationService.list(actor); const records = kind === "team" ? data.teams : data.designations; const title = kind === "team" ? "Teams" : "Designations";
  return <section className="operations-page workflow-page"><WorkflowFeedback /><header className="operations-heading"><div><p className="eyebrow">People</p><h2>{title}</h2><p>{kind === "team" ? "Create teams and manage their members. Access permissions are managed separately." : "Create job designations and assign people to them. System roles are managed separately."}</p></div><TaskDialog triggerLabel={`New ${kind}`} title={`Create ${kind}`}><CatalogueNameForm kind={kind} /></TaskDialog></header><nav className="catalogue-links" aria-label="People management"><Link href="/employees">Employees</Link><Link href={kind === "team" ? "/designations" : "/teams"}>{kind === "team" ? "Designations" : "Teams"}</Link></nav><div className="catalogue-grid">{records.map((record) => { const members = data.members.filter((person) => (kind === "team" ? person.team : person.designationId) === record.id); const active = !("active" in record) || record.active; return <article className="operation-panel" key={record.id}><div className="schedule-panel-heading"><h3>{record.name}</h3><span className="workflow-count">{members.length} member{members.length === 1 ? "" : "s"}</span></div>{!active ? <p className="workflow-inline-note">Archived designation · existing membership retained.</p> : null}<div className="workflow-row-actions">{record.version > 0 ? <TaskDialog triggerLabel={`Rename ${record.name}`} triggerText="Rename" title={`Rename ${kind}`} triggerClassName="button"><CatalogueNameForm kind={kind} record={record} /></TaskDialog> : null}{active ? <TaskDialog triggerLabel={`Add member to ${record.name}`} triggerText="Add member" title={`Add to ${record.name}`} triggerClassName="button"><MembershipForm kind={kind} reference={record.id} members={data.members} /></TaskDialog> : null}</div>{members.length ? <ul className="catalogue-members">{members.map((person) => <li key={person.id}><span><Link href={`/employees/${person.id}`}>{person.name}</Link><small> · {person.role === "SUPER_ADMIN" ? "Super Admin" : person.role === "ADMIN" ? "Admin" : "Employee"}{!person.active ? " · inactive" : ""}</small></span><TaskDialog triggerLabel={`Remove ${person.name} from ${record.name}`} triggerText="Remove" title="Remove membership" triggerClassName="button"><MembershipForm kind={kind} reference={record.id} members={data.members} remove={person} /></TaskDialog></li>)}</ul> : <p>No members yet. Add a person to build this {kind === "team" ? "team" : "designation’s membership"}.</p>}</article>; })}</div>{!records.length ? <div className="workflow-empty"><h3>No {title.toLowerCase()} yet</h3><p>Create a {kind} to make it available in Employee assignments.</p></div> : null}</section>;
}
