"use client";
/* eslint-disable @next/next/no-img-element -- external raster tiles must remain browser-only and bypass server optimization. */
import { useMemo, useRef, useState } from "react";
import type { PlanningProjection } from "@/modules/maps/service";
import { osmRasterAttribution } from "@/modules/maps/map-adapter";

function tile(latitude: number, longitude: number, zoom: number) { const n = 2 ** zoom; return { x: Math.floor((longitude + 180) / 360 * n), y: Math.floor((1 - Math.asinh(Math.tan(latitude * Math.PI / 180)) / Math.PI) / 2 * n) }; }
export function PlanningMapClient({ projection }: { projection: PlanningProjection }) {
  const [selected, setSelected] = useState<string | null>(projection.assignments[0]?.id ?? null); const [zoom, setZoom] = useState(11); const [tileFailed, setTileFailed] = useState(false); const drag = useRef<{ x: number; y: number } | null>(null);
  const markers = useMemo(() => projection.assignments.flatMap((assignment) => { const result: Array<{ key: string; kind: "employee" | "worksite"; coordinate: { latitude: number; longitude: number }; assignment: PlanningProjection["assignments"][number] }> = []; if (assignment.employeeCoordinate) result.push({ key: `e-${assignment.id}`, kind: "employee", coordinate: assignment.employeeCoordinate, assignment }); if (assignment.worksite.coordinate) result.push({ key: `w-${assignment.id}`, kind: "worksite", coordinate: assignment.worksite.coordinate, assignment }); return result; }), [projection.assignments]);
  const [centre, setCentre] = useState(markers[0]?.coordinate ?? { latitude: 25.2048, longitude: 55.2708 }); const base = tile(centre.latitude, centre.longitude, zoom); const active = projection.assignments.find((item) => item.id === selected) ?? null;
  const position = (coordinate: { latitude: number; longitude: number }) => ({ x: Math.max(4, Math.min(96, 50 + (coordinate.longitude - centre.longitude) * (18 + zoom))), y: Math.max(5, Math.min(94, 50 - (coordinate.latitude - centre.latitude) * (22 + zoom))) });
  const pan = (event: React.PointerEvent<HTMLElement>) => { if (!drag.current) return; const dx = event.clientX - drag.current.x; const dy = event.clientY - drag.current.y; drag.current = { x: event.clientX, y: event.clientY }; setCentre((value) => ({ latitude: Math.max(-85, Math.min(85, value.latitude + dy / (22 + zoom))), longitude: Math.max(-180, Math.min(180, value.longitude - dx / (18 + zoom))) })); };
  return <div className="planning-map-client"><section className="planning-map-canvas" aria-label="Static planning map" aria-describedby="map-provider-notice" onPointerDown={(event) => { if (event.target === event.currentTarget || (event.target as HTMLElement).classList.contains("planning-map-tiles")) { drag.current = { x: event.clientX, y: event.clientY }; event.currentTarget.setPointerCapture(event.pointerId); } }} onPointerMove={pan} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}>
    {tileFailed ? <div className="planning-map-tile-failure" role="alert"><strong>Map tiles could not be loaded.</strong><span>The authorized planning list remains available below.</span></div> : <div className="planning-map-tiles" aria-hidden="true">{[-1, 0, 1].flatMap((dy) => [-1, 0, 1].map((dx) => <img key={`${dx}:${dy}:${zoom}`} src={`https://tile.openstreetmap.org/${zoom}/${base.x + dx}/${base.y + dy}.png`} alt="" onError={() => setTileFailed(true)} />))}</div>}
    <div className="planning-map-controls"><button type="button" onClick={() => setZoom((value) => Math.min(18, value + 1))} aria-label="Zoom in">+</button><button type="button" onClick={() => setZoom((value) => Math.max(3, value - 1))} aria-label="Zoom out">−</button></div>
    {!tileFailed ? <><svg className="planning-map-lines" aria-label="Static planned associations" role="img">{projection.assignments.flatMap((assignment) => assignment.employeeCoordinate && assignment.worksite.coordinate ? [{ assignment, from: position(assignment.employeeCoordinate), to: position(assignment.worksite.coordinate) }] : []).map(({ assignment, from, to }) => <line key={assignment.id} className={selected === assignment.id ? "selected" : ""} x1={`${from.x}%`} y1={`${from.y}%`} x2={`${to.x}%`} y2={`${to.y}%`} aria-label={`Static planned association: ${assignment.label}`} />)}</svg><div className="planning-map-markers">{markers.map((marker) => { const point = position(marker.coordinate); return <button type="button" key={marker.key} className={`map-marker ${marker.kind} ${selected === marker.assignment.id ? "selected" : ""}`} style={{ left: `${point.x}%`, top: `${point.y}%` }} onClick={() => setSelected(marker.assignment.id)} aria-label={`${marker.kind === "employee" ? "Employee" : "Worksite"}: ${marker.kind === "employee" ? marker.assignment.employeeName : marker.assignment.worksite.name}`}>{marker.kind === "employee" ? "E" : "W"}</button>; })}</div></> : null}
    <p id="map-provider-notice" className="planning-map-attribution">{osmRasterAttribution}. Tile requests are made by your browser and may reveal the viewed geographic area; no ScopeIs identifiers or planning data are sent.</p>
  </section>
  <section className="planning-map-legend" aria-label="Map legend"><span><i className="employee" />Employee planning marker</span><span><i className="worksite" />Authorized worksite marker</span><span><i className="association" />Static planned association, not a route.</span></section>
  {active ? <section className="planning-map-detail" aria-live="polite"><h3>{active.employeeName}</h3><p>{active.client.name} · {active.project.name} · {active.worksite.name}</p><p>{active.employeePrecision === "coarse" ? "Coarse planning area" : active.employeePrecision === "exact" ? "Stored planning marker" : "No employee planning coordinate"}{active.unavailable ? " · Approved unavailable" : ""}{active.coverageGap ? " · Authorized coverage gap" : ""}</p></section> : null}
  <section className="planning-map-list" aria-label="Authorized planning list"><h3>Authorized planning list</h3>{projection.assignments.map((assignment) => <button type="button" key={assignment.id} className={selected === assignment.id ? "selected" : ""} onClick={() => setSelected(assignment.id)}><strong>{assignment.employeeName}</strong><span>{assignment.client.name} · {assignment.project.name} · {assignment.worksite.name}</span><span>{assignment.unavailable ? "Approved unavailable · " : ""}{assignment.coverageGap ? "Coverage gap · " : ""}{assignment.employeeCoordinate ? assignment.employeePrecision === "coarse" ? "Coarse planning area" : "Planning marker" : "No planning coordinate"}</span></button>)}</section>
  </div>;
}
