import "server-only";
import { coverageService } from "@/modules/coverage/service";
import { hasOperationalTargetScope } from "@/modules/authorization/operational-scope";
import { mapRepository } from "@/modules/maps/repositories";
import { parseMapQuery, coarseCoordinate } from "@/modules/maps/validation";
import type { AuthenticatedActor } from "@/shared/types/foundation";

type Row = Awaited<ReturnType<typeof mapRepository.publishedAssignments>>[number];
function employeeVisible(actor: AuthenticatedActor, team: string | null) { return actor.role === "SUPER_ADMIN" || (actor.role === "ADMIN" && team != null && actor.scopes.some((grant) => grant.type === "TEAM" && grant.reference === team)); }
function operationalVisible(actor: AuthenticatedActor, row: Row) { return hasOperationalTargetScope(actor, actor.scopes.map((x) => ({ scopeType: x.type, scopeReference: x.reference })), "PROJECT", row.project.id, row.period.clientId) || hasOperationalTargetScope(actor, actor.scopes.map((x) => ({ scopeType: x.type, scopeReference: x.reference })), "LOCATION", row.location.id, row.period.clientId); }
export type PlanningProjection = { selectedDate: string; invalidFilter: boolean; role: "SUPER_ADMIN" | "ADMIN"; assignments: Array<{ id: string; employeeId: string; employeeName: string; employeeCoordinate: { latitude: number; longitude: number } | null; employeePrecision: "exact" | "coarse" | null; worksite: { id: string; name: string; coordinate: { latitude: number; longitude: number } | null }; client: { id: string; name: string }; project: { id: string; name: string }; unavailable: boolean; skills: Array<{ id: string; name: string }>; coverageGap: boolean; label: string }>; filterOptions: { employees: Array<{ id: string; name: string }>; skills: Array<{ id: string; name: string }>; clients: Array<{ id: string; name: string }>; projects: Array<{ id: string; name: string }>; locations: Array<{ id: string; name: string }> }; lastPublishedAt: string | null; noCoordinateCount: number; };

export class PlanningMapService {
  async projection(actor: AuthenticatedActor, input: unknown): Promise<PlanningProjection> {
    if (actor.role === "EMPLOYEE") throw new Error("FORBIDDEN");
    const query = parseMapQuery(input); const fallbackDate = typeof (input as { date?: unknown }).date === "string" ? (input as { date: string }).date : "";
    if (!query) return { selectedDate: fallbackDate, invalidFilter: true, role: actor.role, assignments: [], filterOptions: { employees: [], skills: [], clients: [], projects: [], locations: [] }, lastPublishedAt: null, noCoordinateCount: 0 };
    const allowed = (await mapRepository.publishedAssignments(query.date)).filter((row) => employeeVisible(actor, row.profile.team) && operationalVisible(actor, row));
    const unavailable = new Set((await mapRepository.approvedUnavailable([...new Set(allowed.map((row) => row.employee.id))], query.date)).map((row) => row.employeeUserId));
    const skills = await mapRepository.employeeSkillRows([...new Set(allowed.map((row) => row.employee.id))]); const byEmployee = new Map<string, Array<{ id: string; name: string }>>(); for (const skill of skills) byEmployee.set(skill.employeeUserId, [...(byEmployee.get(skill.employeeUserId) ?? []), { id: skill.skillId, name: skill.skillName }]);
    const options = { employees: [...new Map(allowed.map((r) => [r.employee.id, { id: r.employee.id, name: r.employee.displayName }])).values()], skills: [...new Map(skills.map((s) => [s.skillId, { id: s.skillId, name: s.skillName }])).values()], clients: [...new Map(allowed.map((r) => [r.client.id, { id: r.client.id, name: r.client.companyName }])).values()], projects: [...new Map(allowed.map((r) => [r.project.id, { id: r.project.id, name: r.project.name }])).values()], locations: [...new Map(allowed.map((r) => [r.location.id, { id: r.location.id, name: r.location.name }])).values()] };
    const requestedIds = [query.employeeId && options.employees.some((x) => x.id === query.employeeId), query.skillId && options.skills.some((x) => x.id === query.skillId), query.clientId && options.clients.some((x) => x.id === query.clientId), query.projectId && options.projects.some((x) => x.id === query.projectId), query.locationId && options.locations.some((x) => x.id === query.locationId)]; if (requestedIds.some((x) => x === false)) return { selectedDate: query.date, invalidFilter: true, role: actor.role, assignments: [], filterOptions: options, lastPublishedAt: null, noCoordinateCount: 0 };
    const result = [] as PlanningProjection["assignments"]; for (const row of allowed) { const employeeSkills = byEmployee.get(row.employee.id) ?? []; const gap = (await coverageService.gaps(actor, row.assignment.id)).length > 0; const marker = row.planning ? (actor.role === "SUPER_ADMIN" ? { latitude: row.planning.latitude, longitude: row.planning.longitude } : coarseCoordinate(row.planning.latitude, row.planning.longitude)) : null; const item = { id: row.assignment.id, employeeId: row.employee.id, employeeName: row.employee.displayName, employeeCoordinate: marker, employeePrecision: marker ? (actor.role === "SUPER_ADMIN" ? "exact" as const : "coarse" as const) : null, worksite: { id: row.location.id, name: row.location.name, coordinate: row.location.latitude == null || row.location.longitude == null ? null : { latitude: row.location.latitude, longitude: row.location.longitude } }, client: { id: row.client.id, name: row.client.companyName }, project: { id: row.project.id, name: row.project.name }, unavailable: unavailable.has(row.employee.id), skills: employeeSkills, coverageGap: gap, label: `${row.employee.displayName} · ${row.project.name} · ${row.location.name}` }; if ((query.employeeId && item.employeeId !== query.employeeId) || (query.skillId && !item.skills.some((x) => x.id === query.skillId)) || (query.clientId && item.client.id !== query.clientId) || (query.projectId && item.project.id !== query.projectId) || (query.locationId && item.worksite.id !== query.locationId) || (query.unavailable && !item.unavailable) || (query.coverageGap && !item.coverageGap)) continue; result.push(item); }
    return { selectedDate: query.date, invalidFilter: false, role: actor.role, assignments: result, filterOptions: options, lastPublishedAt: result.reduce<string | null>((latest, row) => { const source = allowed.find((candidate) => candidate.assignment.id === row.id)?.period.publishedAt?.toISOString() ?? null; return source && (!latest || source > latest) ? source : latest; }, null), noCoordinateCount: result.filter((x) => !x.employeeCoordinate).length };
  }
}
export const planningMapService = new PlanningMapService();
