"use client";

import { useActionState } from "react";
import {
  addContactAction, addEmployeeRelationAction, addNoteAction, addRequirementAction, archiveNoteAction, archiveSupportingAction, createClientAction, createLocationAction, createProjectAction,
  grantOperationalScopeAction, linkProjectLocationAction, revokeOperationalScopeAction, setClientLifecycleAction, setLocationLifecycleAction, unlinkProjectLocationAction, updateClientAction, updateLocationAction,
  updateNoteAction, updateProjectAction, type OperationalAction, type OperationalActionState,
} from "@/modules/operations/actions";

const initial: OperationalActionState = {};
type EmployeeOption = { id: string; displayName: string; role: "SUPER_ADMIN" | "ADMIN" | "EMPLOYEE" };
type SkillOption = { id: string; name: string };
type Target = { type: "CLIENT" | "PROJECT" | "LOCATION"; id: string };
function Feedback({ state }: { state: OperationalActionState }) { return state.error ? <p className="operation-error" role="alert">{state.error}</p> : state.success ? <p className="operation-success" role="status">{state.success}</p> : null; }
function ManagedForm({ action, title, children, submit = "Save", danger = false, compact = false }: { action: OperationalAction; title: string; children: React.ReactNode; submit?: string; danger?: boolean; compact?: boolean }) {
  const [state, formAction, pending] = useActionState(action, initial);
  return <form action={formAction} className={`operation-form ${compact ? "compact" : ""}`} aria-label={title}><h3>{title}</h3>{children}<Feedback state={state} /><button className={`button ${danger ? "danger" : "primary"}`} disabled={pending} type="submit" onClick={danger ? (event) => { if (!window.confirm(`${submit}? This preserves history and does not hard-delete data.`)) event.preventDefault(); } : undefined}>{pending ? "Saving…" : submit}</button></form>;
}
function TargetFields({ target }: { target: Target }) { return <><input type="hidden" name="targetType" value={target.type} /><input type="hidden" name="targetId" value={target.id} /></>; }
function EmployeeSelect({ employees, name, label, value = "", adminsOnly = false }: { employees: EmployeeOption[]; name: string; label: string; value?: string; adminsOnly?: boolean }) { const options = adminsOnly ? employees.filter((employee) => employee.role === "ADMIN") : employees; return <label>{label}<select name={name} defaultValue={value}><option value="">None</option>{options.map((employee) => <option key={employee.id} value={employee.id}>{employee.displayName} · {employee.role.replace("_", " ")}</option>)}</select></label>; }

export function ClientCreateForm({ employees }: { employees: EmployeeOption[] }) { return <ManagedForm action={createClientAction} title="Create Client" submit="Create Client"><p>Only Super Admin can establish a new authorization root.</p><label>Company name<input name="companyName" maxLength={160} required /></label><EmployeeSelect employees={employees} name="accountManagerUserId" label="Account Manager · coordinator only" /><label>Service summary<textarea name="serviceSummary" maxLength={2000} rows={3} /></label><div className="operation-form-grid"><label>Service start<input type="date" name="serviceStartDate" /></label><label>Service end<input type="date" name="serviceEndDate" /></label></div></ManagedForm>; }
export function ClientEditForm({ client, employees }: { client: { id: string; companyName: string; accountManagerUserId: string | null; serviceSummary: string | null; serviceStartDate: string | null; serviceEndDate: string | null; version: number; status: "ACTIVE" | "ARCHIVED" }; employees: EmployeeOption[] }) {
  return <><ManagedForm action={updateClientAction} title="Client details"><input type="hidden" name="clientId" value={client.id} /><input type="hidden" name="expectedVersion" value={client.version} /><label>Company name<input name="companyName" defaultValue={client.companyName} maxLength={160} required /></label><EmployeeSelect employees={employees} name="accountManagerUserId" label="Account Manager · coordinator only" value={client.accountManagerUserId ?? ""} /><label>Service summary<textarea name="serviceSummary" defaultValue={client.serviceSummary ?? ""} maxLength={2000} rows={3} /></label><div className="operation-form-grid"><label>Service start<input type="date" name="serviceStartDate" defaultValue={client.serviceStartDate ?? ""} /></label><label>Service end<input type="date" name="serviceEndDate" defaultValue={client.serviceEndDate ?? ""} /></label></div></ManagedForm><ManagedForm action={setClientLifecycleAction} title="Client lifecycle" submit={client.status === "ACTIVE" ? "Archive Client" : "Reactivate Client"} danger><input type="hidden" name="clientId" value={client.id} /><input type="hidden" name="expectedVersion" value={client.version} /><input type="hidden" name="archived" value={String(client.status === "ACTIVE")} /><p>Archiving is blocked while any Project is not Completed or Archived.</p></ManagedForm></>;
}

export function ProjectCreateForm({ clientId, employees }: { clientId: string; employees: EmployeeOption[] }) { return <ManagedForm action={createProjectAction} title="Create Project under this Client" submit="Create Project"><input type="hidden" name="clientId" value={clientId} /><label>Project name<input name="name" maxLength={160} required /></label><label>Status<select name="status" defaultValue="PLANNED"><option>PLANNED</option><option>ACTIVE</option><option>ON_HOLD</option><option>COMPLETED</option><option>ARCHIVED</option></select></label><EmployeeSelect employees={employees} adminsOnly name="responsibleAdminUserId" label="Responsible Admin · coordinator only" /><div className="operation-form-grid"><label>Start date<input type="date" name="startDate" /></label><label>End date<input type="date" name="endDate" /></label></div></ManagedForm>; }
export function ProjectEditForm({ project, employees }: { project: { id: string; name: string; status: "PLANNED" | "ACTIVE" | "ON_HOLD" | "COMPLETED" | "ARCHIVED"; responsibleAdminUserId: string | null; startDate: string | null; endDate: string | null; version: number }; employees: EmployeeOption[] }) { return <ManagedForm action={updateProjectAction} title="Project details"><input type="hidden" name="projectId" value={project.id} /><input type="hidden" name="expectedVersion" value={project.version} /><label>Project name<input name="name" defaultValue={project.name} maxLength={160} required /></label><label>Status<select name="status" defaultValue={project.status}><option>PLANNED</option><option>ACTIVE</option><option>ON_HOLD</option><option>COMPLETED</option><option>ARCHIVED</option></select></label><EmployeeSelect employees={employees} adminsOnly name="responsibleAdminUserId" label="Responsible Admin · coordinator only" value={project.responsibleAdminUserId ?? ""} /><div className="operation-form-grid"><label>Start date<input type="date" name="startDate" defaultValue={project.startDate ?? ""} /></label><label>End date<input type="date" name="endDate" defaultValue={project.endDate ?? ""} /></label></div></ManagedForm>; }

export function LocationCreateForm({ clientId }: { clientId: string }) { return <ManagedForm action={createLocationAction} title="Create a separate Location" submit="Create Location"><input type="hidden" name="clientId" value={clientId} /><p>Review same-client matches first. Matching text never merges records or links a Project automatically.</p><label>Location name<input name="name" maxLength={160} required /></label><label>Full operational address<textarea name="address" maxLength={500} rows={2} required /></label><div className="operation-form-grid"><label>Latitude · optional pair<input name="latitude" type="number" min="-90" max="90" step="any" /></label><label>Longitude · optional pair<input name="longitude" type="number" min="-180" max="180" step="any" /></label></div><label>Site hours · flexible text<textarea name="siteHours" maxLength={1000} rows={2} /></label><label>Access instructions<textarea name="accessInstructions" maxLength={2000} rows={2} /></label><label>Visit requirements<textarea name="visitRequirements" maxLength={2000} rows={2} /></label></ManagedForm>; }
export function LocationEditForm({ location }: { location: { id: string; name: string; address: string; status: "ACTIVE" | "ARCHIVED"; latitude: number | null; longitude: number | null; siteHours: string | null; accessInstructions: string | null; visitRequirements: string | null; version: number } }) { return <><ManagedForm action={updateLocationAction} title="Location details"><input type="hidden" name="locationId" value={location.id} /><input type="hidden" name="expectedVersion" value={location.version} /><label>Location name<input name="name" defaultValue={location.name} maxLength={160} required /></label><label>Full operational address<textarea name="address" defaultValue={location.address} maxLength={500} rows={2} required /></label><div className="operation-form-grid"><label>Latitude<input name="latitude" type="number" min="-90" max="90" step="any" defaultValue={location.latitude ?? ""} /></label><label>Longitude<input name="longitude" type="number" min="-180" max="180" step="any" defaultValue={location.longitude ?? ""} /></label></div><label>Site hours<textarea name="siteHours" defaultValue={location.siteHours ?? ""} maxLength={1000} rows={2} /></label><label>Access instructions<textarea name="accessInstructions" defaultValue={location.accessInstructions ?? ""} maxLength={2000} rows={2} /></label><label>Visit requirements<textarea name="visitRequirements" defaultValue={location.visitRequirements ?? ""} maxLength={2000} rows={2} /></label></ManagedForm><ManagedForm action={setLocationLifecycleAction} title="Location lifecycle" submit={location.status === "ACTIVE" ? "Archive Location" : "Reactivate Location"} danger><input type="hidden" name="locationId" value={location.id} /><input type="hidden" name="expectedVersion" value={location.version} /><input type="hidden" name="archived" value={String(location.status === "ACTIVE")} /><p>Archiving retains existing Project links and history but blocks new active details.</p></ManagedForm></>;
}

export function ProjectLocationPanel({ projectId, candidates, linked }: { projectId: string; candidates: { location: { id: string; name: string; address: string } }[]; linked: { relation: { version: number }; location: { id: string; name: string; address: string } }[] }) {
  return <section className="operation-panel"><h2>Project Locations</h2><p>Reuse is deliberate and same-client only. This relationship is operational structure, not a schedule assignment.</p><ManagedForm action={linkProjectLocationAction} title="Link an existing same-client Location" submit="Link Location" compact><input type="hidden" name="projectId" value={projectId} /><label>Location<select name="locationId" required><option value="">Choose a likely match</option>{candidates.map(({ location }) => <option key={location.id} value={location.id}>{location.name} — {location.address}</option>)}</select></label></ManagedForm>{linked.length ? <ul className="operation-list">{linked.map(({ relation, location }) => <li key={location.id}><div><strong>{location.name}</strong><span>{location.address}</span></div><ManagedForm action={unlinkProjectLocationAction} title={`Archive link to ${location.name}`} submit="Archive link" danger compact><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="locationId" value={location.id} /><input type="hidden" name="expectedVersion" value={relation.version} /></ManagedForm></li>)}</ul> : <p className="operation-empty">No Location is linked yet.</p>}</section>;
}

type SupportingDetails = {
  contacts: { id: string; name: string; roleTitle: string | null; workPhone: string | null; workEmail: string | null; version: number }[];
  requirements: { requirement: { id: string; requiredEmployeeCount: number; note: string | null; version: number }; skillName: string }[];
  employees: { relation: { id: string; employeeUserId: string; version: number }; displayName: string }[];
  notes: { note: { id: string; authorUserId: string; content: string; version: number }; authorName: string }[];
};
export function SupportingDetailsPanel({ target, details, employees, skills, actorId, isSuperAdmin }: { target: Target; details: SupportingDetails; employees: EmployeeOption[]; skills: SkillOption[]; actorId: string; isSuperAdmin: boolean }) {
  return <section className="operation-supporting"><h2>Operational details</h2><p>Contacts, requirements, employee associations, and notes remain separate. None creates a schedule assignment or permission.</p><div className="operation-support-grid">
    <div className="operation-panel"><ManagedForm action={addContactAction} title="Add operational contact" submit="Add contact" compact><TargetFields target={target} /><label>Name<input name="name" maxLength={160} required /></label><label>Role/title<input name="roleTitle" maxLength={160} /></label><label>Work phone<input name="workPhone" maxLength={40} /></label><label>Work email<input name="workEmail" type="email" maxLength={254} /></label></ManagedForm><ul className="operation-list">{details.contacts.map((contact) => <li key={contact.id}><div><strong>{contact.name}</strong><span>{[contact.roleTitle, contact.workPhone, contact.workEmail].filter(Boolean).join(" · ") || "No optional contact detail"}</span></div><ArchiveSupporting kind="CONTACT" id={contact.id} version={contact.version} /></li>)}</ul></div>
    <div className="operation-panel"><ManagedForm action={addRequirementAction} title="Add operational required skill" submit="Add required skill" compact><TargetFields target={target} /><label>Required skill<select name="requiredSkillId" required><option value="">Choose active skill</option>{skills.map((skill) => <option key={skill.id} value={skill.id}>{skill.name}</option>)}</select></label><label>Recorded staffing count · preserved operational data<input name="requiredEmployeeCount" type="number" min="1" max="1000" defaultValue="1" required /></label><label>Shared operational note<textarea name="note" maxLength={1000} rows={2} /></label><p>The recorded skill is an inherited Phase 6 requirement source. The count is not coverage logic and does not affect warnings.</p></ManagedForm><ul className="operation-list">{details.requirements.map(({ requirement, skillName }) => <li key={requirement.id}><div><strong>{skillName}</strong><span>{requirement.note ?? "No note"} · recorded count {requirement.requiredEmployeeCount} (not used for coverage)</span></div><ArchiveSupporting kind="REQUIREMENT" id={requirement.id} version={requirement.version} /></li>)}</ul></div>
    <div className="operation-panel"><ManagedForm action={addEmployeeRelationAction} title="Add operational employee association" submit="Add association" compact><TargetFields target={target} /><label>Active employee<select name="employeeUserId" required><option value="">Choose employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.displayName}</option>)}</select></label><p>This grants no access and creates no fieldwork or schedule assignment.</p></ManagedForm><ul className="operation-list">{details.employees.map(({ relation, displayName }) => <li key={relation.id}><div><strong>{displayName}</strong><span>Operational association only</span></div><ArchiveSupporting kind="EMPLOYEE_RELATION" id={relation.id} version={relation.version} /></li>)}</ul></div>
    <div className="operation-panel"><ManagedForm action={addNoteAction} title="Add shared operational note" submit="Add note" compact><TargetFields target={target} /><label>Note<textarea name="content" maxLength={5000} rows={3} required /></label></ManagedForm><ul className="operation-notes">{details.notes.map(({ note, authorName }) => <li key={note.id}><strong>{authorName}</strong><p>{note.content}</p>{note.authorUserId === actorId ? <ManagedForm action={updateNoteAction} title="Edit your note" compact><input type="hidden" name="noteId" value={note.id} /><input type="hidden" name="expectedVersion" value={note.version} /><label>Note<textarea name="content" defaultValue={note.content} maxLength={5000} rows={2} required /></label></ManagedForm> : null}{isSuperAdmin ? <ManagedForm action={archiveNoteAction} title="Archive shared note" submit="Archive note" danger compact><input type="hidden" name="noteId" value={note.id} /><input type="hidden" name="expectedVersion" value={note.version} /><label>Required archive reason<input name="reason" minLength={3} maxLength={500} required /></label></ManagedForm> : null}</li>)}</ul></div>
  </div></section>;
}
function ArchiveSupporting({ kind, id, version }: { kind: "CONTACT" | "REQUIREMENT" | "EMPLOYEE_RELATION"; id: string; version: number }) { return <ManagedForm action={archiveSupportingAction} title={`Archive ${kind.toLowerCase().replace("_", " ")}`} submit="Archive" danger compact><input type="hidden" name="kind" value={kind} /><input type="hidden" name="recordId" value={id} /><input type="hidden" name="expectedVersion" value={version} /></ManagedForm>; }

export function ScopeManagementPanel({ target, employees, grants }: { target: Target; employees: EmployeeOption[]; grants: { grant: { id: string; userId: string; scopeType: string; scopeReference: string; active: boolean; version: number }; user: { displayName: string } }[] }) {
  const relevant = grants.filter(({ grant }) => grant.scopeType === target.type && grant.scopeReference === target.id);
  return <section className="operation-panel"><h2>Explicit operational scope</h2><p>Only Super Admin can grant or revoke. Account Manager, Responsible Admin, Team, designation, manager, and employee relationships never grant access.</p><ManagedForm action={grantOperationalScopeAction} title={`Grant ${target.type} scope`} submit="Grant scope" compact><TargetFields target={target} /><EmployeeSelect employees={employees} adminsOnly name="adminUserId" label="Active Admin" /></ManagedForm><ul className="operation-list">{relevant.filter(({ grant }) => grant.active).map(({ grant, user }) => <li key={grant.id}><div><strong>{user.displayName}</strong><span>{grant.scopeType} · version {grant.version}</span></div><ManagedForm action={revokeOperationalScopeAction} title={`Revoke ${grant.scopeType} scope from ${user.displayName}`} submit="Revoke scope" danger compact><input type="hidden" name="grantId" value={grant.id} /><input type="hidden" name="expectedVersion" value={grant.version} /></ManagedForm></li>)}</ul></section>;
}
