"use client";
import { useActionState } from "react";
import { TaskDialog } from "@/shared/components/task-dialog";
import { addAssignmentSkillRequirementAction, addEmployeeSkillAction, archiveAssignmentSkillRequirementAction, archiveEmployeeSkillAction, createSkillAction, renameSkillAction, setSkillActiveAction, type CapabilityAction, type CapabilityActionState } from "@/modules/capabilities/actions";
const initial: CapabilityActionState = {}; const Feedback = ({ state }: { state: CapabilityActionState }) => state.error ? <p className="operation-error" role="alert">{state.error}</p> : state.success ? <p className="operation-success" role="status">{state.success}</p> : null;
function Form({ action, title, children, submit }: { action: CapabilityAction; title: string; children: React.ReactNode; submit: string }) { const [state, formAction, pending] = useActionState(action, initial); return <form className="operation-form compact" action={formAction} aria-label={title}>{children}<Feedback state={state} /><button className="button primary" disabled={pending}>{pending ? "Saving…" : submit}</button></form>; }
export function SkillCatalogue({ skills }: { skills: { id: string; name: string; active: boolean; version: number }[] }) {
  return <section className="operation-panel skill-catalogue">
    <header className="secondary-panel-heading"><div><h3>Skill list</h3><p>{skills.filter((skill) => skill.active).length} active skills · available to record on people</p></div>
      <TaskDialog triggerLabel="Add skill" title="Create skill" description="Add a clear, reusable skill to the team catalogue."><Form action={createSkillAction} title="Create skill" submit="Create skill"><label>Skill name<input name="name" maxLength={160} required /></label></Form></TaskDialog>
    </header>
    <ul className="operation-list">{skills.map((skill) => <li key={skill.id}>
      <div><strong>{skill.name}</strong><span>{skill.active ? "Active" : "Archived"}</span></div>
      <div className="skill-catalogue-actions"><TaskDialog triggerLabel="Rename" title={`Rename ${skill.name}`} triggerClassName="button"><Form action={renameSkillAction} title={`Rename ${skill.name}`} submit="Rename"><input type="hidden" name="skillId" value={skill.id} /><input type="hidden" name="expectedVersion" value={skill.version} /><label>New name<input name="name" defaultValue={skill.name} maxLength={160} required /></label></Form></TaskDialog>
      <Form action={setSkillActiveAction} title={`${skill.active ? "Archive" : "Reactivate"} ${skill.name}`} submit={skill.active ? "Archive" : "Reactivate"}><input type="hidden" name="skillId" value={skill.id} /><input type="hidden" name="expectedVersion" value={skill.version} /><input type="hidden" name="active" value={String(!skill.active)} /></Form></div>
    </li>)}</ul>
    {skills.length ? null : <p className="operation-empty">Add the first skill to start recording team capabilities.</p>}
    <p className="operation-help">Archiving keeps existing records and prevents new use. Only Super Admin can manage this catalogue.</p>
  </section>;
}
export function EmployeeSkillManager({ employees, skills, selectedEmployeeId, records }: { employees: { id: string; displayName: string }[]; skills: { id: string; name: string }[]; selectedEmployeeId?: string; records: { association: { id: string; version: number }; skill: { name: string } }[] }) {
  const person = employees.find((employee) => employee.id === selectedEmployeeId);
  if (!person) return <section className="operation-panel"><h3>Choose a person to start</h3><p>Select someone above to see or add their recorded skills.</p></section>;
  return <section className="operation-panel"><header className="secondary-panel-heading"><div><h3>{person.displayName}’s recorded skills</h3><p>{records.length} skill{records.length === 1 ? "" : "s"} recorded. Certifications and supporting documents are in their profile.</p></div>
    <TaskDialog triggerLabel={`Record a skill for ${person.displayName}`} triggerText="Record skill" title={`Record a skill · ${person.displayName}`}>
      <Form action={addEmployeeSkillAction} title="Record employee skill" submit="Record skill"><input type="hidden" name="employeeUserId" value={person.id} /><label>Skill<select name="skillId" required><option value="">Choose skill</option>{skills.map((skill) => <option key={skill.id} value={skill.id}>{skill.name}</option>)}</select></label></Form>
    </TaskDialog></header>
    {records.length ? <ul className="operation-list">{records.map(({ association, skill }) => <li key={association.id}><div><strong>{skill.name}</strong><span>Recorded skill</span></div><Form action={archiveEmployeeSkillAction} title={`Archive ${skill.name}`} submit="Archive"><input type="hidden" name="employeeSkillId" value={association.id} /><input type="hidden" name="expectedVersion" value={association.version} /></Form></li>)}</ul> : <p className="operation-empty">No skills recorded yet. Record a skill to add it to this person’s profile.</p>}
  </section>;
}
export function AssignmentSkillRequirementPanel({ assignmentId, canManage, skills, requirements }: { assignmentId: string; canManage: boolean; skills: { id: string; name: string }[]; requirements: { requirement: { id: string; version: number }; skillName: string }[] }) { return <section className="schedule-requirements"><h4>Assignment-specific skills</h4><p>These add qualification requirements to Client, Project, and Location sources. They can surface a non-blocking recorded-skill gap; they do not add a staffing count or make an eligibility judgment.</p>{canManage ? <Form action={addAssignmentSkillRequirementAction} title="Add assignment skill requirement" submit="Add skill"><input type="hidden" name="assignmentId" value={assignmentId} /><label>Required skill<select name="skillId" required><option value="">Choose active skill</option>{skills.map((skill) => <option key={skill.id} value={skill.id}>{skill.name}</option>)}</select></label></Form> : null}<ul className="operation-list">{requirements.map(({ requirement, skillName }) => <li key={requirement.id}><div><strong>{skillName}</strong><span>Assignment source</span></div>{canManage ? <Form action={archiveAssignmentSkillRequirementAction} title={`Archive ${skillName} requirement`} submit="Archive"><input type="hidden" name="requirementId" value={requirement.id} /><input type="hidden" name="expectedVersion" value={requirement.version} /></Form> : null}</li>)}</ul></section>; }
