import "server-only";
import { and, asc, eq, inArray, isNull, sql } from "drizzle-orm";
import { db } from "@/db/client";
import { adminScopeGrants, assignmentSkillRequirements, clients, employeeProfiles, employeeSkills, locations, projects, scheduleAssignments, schedulePeriods, skills, staffingRequirements, users } from "@/db/schema";

export type CapabilityTransaction = Parameters<Parameters<typeof db.transaction>[0]>[0];
export type CapabilityExecutor = typeof db | CapabilityTransaction;

export const capabilityRepository = {
  activeSkills(executor: CapabilityExecutor) { return executor.select({ id: skills.id, name: skills.name, version: skills.version }).from(skills).where(eq(skills.active, true)).orderBy(asc(skills.name)); },
  allSkills(executor: CapabilityExecutor) { return executor.select().from(skills).orderBy(asc(skills.name)); },
  skill(executor: CapabilityExecutor, id: string) { return executor.select().from(skills).where(eq(skills.id, id)).limit(1).then(([row]) => row ?? null); },
  assignment(executor: CapabilityExecutor, id: string) { return executor.select({ assignment: scheduleAssignments, period: schedulePeriods, client: clients, project: projects, location: locations, employeeName: users.displayName, employeeTeam: employeeProfiles.team }).from(scheduleAssignments).innerJoin(schedulePeriods, eq(schedulePeriods.id, scheduleAssignments.schedulePeriodId)).innerJoin(clients, eq(clients.id, schedulePeriods.clientId)).innerJoin(projects, eq(projects.id, scheduleAssignments.projectId)).innerJoin(locations, eq(locations.id, scheduleAssignments.locationId)).innerJoin(users, eq(users.id, scheduleAssignments.employeeUserId)).innerJoin(employeeProfiles, eq(employeeProfiles.userId, scheduleAssignments.employeeUserId)).where(eq(scheduleAssignments.id, id)).limit(1).then(([row]) => row ?? null); },
  lockAssignment(tx: CapabilityTransaction, id: string) { return tx.execute(sql`select id from schedule_assignments where id = ${id} for update`); },
  assignmentRequirement(executor: CapabilityExecutor, id: string) { return executor.select().from(assignmentSkillRequirements).where(eq(assignmentSkillRequirements.id, id)).limit(1).then(([row]) => row ?? null); },
  assignmentRequirements(executor: CapabilityExecutor, assignmentId: string) { return executor.select({ requirement: assignmentSkillRequirements, skillName: skills.name }).from(assignmentSkillRequirements).innerJoin(skills, eq(skills.id, assignmentSkillRequirements.skillId)).where(and(eq(assignmentSkillRequirements.scheduleAssignmentId, assignmentId), isNull(assignmentSkillRequirements.archivedAt))).orderBy(asc(skills.name)); },
  createAssignmentRequirement(tx: CapabilityTransaction, assignmentId: string, skillId: string) { return tx.insert(assignmentSkillRequirements).values({ scheduleAssignmentId: assignmentId, skillId }).returning().then(([row]) => row!); },
  archiveAssignmentRequirement(tx: CapabilityTransaction, id: string, expectedVersion: number) { return tx.update(assignmentSkillRequirements).set({ archivedAt: new Date(), version: sql`${assignmentSkillRequirements.version} + 1`, updatedAt: new Date() }).where(and(eq(assignmentSkillRequirements.id, id), eq(assignmentSkillRequirements.version, expectedVersion), isNull(assignmentSkillRequirements.archivedAt))).returning().then(([row]) => row ?? null); },
  activeRequirements(executor: CapabilityExecutor, assignment: { schedulePeriodId: string; projectId: string; locationId: string }) { return executor.select({ skillId: staffingRequirements.requiredSkillId, skillName: skills.name, clientId: staffingRequirements.clientId, projectId: staffingRequirements.projectId, locationId: staffingRequirements.locationId }).from(staffingRequirements).innerJoin(schedulePeriods, eq(schedulePeriods.id, assignment.schedulePeriodId)).innerJoin(skills, eq(skills.id, staffingRequirements.requiredSkillId)).where(and(isNull(staffingRequirements.archivedAt), sql`(${staffingRequirements.clientId} = ${schedulePeriods.clientId} or ${staffingRequirements.projectId} = ${assignment.projectId} or ${staffingRequirements.locationId} = ${assignment.locationId})`)); },
  employeeSkillIds(executor: CapabilityExecutor, employeeUserId: string) { return executor.select({ skillId: employeeSkills.skillId }).from(employeeSkills).where(and(eq(employeeSkills.employeeUserId, employeeUserId), isNull(employeeSkills.archivedAt))); },
  activeGrants(executor: CapabilityExecutor, userId: string) { return executor.select().from(adminScopeGrants).where(and(eq(adminScopeGrants.userId, userId), eq(adminScopeGrants.active, true))); },
  candidates(executor: CapabilityExecutor, skillId: string, teams?: string[]) { return executor.select({ id: users.id, displayName: users.displayName, team: employeeProfiles.team, skillName: skills.name }).from(employeeSkills).innerJoin(users, eq(users.id, employeeSkills.employeeUserId)).innerJoin(employeeProfiles, eq(employeeProfiles.userId, users.id)).innerJoin(skills, eq(skills.id, employeeSkills.skillId)).where(and(eq(employeeSkills.skillId, skillId), isNull(employeeSkills.archivedAt), eq(users.active, true), eq(users.role, "EMPLOYEE"), teams === undefined ? undefined : teams.length ? inArray(employeeProfiles.team, teams) : sql`false`)).orderBy(asc(users.displayName)); },
  periodAssignmentIds(executor: CapabilityExecutor, periodId: string) { return executor.select({ id: scheduleAssignments.id }).from(scheduleAssignments).where(eq(scheduleAssignments.schedulePeriodId, periodId)); },
};
