"use server";
import { revalidatePath } from "next/cache";
import { getCurrentActor } from "@/modules/auth/session-service";
import { CapabilityDomainError } from "@/modules/capabilities/domain-error";
import { capabilityService } from "@/modules/capabilities/service";
import { EmployeeDomainError } from "@/modules/employees/domain-error";
import { employeeCatalogueService, employeeSkillService } from "@/modules/employees/employee-services";

export type CapabilityActionState = { error?: string; success?: string }; export type CapabilityAction = (state: CapabilityActionState, data: FormData) => Promise<CapabilityActionState>;
const text = (data: FormData, key: string) => typeof data.get(key) === "string" ? String(data.get(key)).trim() : ""; const number = (data: FormData, key: string) => Number(text(data, key)); const only = (data: FormData, keys: string[]) => [...data.keys()].every((key) => keys.includes(key) || key.startsWith("$ACTION_"));
async function actor() { const current = await getCurrentActor(); if (!current) throw new CapabilityDomainError("FORBIDDEN", "Your session expired. Sign in again."); return current; }
function message(error: unknown) { return error instanceof CapabilityDomainError || error instanceof EmployeeDomainError ? error.message : "The skill change could not be saved. Reload and try again."; }
async function run(operation: () => Promise<unknown>, success: string) { try { await operation(); for (const path of ["/skills", "/schedule", "/clients", "/projects", "/locations"]) revalidatePath(path, "layout"); return { success }; } catch (error) { return { error: message(error) }; } }
export const createSkillAction: CapabilityAction = async (_state, data) => !only(data, ["name"]) ? { error: "The skill form contained unsupported fields." } : run(async () => employeeCatalogueService.createSkill(await actor(), { name: text(data, "name") }), "Skill created.");
export const renameSkillAction: CapabilityAction = async (_state, data) => !only(data, ["skillId", "name", "expectedVersion"]) ? { error: "The skill form contained unsupported fields." } : run(async () => employeeCatalogueService.updateSkill(await actor(), text(data, "skillId"), { name: text(data, "name"), expectedVersion: number(data, "expectedVersion") }), "Skill renamed.");
export const setSkillActiveAction: CapabilityAction = async (_state, data) => !only(data, ["skillId", "expectedVersion", "active"]) ? { error: "The skill form contained unsupported fields." } : run(async () => employeeCatalogueService.setSkillActive(await actor(), text(data, "skillId"), number(data, "expectedVersion"), text(data, "active") === "true"), text(data, "active") === "true" ? "Skill reactivated." : "Skill archived; existing history is retained.");
export const addEmployeeSkillAction: CapabilityAction = async (_state, data) => !only(data, ["employeeUserId", "skillId"]) ? { error: "The employee-skill form contained unsupported fields." } : run(async () => employeeSkillService.add(await actor(), { employeeUserId: text(data, "employeeUserId"), skillId: text(data, "skillId") }), "Recorded skill added to the Employee profile.");
export const archiveEmployeeSkillAction: CapabilityAction = async (_state, data) => !only(data, ["employeeSkillId", "expectedVersion"]) ? { error: "The employee-skill form contained unsupported fields." } : run(async () => employeeSkillService.setArchived(await actor(), text(data, "employeeSkillId"), number(data, "expectedVersion"), true), "Employee skill association archived; history is retained.");
export const addAssignmentSkillRequirementAction: CapabilityAction = async (_state, data) => !only(data, ["assignmentId", "skillId"]) ? { error: "The assignment requirement form contained unsupported fields." } : run(async () => capabilityService.addAssignmentRequirement(await actor(), { assignmentId: text(data, "assignmentId"), skillId: text(data, "skillId") }), "Assignment skill requirement added.");
export const archiveAssignmentSkillRequirementAction: CapabilityAction = async (_state, data) => !only(data, ["requirementId", "expectedVersion"]) ? { error: "The assignment requirement form contained unsupported fields." } : run(async () => capabilityService.archiveAssignmentRequirement(await actor(), { requirementId: text(data, "requirementId"), expectedVersion: number(data, "expectedVersion") }), "Assignment skill requirement archived.");
