"use server";

import { revalidatePath } from "next/cache";
import { getCurrentActor } from "@/modules/auth/session-service";
import { SchedulingDomainError } from "@/modules/scheduling/domain-error";
import { schedulingService } from "@/modules/scheduling/service";

export type SchedulingActionState = { error?: string; success?: string };
export type SchedulingAction = (state: SchedulingActionState, formData: FormData) => Promise<SchedulingActionState>;
const text = (data: FormData, key: string) => { const value = data.get(key); return typeof value === "string" ? value.trim() : ""; };
const number = (data: FormData, key: string) => Number(text(data, key));
const allowed = (data: FormData, keys: string[]) => [...data.keys()].every((key) => keys.includes(key) || key.startsWith("$ACTION_"));
async function actor() { const current = await getCurrentActor(); if (!current) throw new SchedulingDomainError("FORBIDDEN", "Your session expired. Sign in again."); return current; }
function message(error: unknown) { return error instanceof SchedulingDomainError ? error.message : "The schedule change could not be saved. Reload and try again."; }
async function run(operation: () => Promise<unknown>, success: string) { try { await operation(); revalidatePath("/schedule"); return { success }; } catch (error) { return { error: message(error) }; } }

export const createSchedulePeriodAction: SchedulingAction = async (_state, data) => { if (!allowed(data, ["clientId", "month"])) return { error: "The schedule form contained unsupported fields." }; return run(async () => schedulingService.createPeriod(await actor(), { clientId: text(data, "clientId"), month: text(data, "month") }), "Draft schedule created."); };
export const addScheduleAssignmentAction: SchedulingAction = async (_state, data) => { if (!allowed(data, ["periodId", "expectedPeriodVersion", "employeeUserId", "projectId", "locationId", "assignmentDate", "startTime", "endTime", "sharedInstruction"])) return { error: "The assignment form contained unsupported fields." }; return run(async () => schedulingService.addAssignment(await actor(), { periodId: text(data, "periodId"), expectedPeriodVersion: number(data, "expectedPeriodVersion"), employeeUserId: text(data, "employeeUserId"), projectId: text(data, "projectId"), locationId: text(data, "locationId"), assignmentDate: text(data, "assignmentDate"), startTime: text(data, "startTime"), endTime: text(data, "endTime"), sharedInstruction: text(data, "sharedInstruction") }), "Assignment added to the Draft."); };
export const updateScheduleAssignmentAction: SchedulingAction = async (_state, data) => { if (!allowed(data, ["assignmentId", "periodId", "expectedVersion", "expectedPeriodVersion", "employeeUserId", "projectId", "locationId", "assignmentDate", "startTime", "endTime", "sharedInstruction"])) return { error: "The assignment form contained unsupported fields." }; return run(async () => schedulingService.updateAssignment(await actor(), { assignmentId: text(data, "assignmentId"), periodId: text(data, "periodId"), expectedVersion: number(data, "expectedVersion"), expectedPeriodVersion: number(data, "expectedPeriodVersion"), employeeUserId: text(data, "employeeUserId"), projectId: text(data, "projectId"), locationId: text(data, "locationId"), assignmentDate: text(data, "assignmentDate"), startTime: text(data, "startTime"), endTime: text(data, "endTime"), sharedInstruction: text(data, "sharedInstruction") }), "Assignment updated."); };
export const removeScheduleAssignmentAction: SchedulingAction = async (_state, data) => { if (!allowed(data, ["assignmentId", "periodId", "expectedVersion", "expectedPeriodVersion"])) return { error: "The assignment form contained unsupported fields." }; return run(async () => schedulingService.removeAssignment(await actor(), { assignmentId: text(data, "assignmentId"), periodId: text(data, "periodId"), expectedVersion: number(data, "expectedVersion"), expectedPeriodVersion: number(data, "expectedPeriodVersion") }), "Draft assignment removed."); };
export const proposeScheduleAction: SchedulingAction = async (_state, data) => { if (!allowed(data, ["periodId", "expectedVersion"])) return { error: "The lifecycle form contained unsupported fields." }; return run(async () => schedulingService.propose(await actor(), { periodId: text(data, "periodId"), expectedVersion: number(data, "expectedVersion") }), "Schedule proposed for Super Admin review."); };
export const returnScheduleToDraftAction: SchedulingAction = async (_state, data) => { if (!allowed(data, ["periodId", "expectedVersion", "reason"])) return { error: "The lifecycle form contained unsupported fields." }; return run(async () => schedulingService.returnToDraft(await actor(), { periodId: text(data, "periodId"), expectedVersion: number(data, "expectedVersion"), reason: text(data, "reason") }), "Schedule returned to Draft."); };
export const publishScheduleAction: SchedulingAction = async (_state, data) => { if (!allowed(data, ["periodId", "expectedVersion"])) return { error: "The lifecycle form contained unsupported fields." }; return run(async () => schedulingService.publish(await actor(), { periodId: text(data, "periodId"), expectedVersion: number(data, "expectedVersion") }), "Schedule published. Affected employees can now see their own assignments."); };
export const createScheduleRevisionAction: SchedulingAction = async (_state, data) => { if (!allowed(data, ["periodId", "expectedVersion"])) return { error: "The lifecycle form contained unsupported fields." }; return run(async () => schedulingService.createRevision(await actor(), { periodId: text(data, "periodId"), expectedVersion: number(data, "expectedVersion") }), "Editable Draft revision created from the Published schedule."); };
