"use client";

import { useActionState, useState } from "react";
import Link from "next/link";
import { TaskDialog } from "@/shared/components/task-dialog";
import { announceWorkflowSuccess } from "@/shared/components/workflow-feedback";
import { addScheduleAssignmentAction, createSchedulePeriodAction, createScheduleRevisionAction, proposeScheduleAction, publishScheduleAction, removeScheduleAssignmentAction, returnScheduleToDraftAction, updateScheduleAssignmentAction, type SchedulingAction, type SchedulingActionState } from "@/modules/scheduling/actions";
import { AssignmentSkillRequirementPanel } from "@/modules/capabilities/forms";

const initial: SchedulingActionState = {};
type Employee = { id: string; displayName: string };
type Project = { project: { id: string; name: string } };
type Location = { location: { id: string; name: string } };
type Assignment = { assignment: { id: string; employeeUserId: string; projectId: string; locationId: string; assignmentDate: string; startTime: string; endTime: string; sharedInstruction: string | null; version: number }; employeeName: string; projectName: string; locationName: string; requirements: { requirement: { id: string; version: number }; skillName: string }[] };
type Period = { id: string; clientId: string; planningMonth: string; revisionNumber: number; parentPeriodId: string | null; status: "DRAFT" | "PROPOSED" | "PUBLISHED"; isCurrent: boolean; lastReturnReason: string | null; version: number };
function Feedback({ state }: { state: SchedulingActionState }) { return state.error ? <p className="schedule-error" role="alert">{state.error}</p> : state.success ? <p className="schedule-success" role="status">{state.success}</p> : null; }
function ActionForm({ action, title, children, submit = "Save", danger = false, persistentFeedback = false }: { action: SchedulingAction; title: string; children: React.ReactNode; submit?: string; danger?: boolean; persistentFeedback?: boolean }) { const [state, formAction, pending] = useActionState(async (previous: SchedulingActionState, data: FormData) => { const result = await action(previous, data); if (persistentFeedback) announceWorkflowSuccess(result); return result; }, initial); return <form className="schedule-form" action={formAction} aria-label={title}>{children}<Feedback state={state} /><button className={`button ${danger ? "danger" : "primary"}`} type="submit" disabled={pending}>{pending ? "Saving…" : submit}</button></form>; }

export function CreatePeriodForm({ clients, month }: { clients: { id: string; companyName: string }[]; month: string }) { return <ActionForm action={createSchedulePeriodAction} title="Create a monthly Draft" submit="Create Draft"><label>Client<select name="clientId" required defaultValue=""><option value="">Choose Client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.companyName}</option>)}</select></label><label>Planning month<input name="month" type="month" defaultValue={month} required /></label><p className="schedule-help">One Client-month Draft at a time. Planning timezone: Asia/Dubai.</p></ActionForm>; }

export function LifecyclePanel({ period, clientName, canManage, canPropose, canPublish, warnings }: { period: Period; clientName: string; canManage: boolean; canPropose: boolean; canPublish: boolean; warnings: { assignmentId: string; employeeName: string; assignmentDate: string; missingSkills: { id: string; name: string; sources: ("Client" | "Project" | "Location" | "Assignment")[] }[] }[] }) {
  const steps = ["DRAFT", "PROPOSED", "PUBLISHED"] as const;
  const currentStep = steps.indexOf(period.status);
  return <section className="schedule-panel workflow-lifecycle">
    <div className="schedule-panel-heading"><div><p className="eyebrow">Revision {period.revisionNumber} · {period.planningMonth.slice(0, 7)}</p><h3>{clientName}</h3></div><span className={`schedule-status ${period.status.toLowerCase()}`}>{period.status}</span></div>
    <ol className="workflow-steps" aria-label="Schedule progress">{steps.map((step, index) => <li key={step} aria-current={step === period.status ? "step" : undefined} className={index <= currentStep ? "reached" : ""}><span>{index + 1}</span>{step === "DRAFT" ? "Plan" : step === "PROPOSED" ? "Review" : "Published"}</li>)}</ol>
    <p className="schedule-help">{!canManage && !canPropose && !canPublish ? (period.status === "DRAFT" ? "Super Admin is preparing this schedule. Draft work is not published." : period.status === "PROPOSED" ? "Super Admin is reviewing this schedule. It is not published yet." : period.isCurrent ? "This is the team’s current published schedule." : "This is a historical published schedule.") : period.status === "DRAFT" ? "Add or update assignments, then propose the schedule for review." : period.status === "PROPOSED" ? "Ready for Super Admin review. Return to Draft to make changes, or publish to the team." : period.isCurrent ? "This is the team’s current schedule. Published schedules are locked; create a Draft revision to make changes." : "This is a historical version. Published schedules are locked."} All times: Asia/Dubai.</p>
    {period.lastReturnReason && period.status === "DRAFT" ? <p className="schedule-callout">Returned for changes: {period.lastReturnReason}</p> : null}
    <div className="schedule-actions workflow-lifecycle-actions">
      {canPropose && period.status === "DRAFT" ? <ActionForm persistentFeedback action={proposeScheduleAction} title="Propose this Draft" submit="Propose for review"><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedVersion" value={period.version} /></ActionForm> : null}
      {canPublish && period.status === "PROPOSED" ? <><ActionForm persistentFeedback action={publishScheduleAction} title="Publish Proposed schedule" submit="Publish schedule"><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedVersion" value={period.version} /></ActionForm><TaskDialog triggerLabel="Return to Draft" triggerClassName="button" title="Return schedule for changes"><ActionForm persistentFeedback action={returnScheduleToDraftAction} title="Return Proposed schedule to Draft" submit="Return to Draft"><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedVersion" value={period.version} /><label>Reason for return<textarea name="reason" minLength={3} maxLength={500} required rows={3} /></label></ActionForm></TaskDialog></> : null}
      {canPublish && period.status === "PUBLISHED" && period.isCurrent ? <ActionForm action={createScheduleRevisionAction} title="Create an editable revision" submit="Create Draft revision"><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedVersion" value={period.version} /></ActionForm> : null}
    </div>
    {warnings.length ? <details className="workflow-advisory"><summary>{warnings.length} recorded-skill warning{warnings.length === 1 ? "" : "s"}</summary>{warnings.map((warning) => <p key={warning.assignmentId}>{warning.employeeName} · {warning.assignmentDate}: {warning.missingSkills.map((skill) => `${skill.name} (${skill.sources.join(" + ")})`).join(", ")} is not recorded on this employee’s profile. This warning does not block publication or determine coverage.</p>)}</details> : null}
  </section>;
}

export function AssignmentForm({ period, employees, projects, locationsByProject, assignment }: { period: Period; employees: Employee[]; projects: Project[]; locationsByProject: [string, Location[]][]; assignment?: Assignment["assignment"] }) {
  const [projectId, setProjectId] = useState(assignment?.projectId ?? ""); const locations = new Map(locationsByProject).get(projectId) ?? [];
  if (period.status !== "DRAFT") return null;
  return <ActionForm action={assignment ? updateScheduleAssignmentAction : addScheduleAssignmentAction} title={assignment ? "Edit schedule assignment" : "Add schedule assignment"} submit={assignment ? "Save assignment" : "Add assignment"}><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedPeriodVersion" value={period.version} />{assignment ? <><input type="hidden" name="assignmentId" value={assignment.id} /><input type="hidden" name="expectedVersion" value={assignment.version} /></> : null}<label>Employee<select name="employeeUserId" required defaultValue={assignment?.employeeUserId ?? ""}><option value="">Choose visible Employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.displayName}</option>)}</select></label><label>Project<select name="projectId" required value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Choose Project</option>{projects.map(({ project }) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Linked Location<select name="locationId" required defaultValue={assignment?.locationId ?? ""} key={projectId}><option value="">Choose linked Location</option>{locations.map(({ location }) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><div className="schedule-form-grid"><label>Date<input name="assignmentDate" type="date" defaultValue={assignment?.assignmentDate ?? `${period.planningMonth.slice(0, 7)}-01`} required /></label><label>Start time<input name="startTime" type="time" defaultValue={assignment?.startTime.slice(0, 5) ?? "09:00"} required /></label><label>End time<input name="endTime" type="time" defaultValue={assignment?.endTime.slice(0, 5) ?? "17:00"} required /></label></div><label>Short work instruction · shared with this Employee<textarea name="sharedInstruction" maxLength={500} defaultValue={assignment?.sharedInstruction ?? ""} rows={2} /></label><p className="schedule-help">Same-day timed assignment only. All times use Asia/Dubai.</p></ActionForm>;
}

export function AssignmentList({ period, assignments, employees, projects, locationsByProject, skills, canManage, coverageAssignmentIds = [] }: { period: Period; assignments: Assignment[]; employees: Employee[]; projects: Project[]; locationsByProject: [string, Location[]][]; skills: { id: string; name: string }[]; canManage: boolean; coverageAssignmentIds?: string[] }) {
  const editable = canManage && period.status === "DRAFT";
  return <section className="schedule-panel"><div className="schedule-panel-heading"><div><h3>Assignments <span className="workflow-count">{assignments.length}</span></h3><p className="schedule-help">Who is working, where, and when.</p></div>{editable ? <TaskDialog triggerLabel="Add assignment" title="Add schedule assignment" description="Choose an employee, project, and linked location." triggerClassName="button primary">{employees.length && projects.length ? <AssignmentForm period={period} employees={employees} projects={projects} locationsByProject={locationsByProject} /> : <p className="workflow-empty">No employees or projects are available for this selection. Adjust the skill filter or ask your Super Admin to check your team and project access.</p>}</TaskDialog> : null}</div>
    {assignments.length ? <div className="workflow-assignment-list">{assignments.map((item) => <article key={item.assignment.id} className="workflow-assignment"><div className="workflow-assignment-heading"><div><h4>{item.employeeName}</h4><p>{item.assignment.assignmentDate} · <strong>{item.assignment.startTime.slice(0, 5)}–{item.assignment.endTime.slice(0, 5)}</strong></p><p>{item.projectName} · {item.locationName}</p></div><div className="workflow-row-actions">{coverageAssignmentIds.includes(item.assignment.id) ? <Link className="button" href={`/coverage?assignment=${item.assignment.id}`}>Review coverage</Link> : null}{editable ? <TaskDialog triggerLabel="Edit assignment" triggerClassName="button" title={`Edit ${item.employeeName}’s assignment`}><AssignmentForm period={period} employees={employees} projects={projects} locationsByProject={locationsByProject} assignment={item.assignment} /><details className="workflow-advanced"><summary>Remove assignment</summary><p>Assignments with retained skill requirements or replacement history cannot be removed.</p><ActionForm persistentFeedback action={removeScheduleAssignmentAction} title={`Remove ${item.employeeName} assignment`} submit="Remove" danger><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="assignmentId" value={item.assignment.id} /><input type="hidden" name="expectedPeriodVersion" value={period.version} /><input type="hidden" name="expectedVersion" value={item.assignment.version} /></ActionForm></details></TaskDialog> : null}</div></div>
    {item.assignment.sharedInstruction ? <p className="workflow-work-note">{item.assignment.sharedInstruction}</p> : null}<details className="workflow-advanced"><summary>Skills and requirements ({item.requirements.length})</summary><AssignmentSkillRequirementPanel assignmentId={item.assignment.id} canManage={editable} skills={skills} requirements={item.requirements} /></details></article>)}</div> : <div className="workflow-empty"><h4>No assignments yet</h4><p>{editable ? "Add the first assignment to start planning this month." : "There are no assignments in this schedule."}</p></div>}
  </section>;
}
