"use client";

import { useActionState, useState } from "react";
import { addScheduleAssignmentAction, createSchedulePeriodAction, createScheduleRevisionAction, proposeScheduleAction, publishScheduleAction, removeScheduleAssignmentAction, returnScheduleToDraftAction, updateScheduleAssignmentAction, type SchedulingAction, type SchedulingActionState } from "@/modules/scheduling/actions";

const initial: SchedulingActionState = {};
type Employee = { id: string; displayName: string };
type Project = { project: { id: string; name: string } };
type Location = { location: { id: string; name: string } };
type Assignment = { assignment: { id: string; employeeUserId: string; projectId: string; locationId: string; assignmentDate: string; startTime: string; endTime: string; sharedInstruction: string | null; version: number }; employeeName: string; projectName: string; locationName: string };
type Period = { id: string; clientId: string; planningMonth: string; revisionNumber: number; parentPeriodId: string | null; status: "DRAFT" | "PROPOSED" | "PUBLISHED"; isCurrent: boolean; lastReturnReason: string | null; version: number };
function Feedback({ state }: { state: SchedulingActionState }) { return state.error ? <p className="schedule-error" role="alert">{state.error}</p> : state.success ? <p className="schedule-success" role="status">{state.success}</p> : null; }
function ActionForm({ action, title, children, submit = "Save", danger = false }: { action: SchedulingAction; title: string; children: React.ReactNode; submit?: string; danger?: boolean }) { const [state, formAction, pending] = useActionState(action, initial); return <form className="schedule-form" action={formAction} aria-label={title}>{children}<Feedback state={state} /><button className={`button ${danger ? "danger" : "primary"}`} type="submit" disabled={pending}>{pending ? "Saving…" : submit}</button></form>; }

export function CreatePeriodForm({ clients, month }: { clients: { id: string; companyName: string }[]; month: string }) { return <ActionForm action={createSchedulePeriodAction} title="Create a monthly Draft" submit="Create Draft"><label>Client<select name="clientId" required defaultValue=""><option value="">Choose Client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.companyName}</option>)}</select></label><label>Planning month<input name="month" type="month" defaultValue={month} required /></label><p className="schedule-help">One Client-month Draft at a time. Planning timezone: Asia/Dubai.</p></ActionForm>; }

export function LifecyclePanel({ period, clientName, canManage, canPropose, canPublish }: { period: Period; clientName: string; canManage: boolean; canPropose: boolean; canPublish: boolean }) {
  return <section className="schedule-panel"><div className="schedule-panel-heading"><div><p className="eyebrow">Client-month schedule</p><h3>{clientName} · {period.planningMonth.slice(0, 7)} · Revision {period.revisionNumber}</h3></div><span className={`schedule-status ${period.status.toLowerCase()}`}>{period.status}</span></div><p className="schedule-help">All schedule times use the organization planning timezone: <strong>Asia/Dubai</strong>. Published versions are immutable.</p>{period.lastReturnReason && period.status === "DRAFT" ? <p className="schedule-callout">Returned to Draft with reason: {period.lastReturnReason}</p> : null}<div className="schedule-actions">{canManage && period.status === "DRAFT" ? <ActionForm action={proposeScheduleAction} title="Propose this Draft" submit="Propose for review"><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedVersion" value={period.version} /></ActionForm> : null}{canPublish && period.status === "PROPOSED" ? <><ActionForm action={returnScheduleToDraftAction} title="Return Proposed schedule to Draft" submit="Return to Draft"><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedVersion" value={period.version} /><label>Reason for return<textarea name="reason" minLength={3} maxLength={500} required rows={2} /></label></ActionForm><ActionForm action={publishScheduleAction} title="Publish Proposed schedule" submit="Publish schedule"><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedVersion" value={period.version} /></ActionForm></> : null}{canPublish && period.status === "PUBLISHED" && period.isCurrent ? <ActionForm action={createScheduleRevisionAction} title="Create an editable revision" submit="Create Draft revision"><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedVersion" value={period.version} /></ActionForm> : null}</div>{period.status !== "DRAFT" ? <p className="schedule-help">This version is read-only. Super Admin must return a Proposed version to Draft; Published changes use a new revision.</p> : null}</section>;
}

export function AssignmentForm({ period, employees, projects, locationsByProject, assignment }: { period: Period; employees: Employee[]; projects: Project[]; locationsByProject: [string, Location[]][]; assignment?: Assignment["assignment"] }) {
  const [projectId, setProjectId] = useState(assignment?.projectId ?? ""); const locations = new Map(locationsByProject).get(projectId) ?? [];
  if (period.status !== "DRAFT") return null;
  return <ActionForm action={assignment ? updateScheduleAssignmentAction : addScheduleAssignmentAction} title={assignment ? "Edit schedule assignment" : "Add schedule assignment"} submit={assignment ? "Save assignment" : "Add assignment"}><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="expectedPeriodVersion" value={period.version} />{assignment ? <><input type="hidden" name="assignmentId" value={assignment.id} /><input type="hidden" name="expectedVersion" value={assignment.version} /></> : null}<label>Employee<select name="employeeUserId" required defaultValue={assignment?.employeeUserId ?? ""}><option value="">Choose visible Employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.displayName}</option>)}</select></label><label>Project<select name="projectId" required value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Choose Project</option>{projects.map(({ project }) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Linked Location<select name="locationId" required defaultValue={assignment?.locationId ?? ""} key={projectId}><option value="">Choose linked Location</option>{locations.map(({ location }) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><div className="schedule-form-grid"><label>Date<input name="assignmentDate" type="date" defaultValue={assignment?.assignmentDate ?? `${period.planningMonth.slice(0, 7)}-01`} required /></label><label>Start time<input name="startTime" type="time" defaultValue={assignment?.startTime.slice(0, 5) ?? "09:00"} required /></label><label>End time<input name="endTime" type="time" defaultValue={assignment?.endTime.slice(0, 5) ?? "17:00"} required /></label></div><label>Short work instruction · shared with this Employee<textarea name="sharedInstruction" maxLength={500} defaultValue={assignment?.sharedInstruction ?? ""} rows={2} /></label><p className="schedule-help">Same-day timed assignment only. No address, access instructions, route, attendance, or arrangement logic is copied here.</p></ActionForm>;
}

export function AssignmentList({ period, assignments, employees, projects, locationsByProject, canManage }: { period: Period; assignments: Assignment[]; employees: Employee[]; projects: Project[]; locationsByProject: [string, Location[]][]; canManage: boolean }) { return <section className="schedule-panel"><div className="schedule-panel-heading"><div><h3>Assignments</h3><p className="schedule-help">{assignments.length} planned timed assignment{assignments.length === 1 ? "" : "s"}. Assignment is distinct from Client relationships, operational associations, and staffing requirements.</p></div></div>{canManage && period.status === "DRAFT" ? <AssignmentForm period={period} employees={employees} projects={projects} locationsByProject={locationsByProject} /> : null}{assignments.length ? <div className="schedule-assignment-list">{assignments.map((item) => <article key={item.assignment.id} className="schedule-assignment"><div><strong>{item.employeeName}</strong><span>{item.assignment.assignmentDate} · {item.assignment.startTime.slice(0, 5)}–{item.assignment.endTime.slice(0, 5)} · {item.projectName} · {item.locationName}</span>{item.assignment.sharedInstruction ? <p>{item.assignment.sharedInstruction}</p> : null}</div>{canManage && period.status === "DRAFT" ? <div className="schedule-assignment-actions"><AssignmentForm period={period} employees={employees} projects={projects} locationsByProject={locationsByProject} assignment={item.assignment} /><ActionForm action={removeScheduleAssignmentAction} title={`Remove ${item.employeeName} assignment`} submit="Remove" danger><input type="hidden" name="periodId" value={period.id} /><input type="hidden" name="assignmentId" value={item.assignment.id} /><input type="hidden" name="expectedPeriodVersion" value={period.version} /><input type="hidden" name="expectedVersion" value={item.assignment.version} /></ActionForm></div> : null}</article>)}</div> : <p className="schedule-empty">No assignments yet. Add a real active Employee, Project, and linked Location to this Draft.</p>}</section>; }
