"use client";

import { useState } from "react";
import Link from "next/link";
import { CalendarDays, LayoutList, UsersRound, MapPin, Clock3 } from "lucide-react";
import { TaskDialog } from "@/shared/components/task-dialog";
import type { TimetableEntry } from "./timetable-service";
import { displayDate, monthDays, monthOffset } from "./calendar-dates";

const views = [{ key: "month", name: "Month", icon: CalendarDays }, { key: "people", name: "People", icon: UsersRound }, { key: "agenda", name: "Agenda", icon: LayoutList }] as const;
function Entry({ entry, month, manager }: { entry: TimetableEntry; month: string; manager: boolean }) {
  return <article className="timetable-entry"><div className="timetable-entry-top"><strong>{entry.employeeName}</strong><span><Clock3 size={14} aria-hidden="true" />{entry.start}–{entry.end}</span></div><h4>{entry.projectName}</h4><p>{entry.clientName}</p><p><MapPin size={14} aria-hidden="true" />{entry.locationName}</p>{entry.instruction ? <p className="timetable-instruction">{entry.instruction}</p> : null}{entry.status !== "PUBLISHED" ? <span className="schedule-status">{entry.status === "DRAFT" ? "Draft" : "Proposed"} · unpublished</span> : null}{manager ? <div className="timetable-entry-links"><Link href={`/schedule?month=${month}&period=${entry.periodId}${entry.status !== "PUBLISHED" ? "&mode=planning" : ""}#schedule-editor`}>Open schedule</Link><Link href={`/coverage?assignment=${entry.id}&month=${month}`}>Review coverage</Link></div> : null}</article>;
}
function Day({ date, entries, month, manager }: { date: string; entries: TimetableEntry[]; month: string; manager: boolean }) {
  return <TaskDialog triggerLabel={`Open ${displayDate(date)} · ${entries.length} assignment${entries.length === 1 ? "" : "s"}`} title={displayDate(date)} description="Who, where and what · all times Asia/Dubai" triggerClassName="timetable-day-button" dismissOnNavigate triggerIcon={<><span className="timetable-day-number">{Number(date.slice(-2))}</span><span className="timetable-day-count">{entries.length ? `${entries.length} work item${entries.length === 1 ? "" : "s"}` : "No assignments"}</span><span className="timetable-day-preview">{entries.slice(0, 2).map((entry) => <span className="timetable-mini" key={entry.id}><strong>{entry.employeeName}<small>{entry.start}–{entry.end}</small></strong><span>{entry.projectName}</span><small>{entry.locationName}</small></span>)}{entries.length > 2 ? <em>+{entries.length - 2} more</em> : null}</span></>}><div className="timetable-day-details">{entries.length ? entries.map((entry) => <Entry key={entry.id} entry={entry} month={month} manager={manager} />) : <p>No assignments recorded for this day.</p>}</div></TaskDialog>;
}

export function Timetable({ entries, month, manager, planning, today }: { entries: TimetableEntry[]; month: string; manager: boolean; planning: boolean; today: string }) {
  const [view, setView] = useState<"month" | "people" | "agenda">("month");
  const [person, setPerson] = useState(""); const [client, setClient] = useState(""); const [project, setProject] = useState("");
  const people = [...new Map(entries.map((entry) => [entry.employeeId, entry.employeeName])).entries()].sort((a, b) => a[1].localeCompare(b[1]));
  const clients = [...new Map(entries.map((entry) => [entry.clientId, entry.clientName])).entries()].sort((a, b) => a[1].localeCompare(b[1]));
  const projects = [...new Map(entries.filter((entry) => !client || entry.clientId === client).map((entry) => [entry.projectId, entry.projectName])).entries()].sort((a, b) => a[1].localeCompare(b[1]));
  const filtered = entries.filter((entry) => (!person || person === entry.employeeId) && (!client || client === entry.clientId) && (!project || project === entry.projectId));
  const personCount = new Set(filtered.map((entry) => entry.employeeId)).size;
  const siteCount = new Set(filtered.map((entry) => entry.locationName)).size;
  const days = monthDays(month); const dayEntries = (date: string) => filtered.filter((entry) => entry.date === date);
  const rows = people.filter(([id]) => !person || person === id);
  return <section className="timetable" aria-label="Monthly timetable"><div className="timetable-top"><div><p className="eyebrow">{planning ? "Planning · unpublished" : "Published work"}</p><h3>{displayDate(`${month}-01`, { month: "long", year: "numeric" })}</h3><p className="timetable-summary" aria-live="polite">{filtered.length} assignment{filtered.length === 1 ? "" : "s"} · {personCount} {personCount === 1 ? "person" : "people"} · {siteCount} site{siteCount === 1 ? "" : "s"}</p></div><div className="timetable-views" role="group" aria-label="Timetable view">{views.map(({ key, name, icon: Icon }) => <button key={key} className="button" aria-pressed={view === key} onClick={() => setView(key)}><Icon size={16} aria-hidden="true" />{name}</button>)}</div></div>
    <details className="timetable-filter-disclosure"><summary>Filter timetable{person || client || project ? " · filters applied" : ""}</summary><div className="timetable-filters">{manager ? <label>Person<select value={person} onChange={(event) => setPerson(event.target.value)}><option value="">Everyone</option>{people.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label> : null}<label>Client<select value={client} onChange={(event) => { setClient(event.target.value); setProject(""); }}><option value="">All clients</option>{clients.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Project<select value={project} onChange={(event) => setProject(event.target.value)}><option value="">All projects</option>{projects.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>{person || client || project ? <button className="button" onClick={() => { setPerson(""); setClient(""); setProject(""); }}>Clear filters</button> : null}</div></details>
    {planning ? <p className="timetable-notice">These plans are not yet published. Published work appears in the Published view.</p> : null}
    {!filtered.length ? <div className="workflow-empty"><h4>{entries.length ? "No assignments match these filters" : `No ${planning ? "planned" : "published"} assignments this month`}</h4><p>{manager ? "Review monthly schedules below. Super Admin prepares and publishes the plan." : "Your assignments will appear when the schedule is published."}</p></div> : null}
    {view === "month" ? <><p className="timetable-help">Select a day to see every assignment, location and work instruction.</p><div className="timetable-calendar-scroll" role="region" aria-label="Month calendar, scroll horizontally" tabIndex={0}><div className="timetable-weekdays" aria-hidden="true">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div><div className="timetable-month">{Array.from({ length: monthOffset(month) }, (_, index) => <div className="timetable-day blank" key={`blank-${index}`} />)}{days.map((date) => <div className={`timetable-day ${date === today ? "today" : ""} ${dayEntries(date).length ? "has-work" : ""}`} key={date}><Day date={date} entries={dayEntries(date)} month={month} manager={manager} /></div>)}</div></div><p className="timetable-mobile-hint">Tap a day for details, or choose Agenda to read the month as a list.</p></> : null}
    {view === "people" ? <><p className="timetable-help">People by day · scroll across the month. Blank cells mean no recorded assignment.</p><div className="timetable-matrix-scroll" tabIndex={0} role="region" aria-label="People by day, scroll horizontally"><table className="timetable-matrix"><caption>{displayDate(`${month}-01`, { month: "long", year: "numeric" })} · assignments by person</caption><thead><tr><th scope="col">Person</th>{days.map((date) => <th scope="col" key={date}>{Number(date.slice(-2))}<small>{displayDate(date, { weekday: "short" })}</small></th>)}</tr></thead><tbody>{rows.map(([id, name]) => <tr key={id}><th scope="row">{name}</th>{days.map((date) => { const work = dayEntries(date).filter((entry) => entry.employeeId === id); return <td key={date}>{work.length ? <TaskDialog triggerLabel={`${name}, ${displayDate(date)}: ${work.length} assignment${work.length === 1 ? "" : "s"}`} title={`${name} · ${displayDate(date)}`} triggerClassName="timetable-matrix-button" dismissOnNavigate triggerIcon={<span>{work.map((entry) => <span className="timetable-matrix-item" key={entry.id}><strong>{entry.start}–{entry.end}</strong><span>{entry.projectName}</span><small>{entry.locationName}</small></span>)}</span>}><div className="timetable-day-details">{work.map((entry) => <Entry key={entry.id} entry={entry} month={month} manager={manager} />)}</div></TaskDialog> : <><span aria-hidden="true">—</span><span className="workflow-sr-only">No assignment</span></>}</td>; })}</tr>)}</tbody></table></div></> : null}
    {view === "agenda" ? <div className="timetable-agenda">{days.filter((date) => dayEntries(date).length).map((date) => <section key={date}><h4>{displayDate(date)}</h4><div>{dayEntries(date).map((entry) => <Entry key={entry.id} entry={entry} month={month} manager={manager} />)}</div></section>)}</div> : null}
  </section>;
}
