"use client";

import { projects, type PreviewEmployee } from "@/preview/preview-data";

type Assignment = { id: string; employeeId: string; projectId: string; date: string; time: string; type: string; state: string; location: string; warning: string };

function day(date: Date) { return date.toISOString().slice(0, 10); }
function shortDay(date: Date) { return new Intl.DateTimeFormat("en-GB", { weekday: "short", day: "numeric", timeZone: "UTC" }).format(date); }

export function ScheduleAlternative({ layout, people, weekDays, assignments, selectedId, onSelect }: { layout: "2" | "3"; people: PreviewEmployee[]; weekDays: Date[]; assignments: Assignment[]; selectedId?: string; onSelect: (id: string) => void }) {
  if (layout === "2") return <section className="schedule-alternative timeline-planner"><header><h2>Timeline / resource planner</h2><p>Assignment bars prioritize duration, workload and overlaps across the same filtered planning records.</p></header><div className="timeline-scroll"><div className="timeline-header"><span>Resource</span>{weekDays.map((date) => <span key={day(date)}>{shortDay(date)}</span>)}</div>{people.map((person) => <div className="timeline-row" key={person.id}><strong>{person.name}<small>{person.designation}</small></strong>{weekDays.map((date) => { const records = assignments.filter((item) => item.employeeId === person.id && item.date === day(date)); return <div key={day(date)}>{records.map((item) => <button key={item.id} className={`timeline-bar ${item.state.toLowerCase()}${selectedId === item.id ? " selected" : ""}`} type="button" onClick={() => onSelect(item.id)}><span>{projects.find((project) => project.id === item.projectId)?.name}</span><small>{item.time}</small></button>)}</div>; })}</div>)}</div><p className="schedule-alternative-note">Milestone emphasis: work is grouped by employee with state, duration label and selected assignment visibility. No schedule change is stored.</p></section>;
  const demand = assignments.filter((item) => item.warning || item.state === "Draft").slice(0, 8);
  return <section className="schedule-alternative demand-workspace"><header><h2>Work-demand and allocation workspace</h2><p>Start with work requiring attention, then compare the same filtered schedule and eligible people.</p></header><div className="demand-columns"><aside><h3>Demand needing review</h3>{demand.length ? demand.map((item) => <button key={item.id} className={selectedId === item.id ? "demand-item selected" : "demand-item"} type="button" onClick={() => onSelect(item.id)}><strong>{projects.find((project) => project.id === item.projectId)?.name}</strong><span>{item.date} · {item.location}</span><small>{item.warning || `${item.state} work awaiting allocation review`}</small></button>) : <p className="muted">No Draft or warning records match these filters.</p>}</aside><section><h3>Week allocation board</h3><div className="demand-board">{weekDays.map((date) => <div key={day(date)}><strong>{shortDay(date)}</strong>{assignments.filter((item) => item.date === day(date)).slice(0, 10).map((item) => <button key={item.id} className={selectedId === item.id ? "demand-block selected" : "demand-block"} type="button" onClick={() => onSelect(item.id)}>{projects.find((project) => project.id === item.projectId)?.name}<small>{people.find((person) => person.id === item.employeeId)?.name} · {item.state}</small></button>)}</div>)}</div></section><aside><h3>Candidate context</h3><p className="muted">Select a demand item to compare people. Candidate guidance uses the existing team-filtered skills, availability and assignment records.</p>{selectedId ? <ul className="rich-list">{people.filter((person) => person.availability !== "On leave").slice(0, 6).map((person) => <li key={person.id}><strong>{person.name}</strong><span>{person.designation} · {person.availability} · candidate review only</span></li>)}</ul> : null}</aside></div><p className="schedule-alternative-note">Allocation controls are demonstrative only. Demo only — this change is not saved and will reset on refresh.</p></section>;
}
