import type { ModuleKey } from "@/modules/authorization/capabilities";
import type { SystemRole } from "@/shared/types/foundation";

type Step = { title: string; detail: string };
export type PageJourney = { goal: string; steps: Step[]; related: ModuleKey[] };
const step = (title: string, detail: string): Step => ({ title, detail });
const journeys: Record<ModuleKey, PageJourney> = {
  dashboard: { goal: "Know what needs your attention and choose where to start.", steps: [step("Check requests", "Open a review card or update that needs your attention."), step("See the plan", "Open the timetable to see who is working where."), step("Explore when needed", "Open More team insights for the supporting figures.")], related: ["schedule", "notifications"] },
  tickets: { goal: "Follow company tickets within the workspaces you can access.", steps: [step("Choose your work", "Open an available workspace and board to see its tickets."), step("Find a ticket", "Use the ticket view and filters to find the work you need."), step("Follow progress", "Open a ticket to read its details and use the actions available to your role.")], related: ["schedule", "notifications"] },
  schedule: { goal: "See who is where, when they are working and what they are doing.", steps: [step("Choose a month", "Use Month for an overview, People for one person across the month, or Agenda for full details."), step("Prepare work", "Choose Plan work, select a client’s monthly schedule and add people, times, projects and locations."), step("Share the final plan", "Draft means editable. Proposed means ready for review. Only Super Admin can publish; employees see Published work.")], related: ["map", "coverage"] },
  map: { goal: "See the day’s published work by person and location.", steps: [step("Choose a day", "The map shows the stored plan for that date, rather than anyone’s live position."), step("Choose a person or site", "Select a pin or search the assignment list to see the person, work and time."), step("Take the next step", "Check cover if support is needed, or open the timetable to review the assignment.")], related: ["schedule", "coverage"] },
  coverage: { goal: "Find scheduled work that needs another person or a missing skill.", steps: [step("Choose the work", "Search by person, client, project or site, then open Check cover."), step("Choose the change", "Replace a person to hand over their work, or add support so they keep their assignment."), step("Review and publish", "Follow the request in Cover requests. Approval prepares a Draft; Super Admin publishes it from Timetable.")], related: ["replacements", "schedule"] },
  replacements: { goal: "Review requests to replace someone or add extra support.", steps: [step("Read the request", "Check the person, date, work and whether the request is for a replacement or extra support."), step("Make a decision", "Review an eligible person, then approve or decline. Approval prepares an editable Draft."), step("Publish the update", "Open Timetable and review the updated client schedule before publishing it.")], related: ["coverage", "schedule", "requests"] },
  requests: { goal: "Follow the cover requests you participate in and discuss the next step.", steps: [step("Choose a request", "Check the request type, date and decision status."), step("Open the conversation", "Expand a request to read or write messages to the people on it."), step("Check your work", "The timetable shows your published assignments. A request approval by itself does not publish a change.")], related: ["schedule", "replacements"] },
  leave: { goal: "Review time-off requests and their effect on the published plan.", steps: [step("Choose a request", "Select Review beside a person’s pending leave request."), step("Check the details", "Review dates, annual balance and any overlapping published work."), step("Record your decision", "Only Super Admin can approve or decline. Arrange cover separately when required.")], related: ["coverage", "schedule"] },
  employees: { goal: "Find a person and open their work record.", steps: [step("Find the person", "Search by name or employee code, or filter by team, job title and status."), step("Open their record", "Review work details, recorded skills and the documents you can access."), step("Manage the right thing", "Team and job title describe the person’s work. Their system role and access permissions are managed separately.")], related: ["teams", "designations", "skills"] },
  teams: { goal: "Organize people into teams and keep membership up to date.", steps: [step("Create a team", "Choose New team and give it a clear name."), step("Add people", "Choose Add member. A person belongs to one team; moving them replaces their current membership."), step("Keep it current", "Rename the team or remove a member. Removing membership keeps their employee record and history.")], related: ["employees", "designations"] },
  designations: { goal: "Manage job titles, also called designations, and the people who hold them.", steps: [step("Create a job title", "Choose New job title and enter the title used by your company."), step("Assign people", "Choose Add member. Each person has one job title."), step("Keep access separate", "A job title never grants permissions. Super Admin, Admin and Employee are separate system roles.")], related: ["employees", "teams"] },
  skills: { goal: "See and record the skills held by each person.", steps: [step("Choose a person", "Select an employee and open their recorded skills."), step("Record a skill", "Add a skill from the shared list or archive a record that is no longer current."), step("Manage the shared list", "Open Manage skill list to create or rename skills. Documents and certifications are reviewed separately.")], related: ["employees", "coverage"] },
  profile: { goal: "Keep your work details, experience and documents up to date.", steps: [step("Edit your details", "Choose Edit profile to update work contact details and your professional summary."), step("Add your documents", "Use Certifications, Portfolio, Project examples, CV or Supporting documents."), step("Follow reviews", "Check each item’s review status and Notifications for updates. Uploading a document does not automatically record a skill.")], related: ["skills", "notifications"] },
  clients: { goal: "Keep each customer’s work and contacts together.", steps: [step("Open or create a client", "Search for a company, or create its client record."), step("Add the work and sites", "Create projects under that client, then connect locations belonging to the same client."), step("Plan the people", "Open Timetable to assign people, times, projects and locations.")], related: ["projects", "locations", "schedule"] },
  projects: { goal: "Describe the work your team will do for a client.", steps: [step("Choose a client", "Create or open a project under the client it belongs to."), step("Prepare the work", "Set dates, link the client’s locations and record skills or staffing requirements where needed."), step("Assign people", "Open Timetable to plan who will do that work and when.")], related: ["clients", "locations", "schedule"] },
  locations: { goal: "Keep the places your team works ready for planning.", steps: [step("Open or create a site", "Choose its client and record the address and visit instructions."), step("Connect the work", "Link a project belonging to that same client."), step("Use it in the plan", "Choose this location when assigning work in Timetable. Published assignments can appear on the work map.")], related: ["projects", "schedule", "map"] },
  reports: { goal: "Answer a team question using the records you can access.", steps: [step("Find your question", "Search the report list by task, topic or report name."), step("Choose the view", "Open a report and select the relevant dates and filters. Unpublished plans are labelled separately."), step("Read or download", "Review the results and use Download CSV where available. How to read this report explains the figures.")], related: ["dashboard", "schedule"] },
  notifications: { goal: "Read your updates and open the work they refer to.", steps: [step("Check unread updates", "Choose Unread to focus on new messages."), step("Open the next action", "Use the update’s link to review the request, document or work record."), step("Tidy your inbox", "Mark an update read when checked. Archive moves it out of the inbox; it does not change the related work.")], related: ["requests", "schedule"] },
  accounts: { goal: "Manage how your team signs in.", steps: [step("Find the account", "Search by person or username and check their sign-in setup."), step("Create or restore sign-in", "Create an account, enable sign-in for an existing person, or set a temporary password when needed."), step("Manage access separately", "Open the person’s record to manage their system role and access. Existing passwords cannot be viewed.")], related: ["employees", "audit"] },
  audit: { goal: "See who changed what and when.", steps: [step("Find an action", "Filter by action, record type, person or date."), step("Read the history", "Check the action, time and person. Record details contains technical references."), step("Keep the record intact", "This is a read-only history. Make any new change from the relevant work page.")], related: ["accounts", "reports"] },
  settings: { goal: "Workspace settings are not available yet.", steps: [step("Use the working tools", "Manage people, accounts and schedules from their pages."), step("Personal preferences", "Use the theme button in the header or My profile for your own details.")], related: ["profile", "accounts"] },
};

export function pageJourney(key: ModuleKey, role: SystemRole): PageJourney {
  const base = journeys[key];
  if (role === "EMPLOYEE") {
    if (key === "dashboard") return { ...base, goal: "Check your work summary and open your next ticket.", steps: [step("Start with tickets", "Open Tickets to follow the work available to you."), step("Check your plan", "Open Schedule for your published times, sites and instructions, or Vacations to request time off."), step("Keep your profile current", "Read your skills and update work details and documents in My profile.")], related: ["tickets", "schedule", "leave", "profile"] };
    if (key === "tickets") return { ...base, goal: "Start your workday with the tickets you can access.", steps: [step("Find your work", "Choose an available workspace and board, then use the filters to find your tickets."), step("Open a ticket", "Read the details, priority and current status. Available actions follow your role and ticket access."), step("Check your plan", "Use Schedule for your published assignments and Vacations when you need time off.")], related: ["schedule", "leave", "profile"] };
    if (key === "schedule") return { ...base, steps: [base.steps[0], step("Open a day", "Read your times, project, site and shared work instructions."), step("Follow changes", "Only published work appears here. Check Notifications for schedule updates.")], related: ["leave", "requests"] };
    if (key === "employees") return { ...base, goal: "View your own employee record and recorded skills.", steps: [step("Open your record", "Check your work details and recorded skills."), step("Update your details", "Use My profile to edit your work contacts and professional summary."), step("Ask about corrections", "Your Super Admin manages team, job title and skill records.")], related: ["profile", "skills"] };
    if (key === "skills") return { ...base, goal: "See the skills recorded on your employee record.", steps: [step("Read your skills", "These records are maintained by Super Admin."), step("Add supporting documents", "Upload certifications and experience in My profile."), step("Ask for a correction", "Contact your Super Admin if a skill record needs updating.")], related: ["profile"] };
    if (key === "profile") return { ...base, goal: "See your skills and keep your professional profile current.", steps: [step("Read your skills", "Recorded skills are maintained by Super Admin. Ask them if a record needs correcting."), step("Update your details", "Choose Edit profile to update your work contacts and professional summary."), step("Add supporting evidence", "Upload certifications, experience, portfolio files or your CV. Documents do not automatically record a skill.")], related: ["tickets", "schedule", "notifications"] };
    if (key === "leave") return { ...base, goal: "Apply for vacation and follow your vacation history.", steps: [step("Choose your dates", "Check your annual balance and submit your vacation request."), step("Follow the decision", "Super Admin reviews the request. Pending dates are not approved time off."), step("Review your vacations", "See your previous requests and decisions, then check your published Schedule.")], related: ["schedule", "notifications"] };
  }
  if (role !== "SUPER_ADMIN" && key === "leave") return { ...base, goal: "Request annual leave and follow its decision.", steps: [step("Choose your dates", "Check your balance and submit a leave request."), step("Follow the decision", "Super Admin reviews your request. Pending dates are not approved time off."), step("Review your plan", "Check Timetable after a decision. Admins can also see approved team leave within their access.")], related: ["schedule", "notifications"] };
  if (role === "ADMIN" && key === "schedule") return { ...base, steps: [base.steps[0], base.steps[1], step("Send it for review", "Propose the Draft when ready. Super Admin reviews and publishes; employees see Published work.")] };
  if (role === "ADMIN" && key === "replacements") return { ...base, goal: "Follow decisions on the cover requests you created.", steps: [step("Create a request", "Choose an assignment in Find cover and request a replacement or extra support."), step("Follow its status", "Super Admin chooses a person and approves or declines."), step("Check the timetable", "Approval prepares a Draft. The published plan changes only after Super Admin publishes it.")] };
  if (role === "ADMIN" && key === "skills") return { ...base, goal: "Find people with a recorded skill within your team access.", steps: [step("Choose a skill", "Pick a skill from the list."), step("View matching people", "Read the results to see who has that recorded skill."), step("Plan work", "Use the timetable or Find cover to review the work. Super Admin manages the skill records.")] };
  return base;
}
