import { notFound, redirect } from "next/navigation";
import { getCurrentActor } from "@/modules/auth/session-service";
import { PlanningMapClient } from "@/modules/maps/planning-map-client";
import { planningMapService } from "@/modules/maps/service";
import { dubaiToday } from "@/modules/maps/validation";

type Params = Record<string, string | string[] | undefined>;
const one = (value: string | string[] | undefined) => Array.isArray(value) ? undefined : value;
export default async function PlanningMapPage({ searchParams }: { searchParams: Promise<Params> }) {
  const actor = await getCurrentActor(); if (!actor) redirect("/login"); if (actor.role === "EMPLOYEE") notFound(); const raw = await searchParams; const query = { date: one(raw.date) ?? dubaiToday(), employeeId: one(raw.employeeId), skillId: one(raw.skillId), clientId: one(raw.clientId), projectId: one(raw.projectId), locationId: one(raw.locationId), unavailable: one(raw.unavailable), coverageGap: one(raw.coverageGap) }; const projection = await planningMapService.projection(actor, query);
  return <section className="planning-map-page"><header><p className="eyebrow">Management planning</p><h2>Static planning map</h2><p className="planning-map-disclaimer">Planning status for {projection.selectedDate} — based on the Published schedule, not live tracking.</p></header><form className="planning-map-filters" action="/map"><label>Date (Asia/Dubai)<input name="date" type="date" defaultValue={projection.selectedDate} required /></label>{([ ["employeeId", "Employee", projection.filterOptions.employees], ["skillId", "Skill", projection.filterOptions.skills], ["clientId", "Client", projection.filterOptions.clients], ["projectId", "Project", projection.filterOptions.projects], ["locationId", "Location", projection.filterOptions.locations] ] as const).map(([name, label, options]) => <label key={name}>{label}<select name={name} defaultValue={one(raw[name]) ?? ""}><option value="">All authorized</option>{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>)}<label className="operation-check"><input type="checkbox" name="unavailable" value="true" defaultChecked={one(raw.unavailable) === "true"} />Approved unavailable</label><label className="operation-check"><input type="checkbox" name="coverageGap" value="true" defaultChecked={one(raw.coverageGap) === "true"} />Coverage gap</label><div><button className="button primary">Apply filters</button><a className="button" href={`/map?date=${projection.selectedDate}`}>Reset</a></div></form>{projection.invalidFilter ? <p className="operation-error" role="alert">That filter is unavailable for your authorized planning projection.</p> : null}<p className="planning-map-meta">{projection.assignments.length} authorized Published assignment{projection.assignments.length === 1 ? "" : "s"}. {projection.lastPublishedAt ? `Last relevant publication: ${new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Dubai" }).format(new Date(projection.lastPublishedAt))} Asia/Dubai.` : "No relevant publication."}{projection.noCoordinateCount ? ` ${projection.noCoordinateCount} employee marker${projection.noCoordinateCount === 1 ? " is" : "s are"} omitted because no approved coordinate is stored.` : ""}</p>{projection.assignments.length ? <PlanningMapClient projection={projection} /> : <div className="operation-empty"><h3>No authorized published planning facts</h3><p>Adjust the selected date or filters. This view never includes Draft or Proposed scheduling.</p></div>}</section>;
}
