import { redirect } from "next/navigation";
import { getCurrentActor } from "@/modules/auth/session-service";
import { capabilityService } from "@/modules/capabilities/service";
import { EmployeeSkillManager, SkillCatalogue } from "@/modules/capabilities/forms";
import { employeeProfileService, employeeSkillService } from "@/modules/employees/employee-services";

export const dynamic = "force-dynamic";
export default async function SkillsPage({ searchParams }: { searchParams: Promise<{ skill?: string; employee?: string }> }) {
  const actor = await getCurrentActor(); if (!actor) redirect("/login"); const params = await searchParams;
  if (actor.role === "EMPLOYEE") { const records = await employeeSkillService.listForEmployee(actor, actor.id); return <section className="operations-page"><header className="operations-heading"><div><p className="eyebrow">Employee self-service</p><h2>My recorded skills</h2><p>These are management-recorded skill facts. You cannot add free-text skills or change qualification records.</p></div></header><section className="operation-panel"><h3>Recorded skills</h3>{records.length ? <ul className="operation-list">{records.map(({ association, skill }) => <li key={association.id}><div><strong>{skill.name}</strong><span>Recorded skill</span></div></li>)}</ul> : <p className="operation-empty">No skills have been recorded on your profile.</p>}</section></section>; }
  const planner = await capabilityService.plannerCandidates(actor, { skillId: params.skill || undefined });
  if (actor.role === "ADMIN") return <section className="operations-page"><header className="operations-heading"><div><p className="eyebrow">Scoped planning</p><h2>Skill filter</h2><p>Results contain only Employees in your explicit TEAM scope. Operational scope never expands skill visibility.</p></div></header><form className="operation-form compact" method="get"><label>Recorded skill<select name="skill" defaultValue={params.skill ?? ""}><option value="">Choose an active skill</option>{planner.skills.map((skill) => <option key={skill.id} value={skill.id}>{skill.name}</option>)}</select></label><button className="button primary">Filter Employees</button></form><section className="operation-panel"><h3>{planner.selectedSkill ? `Employees with ${planner.selectedSkill.name}` : "Choose a skill"}</h3>{planner.selectedSkill ? planner.candidates.length ? <ul className="operation-list">{planner.candidates.map((candidate) => <li key={candidate.id}><div><strong>{candidate.displayName}</strong><span>Recorded skill · TEAM-visible planning projection</span></div></li>)}</ul> : <p className="operation-empty">No TEAM-visible Employee has this recorded skill.</p> : <p className="operation-empty">No employee directory is exposed until an active skill is selected.</p>}</section></section>;
  const [catalogue, activePlanner, directory] = await Promise.all([capabilityService.catalogue(actor), capabilityService.plannerCandidates(actor, {}), employeeProfileService.listDirectoryProfiles(actor, { active: true })]); const selectedEmployeeId = params.employee && directory.items.some((profile) => profile.userId === params.employee) ? params.employee : undefined; const records = selectedEmployeeId ? await employeeSkillService.listForEmployee(actor, selectedEmployeeId) : [];
  return <section className="operations-page"><header className="operations-heading"><div><p className="eyebrow">Phase 6 capability management</p><h2>Skills and operational capability facts</h2><p>Recorded skills support transparent planning warnings. They do not create coverage, ranking, certification, or performance conclusions.</p></div></header><div className="operation-columns"><SkillCatalogue skills={catalogue} /><EmployeeSkillManager employees={directory.items.map((profile) => ({ id: profile.userId, displayName: profile.user.displayName }))} skills={activePlanner.skills} selectedEmployeeId={selectedEmployeeId} records={records} /></div><section className="operation-panel"><h3>Review an Employee</h3><form method="get"><label>Employee<select name="employee" defaultValue={selectedEmployeeId ?? ""}><option value="">Choose Employee</option>{directory.items.map((profile) => <option key={profile.userId} value={profile.userId}>{profile.user.displayName}</option>)}</select></label><button className="button">Review recorded skills</button></form></section></section>;
}
