"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Brand } from "@/shared/components/brand";

const personas = [
  ["mock-super-admin-nora", "Nora Albright", "Super Admin", "Global foundation access"], ["mock-admin-ava", "Ava Mercer", "Admin", "Mock Team Alpha scope"], ["mock-admin-ben", "Ben Iqbal", "Admin", "Mock Team Bravo scope"], ["mock-employee-cora", "Cora Bell", "Employee", "Mock Team Alpha association"], ["mock-employee-dan", "Dan Rowan", "Employee", "Mock Team Bravo association"],
] as const;
export function LoginScreen() { const router = useRouter(); const [selected, setSelected] = useState<string>(personas[0][0]); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); async function signIn() { setPending(true); setError(null); const response = await fetch("/api/auth/mock-login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ personaId: selected }) }); const payload = await response.json(); if (!response.ok) { setError(payload.message ?? "Unable to start a mock session."); setPending(false); return; } router.push(payload.redirectTo); router.refresh(); }
  return <main className="login-page"><section className="login-card"><Brand /><p className="eyebrow">Development and test environment</p><h1>Team Management System</h1><p className="intro">Select a fictional persona to test the real server-side access boundaries.</p><div className="mock-callout"><strong>Mock authentication</strong><span>No passwords, tokens, or real employee data are used.</span></div><fieldset><legend>Choose a test persona</legend><div className="persona-list">{personas.map(([id, name, role, scope]) => <label key={id} className={`persona-option ${selected === id ? "selected" : ""}`}><input type="radio" name="persona" value={id} checked={selected === id} onChange={() => setSelected(id)} /><span><strong>{name}</strong><small>{role} · {scope}</small></span></label>)}</div></fieldset>{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary login-submit" type="button" disabled={pending} onClick={signIn}>{pending ? "Starting session…" : "Continue with mock persona"}</button></section></main>; }
