import Link from "next/link";
import { displayDate } from "@/modules/scheduling/calendar-dates";
import { WorkflowFeedback } from "@/shared/components/workflow-feedback";
import { notFound } from "next/navigation";
import { getCurrentActor } from "@/modules/auth/session-service";
import { AllowanceForm, CancelLeaveForm, LeaveDecisionForm, LeaveRequestForm } from "@/modules/leave/forms";
import { leaveService, LEAVE_TIMEZONE } from "@/modules/leave/service";
import { LeaveDomainError } from "@/modules/leave/domain-error";
import { TaskDialog } from "@/shared/components/task-dialog";

function Balance({ balance }: { balance: { year: number; allowance: number; used: number; remaining: number } }) {
  return <dl className="leave-balance workflow-balance"><div><dt>Remaining · {balance.year}</dt><dd>{balance.remaining}<span> working days</span></dd></div><div><dt>Approved used</dt><dd>{balance.used}<span> working days</span></dd></div><div><dt>Annual allowance</dt><dd>{balance.allowance}<span> working days</span></dd></div></dl>;
}
export default async function LeavePage({ searchParams }: { searchParams: Promise<{ request?: string }> }) {
  const actor = await getCurrentActor(); if (!actor) return null; const params = await searchParams;
  if (actor.role === "EMPLOYEE") {
    const view = await leaveService.getMyLeave(actor);
    return <section className="operations-page leave-page workflow-page"><WorkflowFeedback /><header className="operations-heading"><div><p className="eyebrow">Your time</p><h2>My leave</h2><p>Plan your time off and follow your requests.</p></div><TaskDialog triggerLabel="Request leave" title="Request annual leave" description="Your request and note are private to you and Super Admin."><LeaveRequestForm /></TaskDialog></header>
      <Balance balance={view.balance} /><p className="workflow-meta">Monday–Friday count toward your allowance. Each {LEAVE_TIMEZONE} calendar year has its own balance.</p>
      <section className="operation-panel"><div className="schedule-panel-heading"><h3>Your leave requests</h3><span className="workflow-count">{view.requests.length}</span></div>{view.requests.length ? <ul className="workflow-leave-list">{view.requests.map((request) => <li key={request.id}><div className="workflow-assignment-heading"><div><h4>{displayDate(request.startDate)} to {displayDate(request.endDate)}</h4><p>{request.requestedWorkingDays} working days</p></div><span className={`workflow-status ${request.status.toLowerCase()}`}>{request.status}</span></div>{request.balances.map((balance) => <p className="workflow-meta" key={balance.year}>{balance.year}: {balance.requestedWorkingDays} requested working days · {request.status === "PENDING" ? "Projected remaining if approved" : "Remaining"}: {balance.projectedRemaining}</p>)}{request.decisionResponse ? <p className="workflow-work-note">Decision response: {request.decisionResponse}</p> : null}{request.status === "PENDING" ? <div className="workflow-row-actions"><CancelLeaveForm id={request.id} version={request.version} /></div> : null}</li>)}</ul> : <div className="workflow-empty"><h4>No requests yet</h4><p>Use Request leave when you are ready to plan time off.</p></div>}</section>
    </section>;
  }
  if (actor.role === "ADMIN") {
    const rows = await leaveService.approvedUnavailabilityForAdmin(actor);
    return <section className="operations-page leave-page workflow-page"><WorkflowFeedback /><header className="operations-heading"><div><p className="eyebrow">Team availability</p><h2>Team leave</h2><p>Approved leave for employees in your team scope. Private reasons and balances are not shown.</p></div><Link className="button" href="/schedule">Open schedule</Link></header><section className="operation-panel"><h3>Upcoming and recorded leave</h3>{rows.length ? <ul className="workflow-leave-list">{rows.map((request) => <li key={`${request.employeeUserId}:${request.startDate}:${request.endDate}`}><div className="workflow-assignment-heading"><div><h4>{request.employeeName}</h4><p>{displayDate(request.startDate)} to {displayDate(request.endDate)}</p></div><span className="workflow-status approved">APPROVED</span></div></li>)}</ul> : <div className="workflow-empty"><h4>No approved leave to show</h4><p>Approved time off for your visible team will appear here.</p></div>}</section></section>;
  }
  const [queue, allowance] = await Promise.all([leaveService.reviewQueue(actor), leaveService.getAllowance(actor)]);
  let selected: Awaited<ReturnType<typeof leaveService.getReview>> | null = null;
  if (params.request) { try { selected = await leaveService.getReview(actor, params.request); } catch (error) { if (error instanceof LeaveDomainError) notFound(); throw error; } }
  return <section className="operations-page leave-page workflow-page"><WorkflowFeedback /><header className="operations-heading"><div><p className="eyebrow">Time-off decisions</p><h2>Leave review queue</h2><p>Review the request, annual balance, and published work before deciding.</p></div><details className="workflow-settings"><summary>Annual allowance settings</summary><AllowanceForm allowance={allowance.annualWorkingDays} version={allowance.version} /></details></header>
    <div className="workflow-review-layout"><section className="operation-panel"><div className="schedule-panel-heading"><h3>Pending requests</h3><span className="workflow-count">{queue.length}</span></div>{queue.length ? <ul className="workflow-queue">{queue.map(({ request, employeeName }) => <li key={request.id}><div><strong>{employeeName}</strong><span>{displayDate(request.startDate)} to {displayDate(request.endDate)}</span></div><Link className="button" aria-current={selected?.request.id === request.id ? "true" : undefined} href={`/leave?request=${request.id}`}>Review</Link></li>)}</ul> : <div className="workflow-empty"><h4>All caught up</h4><p>No leave requests are waiting for your decision.</p></div>}</section>
    {selected ? <section className="operation-panel workflow-leave-review"><div className="schedule-panel-heading"><div><p className="eyebrow">Annual leave request</p><h3>{selected.employeeName ?? "Employee leave request"}</h3></div><span className={`workflow-status ${selected.request.status.toLowerCase()}`}>{selected.request.status}</span></div><p><strong>{displayDate(selected.request.startDate)} to {displayDate(selected.request.endDate)}</strong> · {selected.requestedWorkingDays} working days</p><p className="workflow-work-note">Private reason: {selected.request.privateReason || "No reason provided."}</p>
      {selected.balances.map((balance) => <section className="workflow-year" key={balance.year}><h4>Calendar year {balance.year}</h4><Balance balance={balance} /><p>{balance.requestedWorkingDays} requested working days · {selected.request.status === "PENDING" ? "Projected remaining if approved" : "Remaining"}: {balance.projectedRemaining}</p></section>)}
      <section className="workflow-impact"><h4>Published schedule impact</h4>{selected.publishedImpact.length ? <><p className="operation-error">{selected.publishedImpact.length} assignment(s) overlap. Revise and publish the schedule changes before approving this leave.</p><ul className="workflow-queue">{selected.publishedImpact.map((impact) => <li key={impact.id}><div><strong>{impact.assignmentDate} · {impact.startTime.slice(0, 5)}–{impact.endTime.slice(0, 5)}</strong><span>{impact.clientName} · {impact.projectName} · {impact.locationName}</span></div><Link className="button" href={`/schedule?month=${impact.assignmentDate.slice(0, 7)}&period=${impact.periodId}`}>View schedule</Link></li>)}</ul></> : <p className="operation-success">No published work conflicts with these dates.</p>}</section>
      {selected.request.status === "PENDING" ? <LeaveDecisionForm id={selected.request.id} version={selected.request.version} approvalBlocked={selected.publishedImpact.length > 0} /> : <p className="workflow-inline-note">This request has already been {selected.request.status.toLowerCase()}.{selected.request.decisionResponse ? ` Response: ${selected.request.decisionResponse}` : ""}</p>}
    </section> : <section className="workflow-empty workflow-select-empty"><h3>Select a request</h3><p>Choose Review to see the employee’s note, balance, and any schedule conflicts.</p></section>}</div>
  </section>;
}
