import Link from "next/link";
import { getCurrentActor } from "@/modules/auth/session-service";
import { AllowanceForm, CancelLeaveForm, LeaveDecisionForm, LeaveRequestForm } from "@/modules/leave/forms";
import { leaveService, LEAVE_TIMEZONE } from "@/modules/leave/service";
function Balance({ balance }: { balance: { year: number; allowance: number; used: number; remaining: number } }) { return <dl className="leave-balance"><div><dt>Annual allowance</dt><dd>{balance.allowance} working days</dd></div><div><dt>Approved used · {balance.year}</dt><dd>{balance.used} working days</dd></div><div><dt>Remaining</dt><dd>{balance.remaining} working days</dd></div></dl>; }
export default async function LeavePage({ searchParams }: { searchParams: Promise<{ request?: string }> }) { const actor = await getCurrentActor(); if (!actor) return null; const params = await searchParams;
  if (actor.role === "EMPLOYEE") { const view = await leaveService.getMyLeave(actor); return <section className="operations-page leave-page"><header className="operations-heading"><div><p className="eyebrow">Employee self-service</p><h2>My Leave</h2><p>Annual leave uses the {LEAVE_TIMEZONE} calendar year and a provisional Monday–Friday working-day rule.</p></div></header><Balance balance={view.balance} /><LeaveRequestForm /><section className="operation-panel"><h3>Your leave requests</h3>{view.requests.length ? <ul className="operation-list">{view.requests.map((request) => <li key={request.id}><div><strong>{request.startDate} to {request.endDate}</strong><span>{request.status} · Requested: {request.requestedWorkingDays} working days · Projected remaining if approved: {request.projectedRemaining}</span>{request.decisionResponse ? <span>Decision response: {request.decisionResponse}</span> : null}</div>{request.status === "PENDING" ? <CancelLeaveForm id={request.id} version={request.version} /> : null}</li>)}</ul> : <p className="operation-empty">No leave requests yet.</p>}</section></section>; }
  if (actor.role === "ADMIN") { const rows = await leaveService.approvedUnavailabilityForAdmin(actor); return <section className="operations-page leave-page"><header className="operations-heading"><div><p className="eyebrow">Scoped availability</p><h2>Approved unavailability</h2><p>Only approved dates for Employees in your explicit TEAM scope are shown. Reasons, balances, decisions, and requests awaiting review are private.</p></div></header><section className="operation-panel"><h3>Visible approved leave</h3>{rows.length ? <ul className="operation-list">{rows.map((request) => <li key={`${request.employeeUserId}:${request.startDate}:${request.endDate}`}><div><strong>{request.employeeName}</strong><span>Unavailable {request.startDate} to {request.endDate} · APPROVED</span></div></li>)}</ul> : <p className="operation-empty">No approved unavailability is visible in your TEAM scope.</p>}</section></section>; }
  const [queue, allowance] = await Promise.all([leaveService.reviewQueue(actor), leaveService.getAllowance(actor)]); const selected = params.request ? await leaveService.getReview(actor, params.request) : null;
  return <section className="operations-page leave-page"><header className="operations-heading"><div><p className="eyebrow">Phase 5 leave review</p><h2>Leave review queue</h2><p>Review private leave details, balance, and schedule impact before deciding. Published schedule conflicts must be revised first.</p></div></header><div className="operation-columns"><div><AllowanceForm allowance={allowance.annualWorkingDays} version={allowance.version} /><section className="operation-panel"><h3>Pending requests</h3>{queue.length ? <ul className="operation-list">{queue.map(({ request, employeeName }) => <li key={request.id}><div><strong>{employeeName}</strong><span>{request.startDate} to {request.endDate}</span></div><Link className="button" href={`/leave?request=${request.id}`}>Review</Link></li>)}</ul> : <p className="operation-empty">No Pending leave requests.</p>}</section></div>{selected ? <section className="operation-panel"><h3>{selected.request.startDate} to {selected.request.endDate}</h3><p>Employee: <strong>{selected.request.employeeUserId}</strong></p><p>Private reason: {selected.request.privateReason || "No reason provided."}</p><p>Requested: {selected.requestedWorkingDays} working days · Projected remaining: {selected.projectedRemaining}</p><Balance balance={selected.balance} /><h4>Current Published schedule impact</h4>{selected.publishedImpact.length ? <><p className="operation-error">{selected.publishedImpact.length} current Published assignment(s) overlap. Approval is blocked until the Phase 4 revision workflow resolves them.</p><ul className="operation-list">{selected.publishedImpact.map((impact) => <li key={impact.id}><div><strong>{impact.assignmentDate} · {impact.startTime}–{impact.endTime}</strong><span>{impact.clientName} · {impact.projectName} · {impact.locationName}</span></div></li>)}</ul></> : <p className="operation-success">No current Published assignment overlaps this request.</p>}<LeaveDecisionForm id={selected.request.id} version={selected.request.version} /></section> : <section className="operation-empty"><h3>Select a request</h3><p>Private reasons and review controls appear only to Super Admin.</p></section>}</div></section>; }
