import { expect, test } from "@playwright/test";
import { phase3Ids } from "../../scripts/phase3-test-fixtures.mjs";

test.skip(process.env.SCOPEIS_PHASE3_E2E !== "true", "Run with the guarded Phase 3 fixture runner.");

async function signIn(page: import("@playwright/test").Page, name: string) { await page.goto("/login"); await page.getByText(name, { exact: true }).click(); await page.getByRole("button", { name: "Continue with mock persona" }).click(); await expect(page).toHaveURL(/\/dashboard$/); }
async function signOut(page: import("@playwright/test").Page) { await page.request.post("/api/auth/logout", { headers: { Origin: new URL(page.url()).origin } }); }
async function selectOptionContaining(select: import("@playwright/test").Locator, text: string) {
  const value = await select.locator("option").filter({ hasText: text }).getAttribute("value");
  if (!value) throw new Error(`No option contained: ${text}`);
  await select.selectOption(value);
}
async function createClientJourney(page: import("@playwright/test").Page, suffix: string) {
  const company = `Journey Client ${suffix}`; await page.goto("/clients"); const create = page.getByRole("form", { name: "Create Client" }); await create.getByLabel("Company name").fill(company); await create.getByLabel("Account Manager").selectOption("mock-admin-ava"); await create.getByLabel("Service summary").fill("Fictional Phase 3 browser journey"); await create.getByRole("button", { name: "Create Client" }).click(); await expect(create.getByText("Client created.")).toBeVisible();
  const card = page.locator("article").filter({ hasText: company }); await card.getByRole("link", { name: "Manage Client" }).click(); return { company, clientUrl: page.url() };
}

test("Super Admin creates Client → Projects → new Location and deliberately reuses it", async ({ page }, testInfo) => {
  await signIn(page, "Nora Albright"); const suffix = `${testInfo.project.name}-${Date.now()}`; await createClientJourney(page, suffix);
  const projectOne = `Primary ${suffix}`; const projectTwo = `Reuse ${suffix}`; const locationName = `Shared Site ${suffix}`;
  const projectForm = page.getByRole("form", { name: "Create Project under this Client" }); await projectForm.getByLabel("Project name").fill(projectOne); await projectForm.getByLabel("Responsible Admin").selectOption("mock-admin-ava"); await projectForm.getByRole("button", { name: "Create Project" }).click(); await expect(projectForm.getByText("Project created.")).toBeVisible();
  await projectForm.getByLabel("Project name").fill(projectTwo); await projectForm.getByRole("button", { name: "Create Project" }).click(); await expect(page.locator("article").filter({ hasText: projectTwo })).toBeVisible();
  const locationForm = page.getByRole("form", { name: "Create a separate Location" }); await locationForm.getByLabel("Location name").fill(locationName); await locationForm.getByLabel("Full operational address").fill("88 Fictional Browser Street"); await locationForm.getByLabel(/Latitude/).fill("25.2048"); await locationForm.getByLabel(/Longitude/).fill("55.2708"); await locationForm.getByRole("button", { name: "Create Location" }).click(); await expect(locationForm.getByText("Location created. It was not linked automatically.")).toBeVisible();
  await page.locator("article").filter({ hasText: projectOne }).getByRole("link", { name: "Manage Project" }).click(); const link = page.getByRole("form", { name: "Link an existing same-client Location" }); await selectOptionContaining(link.getByLabel("Location"), locationName); await link.getByRole("button", { name: "Link Location" }).click(); await expect(link.getByText("Location linked deliberately")).toBeVisible();
  await page.goto(new URL("/clients", page.url()).toString()); await page.locator("article").filter({ hasText: `Journey Client ${suffix}` }).getByRole("link", { name: "Manage Client" }).click(); await page.locator("article").filter({ hasText: projectTwo }).getByRole("link", { name: "Manage Project" }).click(); const reuse = page.getByRole("form", { name: "Link an existing same-client Location" }); await selectOptionContaining(reuse.getByLabel("Location"), locationName); await reuse.getByRole("button", { name: "Link Location" }).click(); await expect(reuse.getByText("Location linked deliberately")).toBeVisible(); await expect(page.getByText("This relationship is operational structure, not a schedule assignment.")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); await signOut(page);
});

test("Client-scoped Admin manages descendants while relationship-only and unscoped Admins remain denied", async ({ page }, testInfo) => {
  await signIn(page, "Ava Mercer"); await page.goto(`/clients/${phase3Ids.alphaClient}`); await expect(page.getByRole("heading", { name: "Alpha Facilities" })).toBeVisible(); const form = page.getByRole("form", { name: "Create Project under this Client" }); await form.getByLabel("Project name").fill(`Ava descendant ${testInfo.project.name}`); await form.getByRole("button", { name: "Create Project" }).click(); await expect(form.getByText("Project created.")).toBeVisible(); expect((await page.goto(`/clients/${phase3Ids.bravoClient}`))?.status()).toBe(404); await signOut(page);
  await signIn(page, "Dan Rowan"); await page.goto("/clients"); await expect(page.getByRole("heading", { name: "No authorized Clients" })).toBeVisible(); expect((await page.goto(`/clients/${phase3Ids.implicitClient}`))?.status()).toBe(404); expect((await page.goto(`/projects/${phase3Ids.implicitProject}`))?.status()).toBe(404); expect((await page.goto(`/locations/${phase3Ids.implicitLocation}`))?.status()).toBe(404); await signOut(page);
});

test("Project and Location scopes never climb upward or reach siblings", async ({ page }) => {
  await signIn(page, "Ben Iqbal"); await page.goto(`/projects/${phase3Ids.bravoProject}`); await expect(page.getByRole("heading", { name: "Bravo Scoped Project" })).toBeVisible(); expect((await page.goto(`/projects/${phase3Ids.bravoSibling}`))?.status()).toBe(404); expect((await page.goto(`/clients/${phase3Ids.bravoClient}`))?.status()).toBe(404);
  await page.goto(`/locations/${phase3Ids.gammaLocation}`); await expect(page.getByRole("heading", { name: "Gamma Scoped Location" })).toBeVisible(); expect((await page.goto(`/clients/${phase3Ids.gammaClient}`))?.status()).toBe(404); expect((await page.goto(`/projects/${phase3Ids.gammaProject}`))?.status()).toBe(404); await signOut(page);
});

test("Employee has no Phase 3 navigation, pages, or sensitive operational projection", async ({ page }) => {
  await signIn(page, "Cora Bell"); await expect(page.getByRole("link", { name: "Clients" })).toHaveCount(0); await expect(page.getByRole("link", { name: "Projects" })).toHaveCount(0); for (const path of ["/clients", "/projects", "/locations", `/locations/${phase3Ids.alphaLocation}`]) expect((await page.goto(path))?.status()).toBe(404); await expect(page.getByText("Alpha Operations Desk", { exact: true })).toHaveCount(0); await expect(page.getByText("Report to fictional reception", { exact: true })).toHaveCount(0); await signOut(page);
});

test("archive safeguards and stale submissions fail with understandable state", async ({ page, context }, testInfo) => {
  await signIn(page, "Nora Albright"); const suffix = `Guard-${testInfo.project.name}-${Date.now()}`; await createClientJourney(page, suffix); const projectForm = page.getByRole("form", { name: "Create Project under this Client" }); await projectForm.getByLabel("Project name").fill(`Active ${suffix}`); await projectForm.getByRole("button", { name: "Create Project" }).click(); const lifecycle = page.getByRole("form", { name: "Client lifecycle" }); page.once("dialog", (dialog) => dialog.accept()); await lifecycle.getByRole("button", { name: "Archive Client" }).click(); await expect(lifecycle.getByText(/Complete or archive every active project/)).toBeVisible();
  const projectLink = page.locator("article").filter({ hasText: `Active ${suffix}` }).getByRole("link", { name: "Manage Project" }); const projectPath = await projectLink.getAttribute("href"); if (!projectPath) throw new Error("Created Project link is missing its destination."); await page.goto(projectPath); await expect(page).toHaveURL(/\/projects\//); const staleUrl = page.url(); const second = await context.newPage(); await second.goto(staleUrl); const staleForm = second.getByRole("form", { name: "Project details" }); await expect(staleForm).toBeVisible(); await staleForm.getByLabel("Project name").fill(`Stale ${suffix}`); const firstForm = page.getByRole("form", { name: "Project details" }); await firstForm.getByLabel("Project name").fill(`Updated ${suffix}`); await firstForm.getByRole("button", { name: "Save" }).click(); await expect(firstForm.getByText("Project saved.")).toBeVisible(); await staleForm.getByRole("button", { name: "Save" }).click(); await expect(staleForm.getByText("This record changed. Reload and try again.")).toBeVisible(); await second.close(); await signOut(page);
});

test("cross-client and invalid coordinate submissions cannot create hidden relationships", async ({ page }, testInfo) => {
  await signIn(page, "Nora Albright"); const suffix = `Invalid-${testInfo.project.name}-${Date.now()}`; await createClientJourney(page, suffix); const projectForm = page.getByRole("form", { name: "Create Project under this Client" }); await projectForm.getByLabel("Project name").fill(`Boundary ${suffix}`); await projectForm.getByRole("button", { name: "Create Project" }).click(); const locationForm = page.getByRole("form", { name: "Create a separate Location" }); await locationForm.getByLabel("Location name").fill(`Invalid coordinate ${suffix}`); await locationForm.getByLabel("Full operational address").fill("Browser validation road"); await locationForm.getByLabel(/Latitude/).fill("91"); await locationForm.getByLabel(/Longitude/).fill("10"); await locationForm.getByRole("button", { name: "Create Location" }).click(); await expect(locationForm.getByText("Location created. It was not linked automatically.")).toHaveCount(0);
  await page.locator("article").filter({ hasText: `Boundary ${suffix}` }).getByRole("link", { name: "Manage Project" }).click(); const select = page.getByRole("form", { name: "Link an existing same-client Location" }).getByLabel("Location"); await select.evaluate((element, value) => { const option = document.createElement("option"); option.value = String(value); option.textContent = "Injected cross-client Location"; element.append(option); }, phase3Ids.gammaLocation); await select.selectOption(phase3Ids.gammaLocation); await page.getByRole("form", { name: "Link an existing same-client Location" }).getByRole("button", { name: "Link Location" }).click(); await expect(page.getByText("The selected records cannot be related.")).toBeVisible(); await signOut(page);
});

test("Super Admin scope control is explicit and separate from Account Manager", async ({ page }, testInfo) => {
  await signIn(page, "Nora Albright"); const suffix = `Grant-${testInfo.project.name}-${Date.now()}`; await createClientJourney(page, suffix); const scope = page.getByRole("form", { name: "Grant CLIENT scope" }); await scope.getByLabel("Active Admin").selectOption("mock-admin-ben"); await scope.getByRole("button", { name: "Grant scope" }).click(); await expect(scope.getByText("Explicit operational scope granted.")).toBeVisible(); await expect(page.getByRole("strong").filter({ hasText: "Ben Iqbal" })).toBeVisible(); await signOut(page);
});
