"use client";

import Link from "next/link";
import dynamic from "next/dynamic";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Suspense, useEffect, useMemo, useState } from "react";
import {
  assignments, auditEvents, clients, coverageGaps, dashboardCounts, employeeFor, employees, fixtureCounts, inScope, leaveRequests, locations,
  notes, notifications, personas, previewConfig, projects, replacements, selectedPersona, type PreviewPersona,
  visibleAssignments, visibleDiscussions, visibleEmployees, visibleLeave, visibleNotes,
} from "@/preview/preview-data";
import { visiblePreviewRoutes } from "@/preview/preview-routes";

const InteractivePlanningMap = dynamic(
  () => import("@/preview/interactive-planning-map").then((module) => module.InteractivePlanningMap),
  { ssr: false, loading: () => <p className="demo-callout">Loading the fictional planning canvas…</p> },
);


function friendlyRole(role: PreviewPersona["role"]) { return role === "SUPER_ADMIN" ? "Super Admin" : role === "ADMIN" ? "Admin" : "Employee"; }
function subjectName(id: string) { return employeeFor(id)?.name ?? "Unknown fictional record"; }
function clientName(id: string) { return clients.find((client) => client.id === id)?.name ?? "Fictional client"; }
function href(path: string, persona: PreviewPersona) { return `${path}?persona=${persona.id}`; }

export function PreviewApp() { return <Suspense fallback={<main className="login-page"><p className="preview-notice">Loading fictional Preview…</p></main>}><PreviewAppContent /></Suspense>; }

function PreviewAppContent() {
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const router = useRouter();
  const persona = selectedPersona(searchParams.get("persona"));
  const [theme, setTheme] = useState<"light" | "dark">("light");
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  if (pathname === "/login" || pathname === "/") return <Login persona={persona} choose={(id) => router.push(`/dashboard?persona=${id}`)} />;

  const links = visiblePreviewRoutes(persona).filter((item) => item.href !== "/tickets");
  return <div className="preview-app">
    <a className="skip-link" href="#preview-content">Skip to content</a>
    <aside className={`preview-sidebar ${menuOpen ? "is-open" : ""}`} aria-label="Preview navigation">
      <div className="preview-brand"><span className="brand-mark">S</span><span><strong>ScopeIs</strong><small>Team Management</small></span></div>
      <p className="preview-notice">{previewConfig.label}</p>
      <nav>{links.map((item) => <Link key={item.href} href={href(item.href, persona)} aria-current={pathname === item.href ? "page" : undefined} onClick={() => setMenuOpen(false)}>{item.label}</Link>)}
        <span className="ticket-link" aria-disabled="true">Ticket System <small>Later / deferred</small></span>
      </nav>
      <div className="sidebar-persona"><span className="avatar">{persona.name.split(" ").map((part) => part[0]).join("")}</span><span><strong>{persona.name}</strong><small>{friendlyRole(persona.role)}{persona.team ? ` · Team ${persona.team === "alpha" ? "Alpha" : "Bravo"}` : " · Global"}</small></span></div>
    </aside>
    <div className="preview-workspace">
      <header className="preview-header"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)}>☰</button><div><strong>ScopeIs Preview</strong><small>{previewConfig.date}</small></div><div className="header-tools"><label className="persona-select"><span className="visually-hidden">Preview persona</span><select aria-label="Preview persona" value={persona.id} onChange={(event) => router.push(href(pathname, selectedPersona(event.target.value)))}>{personas.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name} — {friendlyRole(candidate.role)}</option>)}</select></label><button className="icon-button" aria-label={`Use ${theme === "light" ? "dark" : "light"} theme`} onClick={() => setTheme(theme === "light" ? "dark" : "light")}>{theme === "light" ? "◐" : "☼"}</button><Link className="logout-link" href="/login">Change persona</Link></div></header>
      <main id="preview-content" className="preview-content"><PageContent pathname={pathname} persona={persona} /></main>
    </div>
  </div>;
}

function Login({ persona, choose }: { persona: PreviewPersona; choose: (id: PreviewPersona["id"]) => void }) {
  return <main className="login-page"><section className="login-card"><span className="brand-mark large">S</span><p className="eyebrow">ScopeIs Preview</p><h1>Explore the workforce planning demonstration</h1><p className="lead">This is a complete frontend demonstration using fictional records. It is not authenticated, connected to a database, or persistent.</p><p className="preview-notice prominent">{previewConfig.label}</p><fieldset><legend>Select a fictional persona</legend><div className="persona-grid">{personas.map((candidate) => <button key={candidate.id} type="button" className={candidate.id === persona.id ? "persona-card selected" : "persona-card"} onClick={() => choose(candidate.id)}><span className="avatar">{candidate.name.split(" ").map((part) => part[0]).join("")}</span><strong>{candidate.name}</strong><small>{candidate.summary}</small></button>)}</div></fieldset><p className="footnote">Role views illustrate product rules. They are not a production security boundary.</p></section></main>;
}

function PageContent({ pathname, persona }: { pathname: string; persona: PreviewPersona }) {
  const segment = pathname.split("/")[1] || "dashboard";
  if (segment === "employees" && pathname.split("/").length > 2) return <EmployeeDetail persona={persona} id={pathname.split("/")[2]} />;
  if (["clients", "projects", "locations"].includes(segment) && pathname.split("/").length > 2) return <RecordDetail persona={persona} type={segment} id={pathname.split("/")[2]} />;
  switch (segment) {
    case "dashboard": return <Dashboard persona={persona} />;
    case "employees": return <EmployeeDirectory persona={persona} />;
    case "profile": return <Profile persona={persona} />;
    case "clients": return <Directory persona={persona} title="Clients" description="Fictional client relationships, contacts, and delivery status." records={inScope(clients, persona)} hrefBase="/clients" fields={(record) => [record.contact, record.location, `${record.projects} project${record.projects === 1 ? "" : "s"}`, record.status]} />;
    case "projects": return <Directory persona={persona} title="Projects" description="Fictional project delivery, staffing requirements, and linked locations." records={inScope(projects, persona)} hrefBase="/projects" fields={(record) => [clientName(record.clientId), record.location, record.stage, record.staffing]} />;
    case "locations": return <Directory persona={persona} title="Locations" description="Operational locations shown as fictional planning records, not live places." records={inScope(locations, persona)} hrefBase="/locations" fields={(record) => [record.client, record.city, record.type]} />;
    case "schedule": return <Schedule persona={persona} />;
    case "leave": return <Leave persona={persona} />;
    case "coverage": return <Coverage persona={persona} />;
    case "replacements": return <Replacements persona={persona} />;
    case "map": return <PlanningMap persona={persona} />;
    case "skills": return <Skills persona={persona} />;
    case "evidence": return <Evidence persona={persona} />;
    case "requests": return <Requests persona={persona} />;
    case "notes": return <Notes persona={persona} management={false} />;
    case "management-notes": return <Notes persona={persona} management />;
    case "discussions": return <Discussions persona={persona} />;
    case "notifications": return <Notifications persona={persona} />;
    case "reports": return <Reports persona={persona} />;
    case "audit": return <Audit persona={persona} />;
    case "settings": return <Settings persona={persona} />;
    case "tickets": return <TicketDeferred />;
    default: return <NotAuthorized />;
  }
}

function PageHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <header className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{children}</p></div></header>; }
function DemoAction({ children }: { children: React.ReactNode }) { return <button className="button secondary" disabled title="Frontend demonstration only — no change is stored">{children}</button>; }
function Pill({ children, kind = "neutral" }: { children: React.ReactNode; kind?: "neutral" | "good" | "warning" | "danger" }) { return <span className={`pill ${kind}`}>{children}</span>; }
function Notice({ children }: { children: React.ReactNode }) { return <p className="demo-callout">{children}</p>; }
function leaveDisplayReason(request: Record<string, unknown>, persona: PreviewPersona) { return typeof request.reason === "string" && persona.role !== "ADMIN" ? request.reason : typeof request.visibleReason === "string" ? request.visibleReason : "Private reason"; }

function Dashboard({ persona }: { persona: PreviewPersona }) {
  const scopedAssignments = visibleAssignments(persona); const counts = dashboardCounts(persona);
  return <><PageHeading eyebrow="Overview" title={`${persona.name.split(" ")[0]}'s dashboard`}>Role-aware fixture data for {persona.role === "SUPER_ADMIN" ? "both teams" : persona.role === "ADMIN" ? `Team ${persona.team === "alpha" ? "Alpha" : "Bravo"}` : "your published work"}.</PageHeading><Notice>{previewConfig.label}. Counts reconcile with the fixtures shown in this Preview.</Notice><section className="metric-grid"><Metric label="Visible employees" value={String(counts.employees)} note={persona.role === "SUPER_ADMIN" ? "18 across two teams" : "filtered by role and scope"} /><Metric label="Published assignments" value={String(counts.publishedAssignments)} note="September 2026" /><Metric label="Leave items" value={String(counts.leave)} note={persona.role === "EMPLOYEE" ? "your leave history" : "privacy-filtered"} /><Metric label="Coverage attention" value={String(counts.coverage)} note="fixture planning findings" /></section><section className="two-column"><Panel title="Today’s planning"><ul className="timeline">{scopedAssignments.slice(0, 4).map((assignment) => <li key={assignment.id}><strong>{subjectName(assignment.employeeId)}</strong><span>{assignment.type} · {assignment.time}</span><small>{assignment.location} · <Pill kind={assignment.state === "Published" ? "good" : "warning"}>{assignment.state}</Pill></small></li>)}</ul></Panel><Panel title="Attention items">{persona.role === "EMPLOYEE" ? <ul className="timeline"><li><strong>Published schedule only</strong><span>Draft and Proposed planning are intentionally not available to Employee views.</span></li><li><strong>Portfolio review</strong><span>Your fictional portfolio update is awaiting review.</span></li></ul> : <ul className="timeline">{inScope(coverageGaps, persona).map((gap) => <li key={gap.id}><strong>{gap.title}</strong><span>{gap.skill} · {gap.date}</span><small>{gap.reason}</small></li>)}</ul>}</Panel></section><Panel title="Demonstration controls"><div className="button-row">{persona.role === "SUPER_ADMIN" ? <><DemoAction>Publish schedule</DemoAction><DemoAction>Approve leave</DemoAction><DemoAction>Override warning</DemoAction></> : <DemoAction>Open workflow preview</DemoAction>}<span className="muted">Actions are intentionally disabled; this demo never stores a result.</span></div></Panel></>;
}
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="metric"><small>{label}</small><strong>{value}</strong><span>{note}</span></article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><h2>{title}</h2>{children}</section>; }

function EmployeeDirectory({ persona }: { persona: PreviewPersona }) {
  const [query, setQuery] = useState(""); const records = useMemo(() => visibleEmployees(persona).filter((employee) => `${employee.name} ${employee.designation} ${employee.skills.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [persona, query]);
  if (persona.role === "EMPLOYEE") return <Profile persona={persona} />;
  return <><PageHeading eyebrow="Workforce" title="Employees & capabilities">{persona.role === "SUPER_ADMIN" ? "Global fictional workforce directory." : `Only Team ${persona.team === "alpha" ? "Alpha" : "Bravo"} records are visible.`}</PageHeading><div className="filter-bar"><label>Search employees<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, role, or skill" /></label><span>{records.length} fictional records</span><DemoAction>Add employee</DemoAction></div><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Designation</th><th>Team</th><th>Skills</th><th>Availability</th><th /></tr></thead><tbody>{records.map((employee) => <tr key={employee.id}><th><span className="row-person"><span className="avatar">{employee.initials}</span><span><strong>{employee.name}</strong><small>{employee.workingPattern}</small></span></span></th><td>{employee.designation}</td><td>Team {employee.team === "alpha" ? "Alpha" : "Bravo"}</td><td>{employee.skills.slice(0, 2).join(" · ")}</td><td><Pill kind={employee.availability === "On leave" ? "warning" : employee.availability === "Available" ? "good" : "neutral"}>{employee.availability}</Pill></td><td><Link className="text-link" href={href(`/employees/${employee.id}`, persona)}>View</Link></td></tr>)}</tbody></table></div></>;
}
function EmployeeDetail({ persona, id, embedded = false }: { persona: PreviewPersona; id: string; embedded?: boolean }) { const employee = employeeFor(id); if (!employee || !visibleEmployees(persona).some((record) => record.id === id)) return <NotAuthorized />; const manager = employee.managerId ? employeeFor(employee.managerId) : undefined; return <>{!embedded ? <PageHeading eyebrow="Employee profile" title={employee.name}>{employee.designation} · Team {employee.team === "alpha" ? "Alpha" : "Bravo"}</PageHeading> : null}<section className="profile-hero"><span className="avatar large-avatar">{employee.initials}</span><div><h2>{employee.designation}</h2><p>{employee.summary}</p><div className="pills">{employee.skills.map((skill) => <Pill key={skill}>{skill}</Pill>)}</div></div><Pill kind={employee.availability === "On leave" ? "warning" : "good"}>{employee.availability}</Pill></section><section className="two-column"><Panel title="Professional information"><dl className="detail-list"><div><dt>Manager</dt><dd>{manager?.name ?? "Global oversight"}</dd></div><div><dt>Working pattern</dt><dd>{employee.workingPattern}</dd></div><div><dt>Fictional contact</dt><dd>{employee.email}<br />{employee.phone}</dd></div><div><dt>Certification</dt><dd>{employee.certification}{employee.certificationExpires ? ` · expires ${employee.certificationExpires}` : ""}</dd></div></dl></Panel><Panel title="September schedule"><AssignmentList items={visibleAssignments({ ...persona, employeeId: employee.id }).filter((item) => item.employeeId === employee.id)} /></Panel></section>{persona.role === "SUPER_ADMIN" && !embedded ? <Panel title="Management controls"><Notice>These controls illustrate Super Admin authority only. No employee record can be changed from the demonstration.</Notice><div className="button-row"><DemoAction>Edit details</DemoAction><DemoAction>Change role</DemoAction><DemoAction>Deactivate</DemoAction></div></Panel> : null}</> }
function Profile({ persona }: { persona: PreviewPersona }) { const employee = employeeFor(persona.employeeId)!; return <><PageHeading eyebrow="My profile" title="Professional profile">Your fictional profile is read-only in this frontend demonstration.</PageHeading><EmployeeDetail persona={persona} id={employee.id} embedded /><Panel title="Profile changes"><Notice>Work email, phone and professional summary are shown as a workflow preview only.</Notice><div className="form-grid"><label>Work email<input value={employee.email} readOnly /></label><label>Work phone<input value={employee.phone} readOnly /></label></div><DemoAction>Save profile changes</DemoAction></Panel></> }

function Directory<T extends { id: string; name: string }>({ persona, title, description, records, hrefBase, fields }: { persona: PreviewPersona; title: string; description: string; records: T[]; hrefBase: string; fields: (record: T) => string[] }) { if (persona.role === "EMPLOYEE") return <NotAuthorized />; return <><PageHeading eyebrow="Operations" title={title}>{description}</PageHeading><Notice>{records.length} authorized fictional records are visible for this persona.</Notice><div className="cards">{records.map((record) => <article className="record-card" key={record.id}><h2>{record.name}</h2>{fields(record).map((field) => <p key={field}>{field}</p>)}<Link className="text-link" href={href(`${hrefBase}/${record.id}`, persona)}>Open record</Link></article>)}</div></> }
function RecordDetail({ persona, type, id }: { persona: PreviewPersona; type: string; id: string }) { if (persona.role === "EMPLOYEE") return <NotAuthorized />; const source = type === "clients" ? clients : type === "projects" ? projects : locations; const record = source.find((candidate) => candidate.id === id); if (!record || ("team" in record && !inScope([record], persona).length)) return <NotAuthorized />; const linked = type === "clients" ? projects.filter((project) => project.clientId === id).map((project) => project.name) : type === "projects" ? [clientName((record as typeof projects[number]).clientId), (record as typeof projects[number]).location] : [(record as typeof locations[number]).client, "Static local planning marker"]; return <><PageHeading eyebrow={`Operations / ${type.slice(0, -1)}`} title={record.name}>Fictional operational record with consistent links to its fixtures.</PageHeading><Panel title="Record overview"><dl className="detail-list">{linked.map((item, index) => <div key={item}><dt>{index === 0 ? "Related record" : "Planning context"}</dt><dd>{item}</dd></div>)}</dl><div className="button-row"><DemoAction>Edit record</DemoAction><DemoAction>Archive record</DemoAction></div></Panel></> }

function Schedule({ persona }: { persona: PreviewPersona }) { const visible = visibleAssignments(persona); return <><PageHeading eyebrow="Planning" title={persona.role === "EMPLOYEE" ? "My published schedule" : "Schedule"}>{persona.role === "EMPLOYEE" ? "Only your Published assignments are displayed." : "Draft, Proposed and Published fixture assignments for September 2026."}</PageHeading><div className="schedule-tabs"><button className="selected">Month</button><button>Week</button><button>Employee</button><span>{previewConfig.period}</span></div><Panel title="Assignments"><AssignmentList items={visible} /></Panel>{persona.role === "SUPER_ADMIN" ? <Panel title="Publication"><Notice>Only Super Admin views show publication controls. This is a non-persistent workflow demonstration.</Notice><DemoAction>Publish schedule</DemoAction></Panel> : null}</> }
function AssignmentList({ items }: { items: typeof assignments }) { return <ul className="timeline">{items.length ? items.map((assignment) => <li key={assignment.id}><strong>{subjectName(assignment.employeeId)} · {assignment.type}</strong><span>{assignment.date} · {assignment.time} · {assignment.location}</span><small><Pill kind={assignment.state === "Published" ? "good" : "warning"}>{assignment.state}</Pill>{assignment.warning ? ` ${assignment.warning}` : ""}</small></li>) : <li><strong>No published assignment</strong><span>This fictional persona has no visible assignment for the shown period.</span></li>}</ul> }
function Leave({ persona }: { persona: PreviewPersona }) { const records = visibleLeave(persona); return <><PageHeading eyebrow="Availability" title={persona.role === "EMPLOYEE" ? "My leave" : "Leave & availability"}>{persona.role === "EMPLOYEE" ? "Your private leave history is visible only to you." : "Private leave reasons remain hidden from Admin views."}</PageHeading><Panel title="Leave records"><ul className="timeline">{records.map((request) => <li key={request.id}><strong>{persona.role === "EMPLOYEE" ? "My leave" : subjectName(request.employeeId)}</strong><span>{request.dates}</span><small><Pill kind={request.status === "Approved" ? "good" : request.status === "Pending" ? "warning" : "danger"}>{request.status}</Pill> {leaveDisplayReason(request, persona)}</small></li>)}</ul></Panel><div className="button-row"><DemoAction>Submit leave request</DemoAction>{persona.role === "SUPER_ADMIN" ? <><DemoAction>Approve leave</DemoAction><DemoAction>Reject leave</DemoAction></> : null}</div></> }
function Coverage({ persona }: { persona: PreviewPersona }) { if (persona.role === "EMPLOYEE") return <NotAuthorized />; const records = inScope(coverageGaps, persona); return <><PageHeading eyebrow="Planning quality" title="Coverage">Explainable fixture gaps reflect leave, skills, assignments, and scope.</PageHeading><div className="cards">{records.map((gap) => <article className="record-card" key={gap.id}><Pill kind={gap.severity === "High" ? "danger" : "warning"}>{gap.severity}</Pill><h2>{gap.title}</h2><p>{gap.date} · {gap.skill}</p><p>{gap.reason}</p><DemoAction>Request coverage</DemoAction></article>)}</div></> }
function Replacements({ persona }: { persona: PreviewPersona }) { if (persona.role === "EMPLOYEE") return <NotAuthorized />; return <><PageHeading eyebrow="Planning quality" title="Replacements">Candidate explanations use fictional skills and availability; no decision is stored.</PageHeading><div className="cards">{inScope(replacements, persona).map((request) => <article className="record-card" key={request.id}><Pill kind="warning">{request.status}</Pill><h2>{request.title}</h2><p>For {request.requestedFor}</p><p><strong>Candidates:</strong> {request.candidates.join(" · ")}</p><p>{request.rationale}</p>{persona.role === "SUPER_ADMIN" ? <div className="button-row"><DemoAction>Approve replacement</DemoAction><DemoAction>Change candidate</DemoAction></div> : <DemoAction>View candidate workflow</DemoAction>}</article>)}</div></> }
function PlanningMap({ persona }: { persona: PreviewPersona }) { if (persona.role === "EMPLOYEE") return <NotAuthorized />; return <InteractivePlanningMap persona={persona} />; }
function Skills({ persona }: { persona: PreviewPersona }) { if (persona.role === "EMPLOYEE") return <Profile persona={persona} />; const records = visibleEmployees(persona); const skills = Array.from(new Set(records.flatMap((employee) => employee.skills))).sort(); return <><PageHeading eyebrow="Capabilities" title="Skills">Skill coverage shown from the same fictional employee graph used by assignments and coverage.</PageHeading><div className="skill-cloud">{skills.map((skill) => <span key={skill}><strong>{skill}</strong><small>{records.filter((employee) => employee.skills.includes(skill)).length} people</small></span>)}</div></> }
function Evidence({ persona }: { persona: PreviewPersona }) { const records = visibleEmployees(persona); return <><PageHeading eyebrow="Capabilities" title="Certifications, CV & portfolio evidence">Fictional metadata and local presentation only; no files are uploaded, downloaded, or stored.</PageHeading><div className="cards">{records.filter((employee) => employee.certificationExpires).map((employee) => <article className="record-card" key={employee.id}><Pill kind="warning">Expiring</Pill><h2>{employee.name}</h2><p>{employee.certification} · expires {employee.certificationExpires}</p><p>Fictional portfolio update: unreviewed.</p><DemoAction>Preview evidence workflow</DemoAction></article>)}</div></> }
function Requests({ persona }: { persona: PreviewPersona }) { if (persona.role === "EMPLOYEE") return <NotAuthorized />; return <><PageHeading eyebrow="Operations" title="Requests & assignments">Fictional staffing requirements linked to the current project fixture set.</PageHeading><div className="cards">{inScope(projects, persona).map((project) => <article className="record-card" key={project.id}><h2>{project.name}</h2><p>{project.staffing}</p><p>Lead: {subjectName(project.leadId)}</p><DemoAction>Create assignment</DemoAction></article>)}</div></> }
function Notes({ persona, management }: { persona: PreviewPersona; management: boolean }) { const visible = visibleNotes(persona).filter((note) => management ? note.scope !== "Shared" : note.scope === "Shared"); if (management && persona.role === "EMPLOYEE") return <NotAuthorized />; return <><PageHeading eyebrow="Communication" title={management ? "Management notes" : "Shared notes"}>{management ? "Management visibility follows role and team scope in this demonstration." : "Shared fictional client and project notes."}</PageHeading><div className="cards">{visible.map((note) => <article className="record-card" key={note.id}><Pill>{note.scope}</Pill><h2>{note.title}</h2><p>{note.body}</p><small>Author: {note.author}</small><DemoAction>Add note</DemoAction></article>)}</div></> }
function Discussions({ persona }: { persona: PreviewPersona }) { const entries = visibleDiscussions(persona); return <><PageHeading eyebrow="Communication" title="Private discussions">Only participant-appropriate fictional discussion summaries are shown.</PageHeading><Panel title="Discussion threads"><ul className="timeline">{entries.map((entry) => <li key={entry.id}><strong>{entry.title}</strong><span>{entry.summary}</span><small>Participants: {entry.participantIds.map(subjectName).join(" · ")}</small><DemoAction>Open thread</DemoAction></li>)}</ul></Panel></> }
function Notifications({ persona }: { persona: PreviewPersona }) { const records = notifications.filter((notification) => notification.recipientId === persona.employeeId); return <><PageHeading eyebrow="Communication" title="Notifications">Fictional notification state resets on refresh; archive actions are unavailable.</PageHeading><Panel title="Your notifications"><ul className="timeline">{records.length ? records.map((notification) => <li key={notification.id}><strong>{notification.title}</strong><span>{notification.body}</span><small><Pill kind={notification.state === "Unread" ? "warning" : "neutral"}>{notification.state}</Pill></small></li>) : <li><strong>No fictional notifications</strong><span>This persona has no notice assigned in the fixture set.</span></li>}</ul></Panel></> }
function Reports({ persona }: { persona: PreviewPersona }) { if (persona.role !== "SUPER_ADMIN") return <NotAuthorized />; return <><PageHeading eyebrow="Insights" title="Reports">Read-only summaries based on the current fixture graph; exports are unavailable.</PageHeading><section className="metric-grid"><Metric label="Clients" value={String(fixtureCounts.clients)} note="fictional client records" /><Metric label="Projects" value={String(fixtureCounts.projects)} note="linked to clients and locations" /><Metric label="Published work" value={String(fixtureCounts.publishedAssignments)} note="fixture assignments" /><Metric label="Skill gaps" value={String(fixtureCounts.coverage)} note="explainable planning findings" /></section><DemoAction>Export report</DemoAction></> }
function Audit({ persona }: { persona: PreviewPersona }) { if (persona.role !== "SUPER_ADMIN") return <NotAuthorized />; return <><PageHeading eyebrow="Governance" title="Audit">Fictional, read-only event history for the demonstration.</PageHeading><Panel title="Recent events"><ul className="timeline">{auditEvents.map((event) => <li key={event.id}><strong>{event.event}</strong><span>{event.date} · {event.actor}</span><small>{event.detail}</small></li>)}</ul></Panel></> }
function Settings({ persona }: { persona: PreviewPersona }) { if (persona.role !== "SUPER_ADMIN") return <NotAuthorized />; return <><PageHeading eyebrow="Configuration" title="Settings">Global configuration is visible only to illustrate Super Admin scope. Nothing can be changed.</PageHeading><Panel title="Preview configuration"><dl className="detail-list"><div><dt>Data source</dt><dd>Hardcoded TypeScript fixtures</dd></div><div><dt>Persistence</dt><dd>None</dd></div><div><dt>Authentication</dt><dd>Persona presentation only</dd></div><div><dt>Storage</dt><dd>None</dd></div></dl><DemoAction>Save settings</DemoAction></Panel></> }
function TicketDeferred() { return <><PageHeading eyebrow="Later / deferred" title="Ticket System">The Ticket System remains a later, separate integration and is not active in this workforce demonstration.</PageHeading><Notice>No ticket data, APIs, or storage are connected.</Notice></> }
function NotAuthorized() { return <><PageHeading eyebrow="Preview access" title="This view is not available for this persona">The demonstration keeps role, team-scope, and private-information presentation boundaries visible.</PageHeading><Notice>Choose a permitted persona from the header to inspect the appropriate fictional view.</Notice></> }
