import { IconArchive, IconBell, IconDownload, IconMessageCircle, IconPlus, IconSearch, IconShieldLock, IconTicket } from "@tabler/icons-react";
import { useMemo, useState } from "react";
import { Badge, DataTable, DetailList, PageHeader, Status, TabBar } from "../components";
import { useDemo } from "../DemoContext";
import { employees, skillCatalogue } from "../fixtures";
import { AppLink } from "../router";
import type { Persona } from "../types";
import { AccessDeniedPage, NotFoundPage } from "./workforce";

const requests = [
  { id:"REQ-318", title:"Confirm site access window", status:"Clarification needed", requester:"Ava Mercer", assignee:"Cora Bell", related:"Marina Heights · Access Control Upgrade", date:"16 Sep 2026" },
  { id:"REQ-319", title:"Acknowledge on-call assignment", status:"Awaiting response", requester:"Ben Iqbal", assignee:"Dan Rowan", related:"Cedar Finance · Branch Cloud Migration", date:"18 Sep 2026" },
  { id:"REQ-315", title:"Prepare network survey", status:"Acknowledged", requester:"Ava Mercer", assignee:"Rina Santos", related:"Crestline Schools · Wi-Fi survey", date:"14 Sep 2026" },
];

export function RequestsPage({ persona }: { persona: Persona }) {
  const visible = requests.filter((item) => persona.role === "SUPER_ADMIN" || [item.requester,item.assignee].includes(persona.name) || (persona.role === "ADMIN" && item.requester === persona.name));
  return <div className="page"><PageHeader eyebrow="Collaboration" title="Requests & assignments" description="Requests are separate from schedule state, ticket status, and work logs." actions={persona.role !== "EMPLOYEE" ? <button className="button primary"><IconPlus size={17}/>Create request</button> : undefined}/><TabBar tabs={["All","Clarification needed","Awaiting response","Acknowledged"]} current="All" onChange={() => undefined}/><DataTable label="Assignment requests" headers={["Request","Status","Requester","Assigned employee","Related work","Date","Action"]} rows={visible.map((item) => [<span><strong>{item.id}</strong><small className="block-small">{item.title}</small></span>,<Status tone={item.status === "Acknowledged" ? "green" : "amber"}>{item.status}</Status>,item.requester,item.assignee,item.related,item.date,<AppLink href={`/requests/${item.id}`} className="button ghost">Open request</AppLink>])}/></div>;
}

export function RequestDetailPage({ persona, id }: { persona: Persona; id: string }) {
  const request = requests.find((item) => item.id === id);
  const { state, addDiscussion } = useDemo();
  const [message,setMessage] = useState("");
  if (!request) return <NotFoundPage/>;
  const participant = [request.requester,request.assignee].includes(persona.name);
  if (!participant) return <AccessDeniedPage detail="This assignment discussion is visible only to the requester and assigned employee participants."/>;
  const messages = state.discussions.filter((item) => item.requestId === id);
  return <div className="page"><PageHeader eyebrow={`Requests / ${id}`} title={request.title} description={`${request.status} · Participant-only discussion`} actions={<AppLink href="/requests" className="button secondary">Back to requests</AppLink>}/><div className="dashboard-columns"><section className="panel"><h2>Request summary</h2><DetailList items={[["Requester",request.requester],["Assigned employee",request.assignee],["Related work",request.related],["Schedule date",request.date],["Status",request.status]]}/><div className="button-row"><button className="button primary">Acknowledge request</button><AppLink href="/schedule" className="button secondary">Open related assignment</AppLink></div></section><section className="panel discussion-panel"><header className="panel-heading"><div><p className="eyebrow">Participants only</p><h2>Private discussion</h2></div><IconShieldLock size={20}/></header><div className="message-list">{messages.map((item) => <article key={item.id} className={item.author === persona.name ? "own" : ""}><strong>{item.author}</strong><p>{item.text}</p><small>{item.time}</small></article>)}</div><label className="field">Message<textarea rows={3} value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Write a clarification message"/></label><button className="button primary" disabled={!message.trim()} onClick={() => {addDiscussion(id,persona.name,message);setMessage("");}}>Post message</button></section></div></div>;
}

export function NotificationsPage({ persona }: { persona: Persona }) {
  const { state, toggleNotificationRead, toggleNotificationArchived, markAllRead } = useDemo();
  const [filter,setFilter] = useState<"All"|"Unread"|"Archived">("All");
  const relevant = state.notifications.filter((item) => item.recipient === persona.name || item.recipient === "All affected employees" || (persona.role === "SUPER_ADMIN" && item.recipient === "Nora Albright"));
  const filtered = relevant.filter((item) => filter === "Unread" ? !item.read && !item.archived : filter === "Archived" ? item.archived : !item.archived);
  return <div className="page"><PageHeader eyebrow="Collaboration" title="Notifications" description="In-app events only. No email, SMS, WhatsApp, push, Google, or Microsoft delivery controls." actions={<button className="button secondary" onClick={markAllRead}>Mark all read</button>}/><TabBar tabs={["All","Unread","Archived"]} current={filter} onChange={(value) => setFilter(value as typeof filter)}/><div className="notification-list">{filtered.map((item) => <article key={item.id} className={!item.read ? "unread" : ""}><span className="notification-icon"><IconBell size={20}/></span><div><span className="notification-meta"><Badge tone="grey">{item.type}</Badge><small>{item.time}</small></span><h2>{item.title}</h2><p>{item.detail}</p><div className="button-row"><AppLink href={item.href} className="button ghost">Open related record</AppLink><button className="button ghost" onClick={() => toggleNotificationRead(item.id)}>{item.read ? "Mark unread" : "Mark read"}</button><button className="button ghost" onClick={() => toggleNotificationArchived(item.id)}><IconArchive size={16}/>{item.archived ? "Unarchive" : "Archive"}</button></div></div></article>)}</div></div>;
}

export function ReportsPage({ persona }: { persona: Persona }) {
  const { notify } = useDemo();
  if (persona.role === "EMPLOYEE") return <AccessDeniedPage detail="Employee report access is not confirmed in this prototype."/>;
  return <div className="page"><PageHeader eyebrow="Governance" title="Reports" description="Allocation, availability, coverage, skills, schedule activity, and audit summaries respect persona and scope." actions={<div className="button-row"><button className="button secondary" onClick={() => notify("Simulated CSV export prepared in the browser concept.")}><IconDownload size={17}/>Simulate CSV</button><button className="button secondary" onClick={() => notify("Simulated PDF export prepared in the browser concept.")}><IconDownload size={17}/>Simulate PDF</button></div>}/>{persona.role === "ADMIN" ? <div className="callout warning"><p><strong>Scoped Admin reports are a prototype/later-defined policy.</strong> Current examples stay within {persona.scope} and hide private leave reasons.</p></div> : null}<section className="report-grid"><article className="panel"><h2>Employee allocation</h2><div className="meter-list"><label><span>Published assignments</span><meter min="0" max="18" value="13">13 of 18</meter><strong>13</strong></label><label><span>Available</span><meter min="0" max="18" value="3">3 of 18</meter><strong>3</strong></label><label><span>Leave / limited</span><meter min="0" max="18" value="2">2 of 18</meter><strong>2</strong></label></div></article><article className="panel"><h2>Coverage state</h2><div className="meter-list"><label><span>Satisfied</span><meter min="0" max="12" value="9">9 of 12</meter><strong>9</strong></label><label><span>Warnings</span><meter min="0" max="12" value="2">2 of 12</meter><strong>2</strong></label><label><span>Gaps</span><meter min="0" max="12" value="1">1 of 12</meter><strong>1</strong></label></div></article></section><DataTable label="Allocation report detail" headers={["Team","Employees","Published assignments","Available","Leave","Conflicts"]} rows={[["Team Alpha",8,7,0,1,2],["Team Bravo",7,5,2,0,1],["Shared Services",3,1,1,1,0]]}/><p className="field-note">Exports are clearly simulated frontend actions; no production report service or private leave reason is included.</p></div>;
}

export function AuditPage({ persona }: { persona: Persona }) {
  const { state } = useDemo();
  const [query,setQuery] = useState("");
  if (persona.role !== "SUPER_ADMIN") return <AccessDeniedPage detail="The authorized audit interface is limited to Super Admin in this prototype."/>;
  const filtered = state.audit.filter((item) => `${item.actor} ${item.action} ${item.target} ${item.correlation}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page"><PageHeader eyebrow="Governance" title="Audit" description="Search significant changes with actor, role, target, time, correlation, and expandable metadata." /><section className="filter-bar"><label className="search-field"><IconSearch size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Actor, action, record, or correlation"/></label><label><span>Event type</span><select><option>All events</option><option>Publication</option><option>Leave decision</option><option>Replacement decision</option><option>Role / scope</option><option>Override</option></select></label></section><DataTable label="Audit events" headers={["Time","Actor","Actor role","Action","Target","Correlation","Metadata"]} rows={filtered.map((event) => [event.time,event.actor,event.role.replace("_"," "),event.action,event.target,<Badge tone="grey">{event.correlation}</Badge>,<details><summary>View</summary><p>{event.detail}</p><small>Before/after summary available where applicable.</small></details>])}/></div>;
}

export function SettingsPage({ persona }: { persona: Persona }) {
  const { theme, direction, toggleTheme, toggleDirection, reset, notify } = useDemo();
  const [tab,setTab] = useState("Designations");
  if (persona.role !== "SUPER_ADMIN") return <AccessDeniedPage detail="Global catalogues, roles, and settings are Super Admin controls."/>;
  const tabs=["Designations","Skills","Arrangement labels","Teams & scope","Appearance","Demo controls"];
  return <div className="page"><PageHeader eyebrow="Governance" title="Settings" description="Prototype catalogues and demo preferences only; unresolved production providers and policies are excluded." /><TabBar tabs={tabs} current={tab} onChange={setTab}/>{tab === "Designations" ? <DataTable label="Designations" headers={["Designation","Employees","State","Action"]} rows={[["Senior Network Engineer",2,<Badge tone="green">Active</Badge>,<button className="button ghost">Edit</button>],["Network Engineer",2,<Badge tone="green">Active</Badge>,<button className="button ghost">Edit</button>],["Software Developer",2,<Badge tone="green">Active</Badge>,<button className="button ghost">Edit</button>],["Field Technician",2,<Badge tone="green">Active</Badge>,<button className="button ghost">Edit</button>]]}/> : null}{tab === "Skills" ? <DataTable label="Skills settings" headers={["Skill","Employees","State","Action"]} rows={skillCatalogue.slice(0,8).map(([name,count,,status]) => [name,count,<Badge tone="green">{status}</Badge>,<button className="button ghost" onClick={() => notify(`${name} archived; historical use retained.`)}>Archive</button>])}/> : null}{tab === "Arrangement labels" ? <DataTable label="Arrangement labels" headers={["Label","Meaning","State","Action"]} rows={[["In-house","Descriptive work arrangement",<Badge tone="green">Active</Badge>,<button className="button ghost">Edit</button>],["Outsourced to Client","Internal employee assigned at client",<Badge tone="green">Active</Badge>,<button className="button ghost">Edit</button>],["Scheduled Visit","Planned site visit",<Badge tone="green">Active</Badge>,<button className="button ghost">Edit</button>],["On-call","Descriptive availability arrangement",<Badge tone="green">Active</Badge>,<button className="button ghost">Edit</button>]]}/> : null}{tab === "Teams & scope" ? <section className="panel"><h2>Admin scope fixtures</h2><p>Ava Mercer · Team Alpha</p><p>Ben Iqbal · Team Bravo</p><div className="callout info"><p>System role, employee team, manager, and explicit Admin scope remain separate.</p></div></section> : null}{tab === "Appearance" ? <section className="panel"><h2>Appearance and RTL preview</h2><div className="button-row"><button className="button secondary" onClick={toggleTheme}>Theme: {theme}</button><button className="button secondary" onClick={toggleDirection}>Direction preview: {direction.toUpperCase()}</button></div><p className="field-note">RTL readiness is demonstrated; Arabic localization is not claimed complete.</p></section> : null}{tab === "Demo controls" ? <section className="panel"><h2>Fictional demo state</h2><p>Reset localStorage-backed prototype changes to the deterministic fixtures.</p><button className="button danger" onClick={() => {if(window.confirm("Reset all fictional demo changes?"))reset();}}>Reset demo data</button></section> : null}</div>;
}

export function TicketFuturePage() {
  return <div className="page"><section className="state-page"><IconTicket size={36}/><p className="eyebrow">Later integration</p><h1>Ticket System · Phase 12</h1><p>Later integration after workforce journeys are stable.</p><div className="callout info"><p>Ticket, Assignment, Schedule, Project, Client, and Work Log remain distinct. This frontend concept does not build ticket lists, forms, statuses, work logs, or attachments.</p></div><AppLink href="/dashboard" className="button primary">Return to workforce dashboard</AppLink></section></div>;
}
