"use client";
import { useActionState } from "react";
import { cancelLeaveAction, decideLeaveAction, submitLeaveAction, updateLeaveAllowanceAction, type LeaveAction, type LeaveActionState } from "@/modules/leave/actions";
const initial: LeaveActionState = {};
function FormStatus({ state }: { state: LeaveActionState }) { return <>{state.error ? <p className="operation-error" role="alert">{state.error}</p> : null}{state.success ? <p className="operation-success" role="status">{state.success}</p> : null}</>; }
export function LeaveRequestForm() { const [state, action, pending] = useActionState(submitLeaveAction as LeaveAction, initial); return <form className="operation-form leave-form" action={action} aria-label="Submit annual leave request"><h3>Request annual leave</h3><p>Full calendar dates only. Saturday and Sunday do not consume allowance, but every date in the range is unavailable if approved.</p><div className="operation-form-grid"><label>Start date<input name="startDate" type="date" required /></label><label>End date<input name="endDate" type="date" required /></label></div><label>Private reason or note (optional)<textarea name="privateReason" maxLength={1000} /></label><FormStatus state={state} /><button className="button primary" disabled={pending}>{pending ? "Submitting…" : "Submit leave request"}</button></form>; }
export function CancelLeaveForm({ id, version }: { id: string; version: number }) { const [state, action, pending] = useActionState(cancelLeaveAction as LeaveAction, initial); return <form className="inline-form" action={action}><input type="hidden" name="leaveRequestId" value={id} /><input type="hidden" name="expectedVersion" value={version} /><FormStatus state={state} /><button className="button danger" disabled={pending}>{pending ? "Cancelling…" : "Cancel Pending request"}</button></form>; }
export function LeaveDecisionForm({ id, version }: { id: string; version: number }) { const [state, action, pending] = useActionState(decideLeaveAction as LeaveAction, initial); return <form className="operation-form" action={action} aria-label="Decide leave request"><input type="hidden" name="leaveRequestId" value={id} /><input type="hidden" name="expectedVersion" value={version} /><label>Decision<select name="decision" defaultValue="APPROVED"><option value="APPROVED">Approve</option><option value="REJECTED">Reject</option></select></label><label>Employee-visible response <textarea name="response" maxLength={1000} /></label><p>Rejection requires a response. Approval is blocked while current Published work overlaps these dates.</p><FormStatus state={state} /><button className="button primary" disabled={pending}>{pending ? "Saving…" : "Save decision"}</button></form>; }
export function AllowanceForm({ allowance, version }: { allowance: number; version: number }) { const [state, action, pending] = useActionState(updateLeaveAllowanceAction as LeaveAction, initial); return <form className="operation-form compact" action={action} aria-label="Annual leave allowance"><h3>Global annual allowance</h3><label>Working days per calendar year<input name="annualWorkingDays" type="number" min="1" max="366" defaultValue={allowance} required /></label><input type="hidden" name="expectedVersion" value={version} /><FormStatus state={state} /><button className="button primary" disabled={pending}>{pending ? "Updating…" : "Update allowance"}</button></form>; }
