import { expect, test } from "@playwright/test";
test.skip(process.env.SCOPEIS_PHASE4_E2E !== "true", "Run with the guarded Phase 4 fixture runner.");
async function signIn(page: import("@playwright/test").Page, name: string) { await page.goto("/login"); await page.getByText(name, { exact: true }).click(); await page.getByRole("button", { name: "Continue with mock persona" }).click(); await expect(page).toHaveURL(/\/dashboard$/); }
async function signOut(page: import("@playwright/test").Page) { await page.request.post("/api/auth/logout", { headers: { Origin: new URL(page.url()).origin } }); }
async function selectContaining(select: import("@playwright/test").Locator, text: string) { const value = await select.locator("option").filter({ hasText: text }).getAttribute("value"); if (!value) throw new Error(`Missing option: ${text}`); await select.selectOption(value); }

test("Super Admin publishes a monthly assignment and Employee sees only My Schedule", async ({ page }) => {
  const month = page.viewportSize()?.width === 390 ? "2026-06" : "2026-05";
  const assignmentDate = `${month}-06`;
  await signIn(page, "Nora Albright"); await page.goto(`/schedule?month=${month}`);
  const create = page.getByRole("form", { name: "Create a monthly Draft" }); await selectContaining(create.locator('select[name="clientId"]'), "Alpha Facilities"); await create.getByLabel("Planning month").fill(month); await create.getByRole("button", { name: "Create Draft" }).click(); await expect(create.getByText("Draft schedule created.")).toBeVisible();
  await page.getByRole("link", { name: /Alpha Facilities.*Revision 1/ }).click(); const add = page.getByRole("form", { name: "Add schedule assignment" }); await selectContaining(add.locator('select[name="employeeUserId"]'), "Cora Bell"); await selectContaining(add.locator('select[name="projectId"]'), "Alpha Modernization"); await selectContaining(add.locator('select[name="locationId"]'), "Alpha Shared Site"); await add.getByLabel("Date").fill(assignmentDate); await add.getByLabel("Start time").fill("09:00"); await add.getByLabel("End time").fill("10:00"); await add.getByLabel(/Short work instruction/).fill("Use the reception desk."); await add.getByRole("button", { name: "Add assignment" }).click(); await expect(page.getByText("Assignment added to the Draft.")).toBeVisible();
  await page.getByRole("form", { name: "Propose this Draft" }).getByRole("button", { name: "Propose for review" }).click(); await expect(page.getByRole("link", { name: /^PROPOSED Alpha Facilities/ })).toBeVisible(); await page.getByRole("form", { name: "Publish Proposed schedule" }).getByRole("button", { name: "Publish schedule" }).click(); await expect(page.getByRole("link", { name: /^PUBLISHED Alpha Facilities/ })).toBeVisible(); await signOut(page);
  await signIn(page, "Cora Bell"); await page.goto(`/schedule?month=${month}`); await expect(page.getByRole("heading", { name: "My Schedule" })).toBeVisible(); await expect(page.getByText("Alpha Facilities")).toBeVisible(); await expect(page.getByText("Alpha Modernization · Alpha Shared Site")).toBeVisible(); await expect(page.getByText(/Use the reception desk/)).toBeVisible(); await expect(page.getByText("Monthly planning board")).toHaveCount(0); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); await signOut(page);
});
