import { expect, test } from "@playwright/test";
import { signIn, signOut } from "./sign-in";
test.skip(process.env.SCOPEIS_PHASE4_E2E !== "true", "Run with the guarded Phase 4 fixture runner.");
async function selectContaining(select: import("@playwright/test").Locator, text: string) { const value = await select.locator("option").filter({ hasText: text }).getAttribute("value"); if (!value) throw new Error(`Missing option: ${text}`); await select.selectOption(value); }

test("Super Admin publishes a monthly assignment and Employee sees only My Schedule", async ({ page }) => {
  const month = page.viewportSize()?.width === 390 ? "2026-06" : "2026-05";
  const assignmentDate = `${month}-06`;
  await signIn(page, "Nora Albright"); await page.goto(`/schedule?month=${month}`);
  await page.getByRole("button", { name: "New monthly schedule" }).click();
  const create = page.getByRole("form", { name: "Create a monthly Draft" }); await selectContaining(create.locator('select[name="clientId"]'), "Alpha Facilities"); await create.getByLabel("Planning month").fill(month); await create.getByRole("button", { name: "Create Draft" }).click(); await expect(create.getByText("Draft schedule created.")).toBeVisible(); await page.getByRole("button", { name: "Close", exact: true }).click();
  await page.getByRole("link", { name: /Alpha Facilities.*Revision 1/ }).click(); await page.getByRole("button", { name: "Add assignment", exact: true }).click(); const add = page.getByRole("form", { name: "Add schedule assignment" }); await selectContaining(add.locator('select[name="employeeUserId"]'), "Cora Bell"); await selectContaining(add.locator('select[name="projectId"]'), "Alpha Modernization"); await selectContaining(add.locator('select[name="locationId"]'), "Alpha Shared Site"); await add.getByLabel("Date").fill(assignmentDate); await add.getByLabel("Start time").fill("09:00"); await add.getByLabel("End time").fill("10:00"); await add.getByLabel(/Short work instruction/).fill("Use the reception desk."); await add.getByRole("button", { name: "Add assignment" }).click(); await expect(page.getByText("Assignment added to the Draft.")).toBeVisible(); await page.getByRole("button", { name: "Close", exact: true }).click();
  await expect(page.getByRole("link", { name: "Review coverage", exact: true }).first()).toBeVisible();
  await page.getByRole("form", { name: "Propose this Draft" }).getByRole("button", { name: "Propose for review" }).click(); await expect(page.getByRole("link", { name: /^PROPOSED Alpha Facilities/ })).toBeVisible();
  await page.getByRole("button", { name: "Return to Draft", exact: true }).click();
  const returned = page.getByRole("dialog", { name: "Return schedule for changes", exact: true });
  await returned.getByLabel("Reason for return").fill("Confirm the reception instruction.");
  await returned.getByRole("button", { name: "Return to Draft", exact: true }).click();
  await expect(returned).not.toBeVisible();
  await expect(page.getByRole("status")).toHaveText("Schedule returned to Draft.");
  await page.getByRole("form", { name: "Propose this Draft" }).getByRole("button", { name: "Propose for review" }).click();
  await page.getByRole("form", { name: "Publish Proposed schedule" }).getByRole("button", { name: "Publish schedule" }).click(); await expect(page.getByRole("link", { name: /^PUBLISHED Alpha Facilities/ })).toBeVisible();
  await page.getByRole("link", { name: "Next month", exact: true }).click();
  await expect(page).not.toHaveURL(/[?&]period=/);
  await expect(page.getByRole("heading", { name: "Select a schedule", exact: true })).toBeVisible();
  await page.getByLabel("Planning month", { exact: true }).fill(month);
  await page.getByRole("button", { name: "Go", exact: true }).click();
  await page.getByRole("link", { name: /^PUBLISHED Alpha Facilities/ }).click();
  await page.getByRole("link", { name: "Review coverage", exact: true }).first().click();
  await expect(page.getByRole("heading", { name: "Coverage review", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Cora Bell", exact: true })).toBeVisible();
  await expect(page.getByLabel("Assignment ID")).toHaveCount(0);
  await page.getByRole("link", { name: /Back to schedule/ }).click();
  await page.getByRole("button", { name: "Create Draft revision", exact: true }).click();
  await page.getByRole("link", { name: /DRAFT Alpha Facilities Revision 2/ }).click();
  await page.getByRole("button", { name: "Edit assignment", exact: true }).click();
  const edit = page.getByRole("dialog", { name: "Edit Cora Bell’s assignment", exact: true });
  await edit.getByText("Remove assignment", { exact: true }).click();
  await edit.getByRole("button", { name: "Remove", exact: true }).click();
  await expect(edit).not.toBeVisible();
  await expect(page.getByRole("status")).toHaveText("Draft assignment removed.");
  await signOut(page);
  await signIn(page, "Cora Bell"); await page.goto(`/schedule?month=${month}`); await expect(page.getByRole("heading", { name: "My timetable" })).toBeVisible(); await expect(page.getByText("Alpha Facilities")).toBeVisible(); await expect(page.getByText("Alpha Modernization · Alpha Shared Site")).toBeVisible(); await expect(page.getByText(/Use the reception desk/)).toBeVisible(); await expect(page.getByText("Monthly planning board")).toHaveCount(0); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); await signOut(page);
});
