import { describe, expect, it } from "vitest";
import { db } from "@/db/client";
import { adminScopeGrants, staffingRequirements, users } from "@/db/schema";
import { and, eq } from "drizzle-orm";
import { employeeCatalogueService, employeeSkillService } from "@/modules/employees/employee-services";
import { operationalService } from "@/modules/operations/service";
import { coverageService } from "@/modules/coverage/service";
import { capabilityService } from "@/modules/capabilities/service";
import { CoverageService } from "@/modules/coverage/service";
import { coverageRepository } from "@/modules/coverage/repositories";
import { schedulingService } from "@/modules/scheduling/service";
import { phase3Ids, phase4Ids } from "../../scripts/phase4-test-fixtures.mjs";
import type { AuthenticatedActor } from "@/shared/types/foundation";
const actor = (id: string, role: AuthenticatedActor["role"]): AuthenticatedActor => ({ id, role, displayName: id, sessionId: `s-${id}`, sessionVersion: 1, scopes: [], authenticationMode: "mock" });
const nora = actor("mock-super-admin-nora", "SUPER_ADMIN"), ava = actor("mock-admin-ava", "ADMIN"), cora = actor("mock-employee-cora", "EMPLOYEE"), eli = actor(phase4Ids.alphaEmployee, "EMPLOYEE");
describe("Phase 7 coverage and replacement journey", () => {
  it("keeps independent coverage rules non-blocking and applies an approved add request only to Draft", async () => {
    const skill = await employeeCatalogueService.createSkill(nora, { name: "Phase 7 Coverage Skill" });
    await employeeSkillService.add(nora, { employeeUserId: cora.id, skillId: skill.id }); await employeeSkillService.add(nora, { employeeUserId: eli.id, skillId: skill.id }); const inherited = await db.select().from(staffingRequirements).where(eq(staffingRequirements.projectId, phase3Ids.alphaProjectOne)).then(([row]) => row!); await employeeSkillService.add(nora, { employeeUserId: cora.id, skillId: inherited.requiredSkillId }); await employeeSkillService.add(nora, { employeeUserId: eli.id, skillId: inherited.requiredSkillId });
    const rule = await operationalService.addRequirement(nora, { type: "LOCATION", id: phase3Ids.alphaLocation, requiredSkillId: skill.id, requiredEmployeeCount: 2 });
    const period = await schedulingService.createPeriod(nora, { clientId: phase3Ids.alphaClient, month: "2027-05" }); const anchor = await schedulingService.addAssignment(nora, { periodId: period.id, expectedPeriodVersion: period.version, employeeUserId: cora.id, projectId: phase3Ids.alphaProjectOne, locationId: phase3Ids.alphaLocation, assignmentDate: "2027-05-12", startTime: "09:00", endTime: "11:00" });
    const context = await coverageService.assignmentContext(ava, anchor.id); expect(context).toMatchObject({ employeeName: "Cora Bell", clientName: "Alpha Facilities", projectName: "Alpha Modernization", locationName: "Alpha Shared Site", assignmentDate: "2027-05-12", startTime: "09:00", endTime: "11:00" }); expect(Object.keys(context).sort()).toEqual(["id", "periodId", "month", "status", "employeeName", "clientName", "projectName", "locationName", "assignmentDate", "startTime", "endTime"].sort());
    const gaps = await coverageService.gaps(ava, anchor.id); const gap = gaps.find((item) => item.staffingRequirementId === rule.id); expect(gap?.missingEmployeeCount).toBe(1);
    const candidates = await coverageService.candidates(ava, anchor.id); expect(candidates.candidates.map((item) => item.id)).toContain(eli.id); await expect(coverageService.gaps(cora, anchor.id)).rejects.toMatchObject({ code: "FORBIDDEN" });
    const request = await coverageService.create(ava, { staffingRequirementId: rule.id, anchorAssignmentId: anchor.id, intent: "ADD_COVERAGE_ASSIGNMENT", nominatedEmployeeUserId: eli.id }); expect(request.status).toBe("PENDING");
    const approved = await coverageService.decide(nora, { replacementRequestId: request.id, expectedVersion: request.version, decision: "APPROVED", selectedEmployeeUserId: eli.id }); expect(approved.effectStatus).toBe("APPLIED_TO_DRAFT"); expect((await schedulingService.getPeriodEditor(nora, period.id)).assignments).toHaveLength(2);
    await expect(coverageService.decide(nora, { replacementRequestId: request.id, expectedVersion: request.version, decision: "APPROVED", selectedEmployeeUserId: eli.id })).rejects.toMatchObject({ code: "STALE_VERSION" });
  });
  it("requires Super Admin decision authority and never lets a replacement publish a schedule", async () => { const period = await schedulingService.createPeriod(nora, { clientId: phase3Ids.alphaClient, month: "2027-06" }); const anchor = await schedulingService.addAssignment(nora, { periodId: period.id, expectedPeriodVersion: period.version, employeeUserId: cora.id, projectId: phase3Ids.alphaProjectOne, locationId: phase3Ids.alphaLocation, assignmentDate: "2027-06-12", startTime: "09:00", endTime: "11:00" }); const missing = await employeeCatalogueService.createSkill(nora, { name: "Phase 7 Direct Gap" }); await capabilityService.addAssignmentRequirement(nora, { assignmentId: anchor.id, skillId: missing.id }); const request = await coverageService.create(ava, { anchorAssignmentId: anchor.id, intent: "REPLACE_ASSIGNMENT" }); await expect(coverageService.decide(ava, { replacementRequestId: request.id, expectedVersion: request.version, decision: "REJECTED" })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect((await db.select().from((await import("@/db/schema")).schedulePeriods).where((await import("drizzle-orm")).eq((await import("@/db/schema")).schedulePeriods.id, period.id)))[0]?.status).toBe("DRAFT"); });
  it("returns Proposed to Draft and creates an immutable Draft revision from Published", async () => {
    const proposed = await schedulingService.createPeriod(nora, { clientId: phase3Ids.alphaClient, month: "2027-07" }); const proposedAnchor = await schedulingService.addAssignment(nora, { periodId: proposed.id, expectedPeriodVersion: proposed.version, employeeUserId: cora.id, projectId: phase3Ids.alphaProjectOne, locationId: phase3Ids.alphaLocation, assignmentDate: "2027-07-12", startTime: "09:00", endTime: "11:00" }); const proposedSkill = await employeeCatalogueService.createSkill(nora, { name: "Phase 7 Proposed Skill" }); await employeeSkillService.add(nora, { employeeUserId: eli.id, skillId: proposedSkill.id }); await capabilityService.addAssignmentRequirement(nora, { assignmentId: proposedAnchor.id, skillId: proposedSkill.id }); const proposedRequest = await coverageService.create(ava, { anchorAssignmentId: proposedAnchor.id, intent: "REPLACE_ASSIGNMENT", nominatedEmployeeUserId: eli.id }); const proposedRow = await schedulingService.propose(nora, { periodId: proposed.id, expectedVersion: proposed.version + 1 }); const decidedProposed = await coverageService.decide(nora, { replacementRequestId: proposedRequest.id, expectedVersion: proposedRequest.version, decision: "APPROVED", selectedEmployeeUserId: eli.id }); expect(decidedProposed.effectStatus).toBe("APPLIED_TO_DRAFT"); expect((await schedulingService.getPeriodEditor(nora, proposed.id)).period.status).toBe("DRAFT");
    const published = await schedulingService.createPeriod(nora, { clientId: phase3Ids.alphaClient, month: "2027-08" }); const publishedAnchor = await schedulingService.addAssignment(nora, { periodId: published.id, expectedPeriodVersion: published.version, employeeUserId: cora.id, projectId: phase3Ids.alphaProjectOne, locationId: phase3Ids.alphaLocation, assignmentDate: "2027-08-12", startTime: "09:00", endTime: "11:00" }); const publishedSkill = await employeeCatalogueService.createSkill(nora, { name: "Phase 7 Published Skill" }); await employeeSkillService.add(nora, { employeeUserId: eli.id, skillId: publishedSkill.id }); await capabilityService.addAssignmentRequirement(nora, { assignmentId: publishedAnchor.id, skillId: publishedSkill.id }); const publishedRequest = await coverageService.create(ava, { anchorAssignmentId: publishedAnchor.id, intent: "REPLACE_ASSIGNMENT", nominatedEmployeeUserId: eli.id }); const publishedRow = await schedulingService.publish(nora, { periodId: (await schedulingService.propose(nora, { periodId: published.id, expectedVersion: published.version + 1 })).id, expectedVersion: published.version + 2 }); const decidedPublished = await coverageService.decide(nora, { replacementRequestId: publishedRequest.id, expectedVersion: publishedRequest.version, decision: "APPROVED", selectedEmployeeUserId: eli.id }); expect(decidedPublished.effectStatus).toBe("PUBLISHED_REVISION_CREATED"); expect((await schedulingService.getPeriodEditor(nora, publishedRow.id)).period.status).toBe("PUBLISHED"); expect((await schedulingService.getPeriodEditor(nora, decidedPublished.effectSchedulePeriodId!)).period.status).toBe("DRAFT");
  });
  it("rolls back a request when its required notification write fails", async () => { const period = await schedulingService.createPeriod(nora, { clientId: phase3Ids.alphaClient, month: "2027-09" }); const anchor = await schedulingService.addAssignment(nora, { periodId: period.id, expectedPeriodVersion: period.version, employeeUserId: cora.id, projectId: phase3Ids.alphaProjectOne, locationId: phase3Ids.alphaLocation, assignmentDate: "2027-09-12", startTime: "09:00", endTime: "11:00" }); const missing = await employeeCatalogueService.createSkill(nora, { name: "Phase 7 Rollback Skill" }); await capabilityService.addAssignmentRequirement(nora, { assignmentId: anchor.id, skillId: missing.id }); const failing = new CoverageService(undefined, async () => { throw new Error("forced notification failure"); }); await expect(failing.create(ava, { anchorAssignmentId: anchor.id, intent: "REPLACE_ASSIGNMENT" })).rejects.toThrow("forced notification failure"); expect((await coverageRepository.requestsForRequester(db, ava.id)).filter((item) => item.anchorAssignmentId === anchor.id)).toHaveLength(0); });
});

describe("Coverage authorization and employee lifecycle regressions", () => {
  it("requires TEAM visibility of the anchor for gaps, candidates, and requests without nominees", async () => {
    const period = await schedulingService.createPeriod(nora, { clientId: phase3Ids.alphaClient, month: "2032-01" });
    const anchor = await schedulingService.addAssignment(nora, { periodId: period.id, expectedPeriodVersion: period.version, employeeUserId: phase4Ids.bravoEmployee, projectId: phase3Ids.alphaProjectOne, locationId: phase3Ids.alphaLocation, assignmentDate: "2032-01-12", startTime: "09:00", endTime: "11:00" });
    await expect(coverageService.assignmentContext(ava, anchor.id)).rejects.toMatchObject({ code: "OUT_OF_SCOPE" });
    await expect(coverageService.assignmentContext(nora, "invalid-id")).rejects.toMatchObject({ code: "NOT_FOUND" });
    await expect(coverageService.gaps(ava, anchor.id)).rejects.toMatchObject({ code: "OUT_OF_SCOPE" });
    await expect(coverageService.candidates(ava, anchor.id)).rejects.toMatchObject({ code: "OUT_OF_SCOPE" });
    await expect(coverageService.create(ava, { anchorAssignmentId: anchor.id, intent: "REPLACE_ASSIGNMENT" })).rejects.toMatchObject({ code: "OUT_OF_SCOPE" });
    expect((await coverageRepository.requestsForRequester(db, ava.id)).filter((request) => request.anchorAssignmentId === anchor.id)).toHaveLength(0);
    await db.insert(adminScopeGrants).values({ userId: ava.id, scopeType: "TEAM", scopeReference: "team:bravo" });
    try { expect((await coverageService.gaps(ava, anchor.id)).length).toBeGreaterThan(0); }
    finally { await db.delete(adminScopeGrants).where(and(eq(adminScopeGrants.userId, ava.id), eq(adminScopeGrants.scopeType, "TEAM"), eq(adminScopeGrants.scopeReference, "team:bravo"))); }
  });

  it("stops counting an inactive or reassigned-role employee toward staffing", async () => {
    const period = await schedulingService.createPeriod(nora, { clientId: phase3Ids.alphaClient, month: "2032-02" });
    const anchor = await schedulingService.addAssignment(nora, { periodId: period.id, expectedPeriodVersion: period.version, employeeUserId: cora.id, projectId: phase3Ids.alphaProjectOne, locationId: phase3Ids.alphaLocation, assignmentDate: "2032-02-12", startTime: "09:00", endTime: "11:00" });
    await schedulingService.addAssignment(nora, { periodId: period.id, expectedPeriodVersion: period.version + 1, employeeUserId: eli.id, projectId: phase3Ids.alphaProjectOne, locationId: phase3Ids.alphaLocation, assignmentDate: "2032-02-12", startTime: "09:00", endTime: "11:00" });
    const rule = await db.select().from(staffingRequirements).where(eq(staffingRequirements.projectId, phase3Ids.alphaProjectOne)).then(([row]) => row!);
    expect((await coverageService.gaps(nora, anchor.id)).find((gap) => gap.staffingRequirementId === rule.id)).toBeUndefined();
    try {
      await db.update(users).set({ active: false }).where(eq(users.id, eli.id));
      expect((await coverageService.gaps(nora, anchor.id)).find((gap) => gap.staffingRequirementId === rule.id)).toMatchObject({ eligibleEmployeeCount: 1, missingEmployeeCount: 1 });
      await db.update(users).set({ active: true, role: "ADMIN" }).where(eq(users.id, eli.id));
      expect((await coverageService.gaps(nora, anchor.id)).find((gap) => gap.staffingRequirementId === rule.id)).toMatchObject({ eligibleEmployeeCount: 1, missingEmployeeCount: 1 });
    } finally { await db.update(users).set({ active: true, role: "EMPLOYEE" }).where(eq(users.id, eli.id)); }
  });
});
