"use server";
import { revalidatePath } from "next/cache";
import { getCurrentActor } from "@/modules/auth/session-service";
import { LeaveDomainError } from "@/modules/leave/domain-error";
import { leaveService } from "@/modules/leave/service";
export type LeaveActionState = { error?: string; success?: string }; export type LeaveAction = (state: LeaveActionState, data: FormData) => Promise<LeaveActionState>;
const text = (data: FormData, key: string) => typeof data.get(key) === "string" ? String(data.get(key)).trim() : ""; const number = (data: FormData, key: string) => Number(text(data, key)); const allowed = (data: FormData, keys: string[]) => [...data.keys()].every((key) => keys.includes(key) || key.startsWith("$ACTION_"));
async function actor() { const current = await getCurrentActor(); if (!current) throw new LeaveDomainError("FORBIDDEN", "Your session expired. Sign in again."); return current; }
async function run(operation: () => Promise<unknown>, success: string) { try { await operation(); revalidatePath("/leave"); revalidatePath("/schedule"); return { success }; } catch (error) { return { error: error instanceof LeaveDomainError ? error.message : "The leave change could not be saved. Reload and try again." }; } }
export const submitLeaveAction: LeaveAction = async (_s, data) => !allowed(data, ["startDate", "endDate", "privateReason"]) ? { error: "The leave form contained unsupported fields." } : run(async () => leaveService.submit(await actor(), { startDate: text(data, "startDate"), endDate: text(data, "endDate"), privateReason: text(data, "privateReason") }), "Leave request submitted for Super Admin review.");
export const cancelLeaveAction: LeaveAction = async (_s, data) => !allowed(data, ["leaveRequestId", "expectedVersion"]) ? { error: "The leave form contained unsupported fields." } : run(async () => leaveService.cancel(await actor(), { leaveRequestId: text(data, "leaveRequestId"), expectedVersion: number(data, "expectedVersion") }), "Pending leave request cancelled.");
export const decideLeaveAction: LeaveAction = async (_s, data) => !allowed(data, ["leaveRequestId", "expectedVersion", "decision", "response"]) ? { error: "The leave form contained unsupported fields." } : run(async () => leaveService.decide(await actor(), { leaveRequestId: text(data, "leaveRequestId"), expectedVersion: number(data, "expectedVersion"), decision: text(data, "decision"), response: text(data, "response") }), "Leave decision saved and the Employee was notified.");
export const updateLeaveAllowanceAction: LeaveAction = async (_s, data) => !allowed(data, ["annualWorkingDays", "expectedVersion"]) ? { error: "The allowance form contained unsupported fields." } : run(async () => leaveService.updateAllowance(await actor(), { annualWorkingDays: number(data, "annualWorkingDays"), expectedVersion: number(data, "expectedVersion") }), "Annual leave allowance updated.");
