import "server-only";
import { and, asc, eq, gte, inArray, lte, sql } from "drizzle-orm";
import { db } from "@/db/client";
import { adminScopeGrants, clients, employeeProfiles, leaveAllowanceSettings, leaveRequests, locations, projects, scheduleAssignments, schedulePeriods, users } from "@/db/schema";
export type LeaveTransaction = Parameters<Parameters<typeof db.transaction>[0]>[0]; export type LeaveExecutor = typeof db | LeaveTransaction;
export const leaveRepository = {
  request(executor: LeaveExecutor, id: string) { return executor.select().from(leaveRequests).where(eq(leaveRequests.id, id)).limit(1).then(([row]) => row ?? null); },
  lockRequest(tx: LeaveTransaction, id: string) { return tx.execute(sql`select id from leave_requests where id = ${id} for update`); },
  allowance(executor: LeaveExecutor) { return executor.select().from(leaveAllowanceSettings).where(eq(leaveAllowanceSettings.singleton, true)).limit(1).then(([row]) => row ?? null); },
  lockAllowance(tx: LeaveTransaction) { return tx.execute(sql`select singleton from leave_allowance_settings where singleton = true for update`); },
  activeOverlap(tx: LeaveTransaction, employeeUserId: string, startDate: string, endDate: string, excludeId?: string) { return tx.select({ id: leaveRequests.id }).from(leaveRequests).where(and(eq(leaveRequests.employeeUserId, employeeUserId), inArray(leaveRequests.status, ["PENDING", "APPROVED"]), lte(leaveRequests.startDate, endDate), gte(leaveRequests.endDate, startDate), excludeId ? sql`${leaveRequests.id} <> ${excludeId}` : undefined)).limit(1).then(([row]) => row ?? null); },
  approvedIntersecting(executor: LeaveExecutor, employeeUserId: string, startDate: string, endDate: string) { return executor.select().from(leaveRequests).where(and(eq(leaveRequests.employeeUserId, employeeUserId), eq(leaveRequests.status, "APPROVED"), lte(leaveRequests.startDate, endDate), gte(leaveRequests.endDate, startDate))).orderBy(asc(leaveRequests.startDate)); },
  mine(executor: LeaveExecutor, employeeUserId: string) { return executor.select().from(leaveRequests).where(eq(leaveRequests.employeeUserId, employeeUserId)).orderBy(asc(leaveRequests.startDate)); },
  pending(executor: LeaveExecutor) { return executor.select({ request: leaveRequests, employeeName: users.displayName }).from(leaveRequests).innerJoin(users, eq(users.id, leaveRequests.employeeUserId)).where(eq(leaveRequests.status, "PENDING")).orderBy(asc(leaveRequests.createdAt)); },
  approvedEmployeeIds(executor: LeaveExecutor) { return executor.selectDistinct({ employeeUserId: leaveRequests.employeeUserId }).from(leaveRequests).where(eq(leaveRequests.status, "APPROVED")); },
  activeSuperAdmins(executor: LeaveExecutor) { return executor.select({ id: users.id }).from(users).where(and(eq(users.role, "SUPER_ADMIN"), eq(users.active, true))); },
  activeGrants(executor: LeaveExecutor, userId: string) { return executor.select().from(adminScopeGrants).where(and(eq(adminScopeGrants.userId, userId), eq(adminScopeGrants.active, true))); },
  visibleApproved(executor: LeaveExecutor, teams: string[]) { return executor.select({ request: leaveRequests, employeeName: users.displayName }).from(leaveRequests).innerJoin(users, eq(users.id, leaveRequests.employeeUserId)).innerJoin(employeeProfiles, eq(employeeProfiles.userId, users.id)).where(and(eq(leaveRequests.status, "APPROVED"), teams.length ? inArray(employeeProfiles.team, teams) : sql`false`)).orderBy(asc(leaveRequests.startDate)); },
  updateRequest(tx: LeaveTransaction, id: string, expectedVersion: number, values: Partial<typeof leaveRequests.$inferInsert>) { return tx.update(leaveRequests).set({ ...values, version: sql`${leaveRequests.version} + 1`, updatedAt: new Date() }).where(and(eq(leaveRequests.id, id), eq(leaveRequests.version, expectedVersion))).returning().then(([row]) => row ?? null); },
  updateAllowance(tx: LeaveTransaction, expectedVersion: number, annualWorkingDays: number) { return tx.update(leaveAllowanceSettings).set({ annualWorkingDays, version: sql`${leaveAllowanceSettings.version} + 1`, updatedAt: new Date() }).where(and(eq(leaveAllowanceSettings.singleton, true), eq(leaveAllowanceSettings.version, expectedVersion))).returning().then(([row]) => row ?? null); },
  createRequest(tx: LeaveTransaction, values: typeof leaveRequests.$inferInsert) { return tx.insert(leaveRequests).values(values).returning().then(([row]) => row!); },
  publishedImpact(executor: LeaveExecutor, employeeUserId: string, startDate: string, endDate: string) { return executor.select({ id: scheduleAssignments.id, assignmentDate: scheduleAssignments.assignmentDate, startTime: scheduleAssignments.startTime, endTime: scheduleAssignments.endTime, periodId: schedulePeriods.id, clientName: clients.companyName, projectName: projects.name, locationName: locations.name }).from(scheduleAssignments).innerJoin(schedulePeriods, eq(schedulePeriods.id, scheduleAssignments.schedulePeriodId)).innerJoin(clients, eq(clients.id, schedulePeriods.clientId)).innerJoin(projects, eq(projects.id, scheduleAssignments.projectId)).innerJoin(locations, eq(locations.id, scheduleAssignments.locationId)).where(and(eq(scheduleAssignments.employeeUserId, employeeUserId), eq(schedulePeriods.status, "PUBLISHED"), eq(schedulePeriods.isCurrent, true), gte(scheduleAssignments.assignmentDate, startDate), lte(scheduleAssignments.assignmentDate, endDate))).orderBy(asc(scheduleAssignments.assignmentDate), asc(scheduleAssignments.startTime)); },
};
