import "server-only";
import { sql } from "drizzle-orm";
import { db } from "@/db/client";
import { writeAuditEvent } from "@/modules/audit/audit-service";
import { createNotification } from "@/modules/notifications/notification-service";
import { LeaveDomainError } from "@/modules/leave/domain-error";
import { dubaiCalendarYear, LEAVE_TIMEZONE, workingDays } from "@/modules/leave/date-rules";
import { leaveRepository, type LeaveTransaction } from "@/modules/leave/repositories";
import { allowanceUpdateSchema, leaveDecisionSchema, leaveSubmitSchema, leaveVersionSchema, parseLeave } from "@/modules/leave/validation";
import type { AuthenticatedActor } from "@/shared/types/foundation";

export { LEAVE_TIMEZONE, workingDays, dubaiCalendarYear } from "@/modules/leave/date-rules";
function yearRange(year: number) { return { start: `${year}-01-01`, end: `${year}-12-31` }; }
function intersectionDays(startDate: string, endDate: string, year: number) { const range = yearRange(year); return startDate > range.end || endDate < range.start ? 0 : workingDays(startDate > range.start ? startDate : range.start, endDate < range.end ? endDate : range.end); }
type AuditWriter = typeof writeAuditEvent; type NotificationWriter = typeof createNotification;
export class LeaveService {
  constructor(private readonly auditWriter: AuditWriter = writeAuditEvent, private readonly notificationWriter: NotificationWriter = createNotification) {}
  private audit(tx: LeaveTransaction, actor: AuthenticatedActor, action: string, targetId: string, metadata: Record<string, unknown>) { return this.auditWriter(tx, { actor, action, targetType: "leave_request", targetId, metadata }); }
  private async lockEmployee(tx: LeaveTransaction, employeeUserId: string) { await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`leave:${employeeUserId}`}))`); }
  private async balance(executor: LeaveTransaction | typeof db, employeeUserId: string, year = dubaiCalendarYear()) { const allowance = await leaveRepository.allowance(executor); if (!allowance) throw new Error("Leave allowance setting is missing."); const approved = await leaveRepository.approvedIntersecting(executor, employeeUserId, `${year}-01-01`, `${year}-12-31`); const used = approved.reduce((total, request) => total + intersectionDays(request.startDate, request.endDate, year), 0); return { year, allowance: allowance.annualWorkingDays, used, remaining: allowance.annualWorkingDays - used, allowanceVersion: allowance.version }; }
  async getMyLeave(actor: AuthenticatedActor) { if (actor.role !== "EMPLOYEE") throw new LeaveDomainError("FORBIDDEN"); const [requests, balance] = await Promise.all([leaveRepository.mine(db, actor.id), this.balance(db, actor.id)]); return { requests: requests.map((request) => ({ ...request, requestedWorkingDays: workingDays(request.startDate, request.endDate), projectedRemaining: balance.remaining - workingDays(request.startDate, request.endDate) })), balance }; }
  async submit(actor: AuthenticatedActor, input: unknown) { if (actor.role !== "EMPLOYEE") throw new LeaveDomainError("FORBIDDEN"); const parsed = parseLeave(leaveSubmitSchema, input); return db.transaction(async (tx) => { await this.lockEmployee(tx, actor.id); if (await leaveRepository.activeOverlap(tx, actor.id, parsed.startDate, parsed.endDate)) throw new LeaveDomainError("ACTIVE_OVERLAP"); const row = await leaveRepository.createRequest(tx, { employeeUserId: actor.id, ...parsed }); const balance = await this.balance(tx, actor.id); await this.audit(tx, actor, "leave.requested", row.id, { employeeUserId: actor.id, startDate: row.startDate, endDate: row.endDate, workingDays: workingDays(row.startDate, row.endDate), projectedRemaining: balance.remaining - workingDays(row.startDate, row.endDate), reasonProvided: Boolean(row.privateReason) }); for (const recipient of await leaveRepository.activeSuperAdmins(tx)) await this.notificationWriter(tx, { recipientUserId: recipient.id, eventType: "leave.submitted", relatedRecordType: "leave_request", relatedRecordId: row.id }); return row; }); }
  async cancel(actor: AuthenticatedActor, input: unknown) { const parsed = parseLeave(leaveVersionSchema, input); const request = await leaveRepository.request(db, parsed.leaveRequestId); if (!request || request.employeeUserId !== actor.id || actor.role !== "EMPLOYEE") throw new LeaveDomainError("NOT_FOUND"); return db.transaction(async (tx) => { await this.lockEmployee(tx, actor.id); await leaveRepository.lockRequest(tx, request.id); const current = await leaveRepository.request(tx, request.id); if (!current || current.version !== parsed.expectedVersion) throw new LeaveDomainError("STALE_VERSION"); if (current.status !== "PENDING") throw new LeaveDomainError("INVALID_STATE"); const row = await leaveRepository.updateRequest(tx, current.id, current.version, { status: "CANCELLED", cancelledAt: new Date() }); if (!row) throw new LeaveDomainError("STALE_VERSION"); await this.audit(tx, actor, "leave.cancelled", row.id, { employeeUserId: actor.id, state: row.status, workingDays: workingDays(row.startDate, row.endDate) }); return row; }); }
  async getReview(actor: AuthenticatedActor, requestId: string) { if (actor.role !== "SUPER_ADMIN") throw new LeaveDomainError("NOT_FOUND"); const request = await leaveRepository.request(db, requestId); if (!request) throw new LeaveDomainError("NOT_FOUND"); const [balance, publishedImpact] = await Promise.all([this.balance(db, request.employeeUserId), leaveRepository.publishedImpact(db, request.employeeUserId, request.startDate, request.endDate)]); return { request, balance, requestedWorkingDays: workingDays(request.startDate, request.endDate), projectedRemaining: balance.remaining - (request.status === "APPROVED" ? 0 : workingDays(request.startDate, request.endDate)), publishedImpact }; }
  async reviewQueue(actor: AuthenticatedActor) { if (actor.role !== "SUPER_ADMIN") throw new LeaveDomainError("NOT_FOUND"); return leaveRepository.pending(db); }
  async decide(actor: AuthenticatedActor, input: unknown) { if (actor.role !== "SUPER_ADMIN") throw new LeaveDomainError("FORBIDDEN"); const parsed = parseLeave(leaveDecisionSchema, input); const request = await leaveRepository.request(db, parsed.leaveRequestId); if (!request) throw new LeaveDomainError("NOT_FOUND"); return db.transaction(async (tx) => { await leaveRepository.lockAllowance(tx); await this.lockEmployee(tx, request.employeeUserId); await leaveRepository.lockRequest(tx, request.id); const current = await leaveRepository.request(tx, request.id); if (!current || current.version !== parsed.expectedVersion) throw new LeaveDomainError("STALE_VERSION"); if (current.status !== "PENDING") throw new LeaveDomainError("INVALID_STATE"); const publishedImpact = await leaveRepository.publishedImpact(tx, current.employeeUserId, current.startDate, current.endDate); if (parsed.decision === "APPROVED" && publishedImpact.length) throw new LeaveDomainError("PUBLISHED_ASSIGNMENT_CONFLICT"); if (parsed.decision === "APPROVED") { const balance = await this.balance(tx, current.employeeUserId); if (workingDays(current.startDate, current.endDate) > balance.remaining) throw new LeaveDomainError("INSUFFICIENT_BALANCE"); }
    const row = await leaveRepository.updateRequest(tx, current.id, current.version, { status: parsed.decision, decisionResponse: parsed.response, reviewedByUserId: actor.id, decidedAt: new Date() }); if (!row) throw new LeaveDomainError("STALE_VERSION"); const balance = await this.balance(tx, current.employeeUserId); await this.audit(tx, actor, parsed.decision === "APPROVED" ? "leave.approved" : "leave.rejected", row.id, { employeeUserId: row.employeeUserId, state: row.status, workingDays: workingDays(row.startDate, row.endDate), allowance: balance.allowance, remaining: balance.remaining, scheduleImpactCount: publishedImpact.length, responseProvided: Boolean(row.decisionResponse) }); await this.notificationWriter(tx, { recipientUserId: row.employeeUserId, eventType: parsed.decision === "APPROVED" ? "leave.approved" : "leave.rejected", relatedRecordType: "leave_request", relatedRecordId: row.id }); return row; }); }
  async getAllowance(actor: AuthenticatedActor) { if (actor.role !== "SUPER_ADMIN") throw new LeaveDomainError("NOT_FOUND"); const setting = await leaveRepository.allowance(db); if (!setting) throw new Error("Leave allowance setting is missing."); return setting; }
  async updateAllowance(actor: AuthenticatedActor, input: unknown) { if (actor.role !== "SUPER_ADMIN") throw new LeaveDomainError("FORBIDDEN"); const parsed = parseLeave(allowanceUpdateSchema, input); return db.transaction(async (tx) => { await leaveRepository.lockAllowance(tx); const current = await leaveRepository.allowance(tx); if (!current || current.version !== parsed.expectedVersion) throw new LeaveDomainError("STALE_VERSION"); const year = dubaiCalendarYear(); if (parsed.annualWorkingDays < current.annualWorkingDays) { const employeeIds = await leaveRepository.approvedEmployeeIds(tx); for (const { employeeUserId } of employeeIds) if ((await this.balance(tx, employeeUserId, year)).used > parsed.annualWorkingDays) throw new LeaveDomainError("UNSAFE_ALLOWANCE_REDUCTION"); }
    const row = await leaveRepository.updateAllowance(tx, current.version, parsed.annualWorkingDays); if (!row) throw new LeaveDomainError("STALE_VERSION"); await this.audit(tx, actor, "leave.allowance_updated", "global", { annualWorkingDays: row.annualWorkingDays }); return row; }); }
  async approvedUnavailabilityForAdmin(actor: AuthenticatedActor) { if (actor.role !== "ADMIN") throw new LeaveDomainError("FORBIDDEN"); const grants = await leaveRepository.activeGrants(db, actor.id); const rows = await leaveRepository.visibleApproved(db, grants.filter((grant) => grant.scopeType === "TEAM").map((grant) => grant.scopeReference)); return rows.map(({ employeeName, request }) => ({ employeeName, employeeUserId: request.employeeUserId, startDate: request.startDate, endDate: request.endDate, status: request.status })); }
}
export async function assertEmployeeAvailableForSchedule(tx: LeaveTransaction, employeeUserId: string, assignmentDate: string) { await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`leave:${employeeUserId}`}))`); if ((await leaveRepository.approvedIntersecting(tx, employeeUserId, assignmentDate, assignmentDate)).length) throw new LeaveDomainError("APPROVED_UNAVAILABLE"); }
export const leaveService = new LeaveService();
